"""Unified component and spatial editor regressions. Offline concept only.
Real inline Vue Flow in Chromium; model setup/cancellation probes explicitly labeled.
No native host, filesystem adapter, CLI execution or production build is exercised.
"""
import hashlib,json
from pathlib import Path
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[2]
HTML=ROOT/'docs/concepts/companion/index.html'
OUT=ROOT/'reports/concepts/unified';OUT.mkdir(parents=True,exist_ok=True)
checks=[];errors=[];requests=[];fatal=None

def ok(name,result=True,scope='browser interaction'):
    checks.append({'name':name,'result':'passed' if result else 'failed','scope':scope})
    assert result,name
    print('PASS',name,flush=True)
def act(p,a,v=None,scope=''):
    s=f'{scope} [data-action="{a}"]'+(f'[data-value="{v}"]' if v is not None else '')
    p.locator(s.strip()).first.click()
def j(p,s):return p.evaluate(s)
def center(r):return (r['x']+r['width']/2,r['y']+r['height']/2)
def card(p,id):return p.locator(f'.map-node[data-node="{id}"]')
def wait(p):p.wait_for_timeout(140)
def photo(p,name):p.screenshot(path=str(OUT/(name+'.png')))
def close(p):
    act(p,'close',scope='#modal')
    if p.locator('#discard-dialog[open]').count():p.locator('#discard-confirm').click()
def compact(p):
    if p.locator('.outline-tree').is_visible():act(p,'ref-panel-close',scope='.outline-tree')
    act(p,'canvas-fit');wait(p)
def drag(p,id,dx,dy,hold=False):
    x,y=center(card(p,id).locator('.map-card-title').bounding_box())
    p.mouse.move(x,y);p.mouse.down();p.mouse.move(x+dx,y+dy,steps=15)
    if not hold:p.mouse.up();wait(p)
def draw(p,source='node-3',target='node-5'):
    card(p,source).hover();wait(p)
    a=p.locator(f'[data-port-node="{source}"][data-port-side="right"]')
    z=p.locator(f'[data-port-node="{target}"][data-port-side="left"]')
    x,y=center(a.bounding_box());tx,ty=center(z.bounding_box())
    p.mouse.move(x,y);p.mouse.down();p.mouse.move(tx,ty,steps=20);p.mouse.up()
    p.wait_for_selector('#modal[open] [data-action="design-link-save"]')

with sync_playwright() as pw:
    browser=pw.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=['--no-sandbox'])
    def new(width=1600,height=1000,theme='light'):
        p=browser.new_page(viewport={'width':width,'height':height});p.set_default_timeout(6500)
        p.on('pageerror',lambda e:errors.append(str(e)))
        p.on('console',lambda m:errors.append(m.text) if m.type=='error' else None)
        p.on('request',lambda r:requests.append(r.url))
        p.set_content(HTML.read_text());act(p,'sample',scope='main')
        p.evaluate('(t)=>{state.settings.theme=t;render();}',theme)
        if width<650:act(p,'menu')
        act(p,'nav','sitemap','#sidebar');p.wait_for_selector('.vue-flow__node');wait(p)
        return p
    p=None
    try:
        p=new()
        ok('Every library definition has the same content-instance contract',j(p,'design().library.length===44 && design().library.every(c=>!!c.contentSpec&&Array.isArray(c.tags))'))
        ok('Expanded sample has no design-validation errors',j(p,'designIssues(design()).every(i=>i.level!=="error")'))
        act(p,'nav','components','#sidebar')
        ok('Library has one creation route, no family switch',p.locator('[data-action="library-filter"]').count()==0 and p.locator('[data-action="library-new-brick"]').count()==1)
        act(p,'unified-tag','website',scope='.library-filterbar')
        ok('Website tag filters the whole shared inventory',j(p,'libraryComponents().length>=10 && libraryComponents().every(c=>c.tags.includes("website"))'))
        act(p,'unified-tag','form',scope='.library-filterbar')
        ok('Multiple tags use an explicit intersection',j(p,'libraryComponents().length===2 && libraryComponents().every(c=>c.tags.includes("website")&&c.tags.includes("form"))'))
        act(p,'unified-clear');p.locator('[data-field="unified-tag-select"]').select_option('calendar')
        ok('Less common tags are available through the tag picker',j(p,'libraryComponents().length===1 && libraryComponents()[0].id==="pattern-calendar"'))
        act(p,'unified-clear');p.locator('[data-field="unified-sort"]').select_option('category')
        ok('Sorting groups categories deterministically',j(p,'(()=>{const a=libraryComponents().map(c=>c.category);return JSON.stringify(a)===JSON.stringify([...a].sort((a,b)=>a.localeCompare(b)))})()'))
        p.locator('[data-field="unified-sort"]').select_option('tag')
        ok('Tag sorting orders the shared inventory by primary tag',j(p,'(()=>{const a=libraryComponents().map(c=>c.tags[0]||"~");return JSON.stringify(a)===JSON.stringify([...a].sort((x,y)=>x.localeCompare(y)))})()'))
        p.locator('[data-field="unified-sort"]').select_option('usage')
        ok('Most-used sorting puts referenced definitions first',j(p,'componentUses(libraryComponents()[0].id).length>0'))
        p.locator('[data-field="product-component-filter"]').fill('not-in-library-739')
        ok('Search has a genuine zero-result state',j(p,'libraryComponents().length===0'))
        act(p,'unified-clear');p.locator('[data-field="product-component-filter"]').fill('record-card')
        # The original ID is discovered from source metadata, not a invented contract.
        old_id=j(p,'design().library.find(c=>c.name==="RecordCard").id')
        p.locator('[data-field="product-component-filter"]').fill('RecordCard')
        act(p,'product-component-select',old_id)
        ok('Previously separate UI component uses the same wireframe preview',p.locator('.library-brick-preview').count()==1)
        act(p,'library-place',old_id)
        p.locator('[data-field="library-place-node"]').select_option('node-2');act(p,'library-place-confirm')
        ok('Old UI contract now opens the standard component-instance editor',p.locator('[data-action="brick-save"]').count()==1)
        p.locator('[data-field="brick-title"]').fill('A reusable record summary');act(p,'brick-save')
        ok('UI component becomes an ordered card item, not a second binding',j(p,'bricksOf(design().nodes.find(n=>n.id==="node-2")).some(b=>b.title==="A reusable record summary") && design().nodes.find(n=>n.id==="node-2").components.length===0'))
        act(p,'nav','components','#sidebar');act(p,'unified-clear')
        p.locator('[data-field="product-component-filter"]').fill('pattern-hero');act(p,'product-component-select','pattern-hero')
        act(p,'product-component-edit','pattern-hero')
        p.locator('[data-field="unified-tags"]').fill('Website, LANDING, website, featured')
        p.locator('[data-field="product-form-version"]').fill('1.1.0');act(p,'product-component-save')
        ok('Tags normalize, deduplicate and persist on definition save',j(p,'JSON.stringify(design().library.find(c=>c.id==="pattern-hero").tags)===JSON.stringify(["featured","landing","website"])'))
        photo(p,'01-component-library')
        p.close();p=new();compact(p)
        # Hover/focus-only visibility never removes measurable handle DOM.
        p.mouse.move(300,220);j(p,'document.activeElement?.blur()');wait(p)
        invisible=card(p,'node-3').locator('.flow-port').first
        ok('Idle handles are transparent but keep their bounds',invisible.evaluate('e=>getComputedStyle(e).opacity==="0" && e.getBoundingClientRect().width>0'))
        card(p,'node-3').hover();wait(p)
        ok('Hover reveals card handles',invisible.evaluate('e=>getComputedStyle(e).opacity==="1"'))
        card(p,'node-3').locator('.map-card-title').click();p.mouse.move(300,220);wait(p)
        ok('Selected card retains its handles off hover',invisible.evaluate('e=>getComputedStyle(e).opacity==="1"'))
        p.locator('#vf-root .vue-flow__pane').click(position={'x':25,'y':150});j(p,'document.activeElement?.blur()');wait(p)
        ok('Blank pane clears the active card',j(p,'designUi.selected===null'))
        before=j(p,'design().links.length');draw(p)
        ok('Actual handle drag opens a reviewed link without saving',j(p,'design().links.length')==before)
        close(p);wait(p)
        ok('Cancelled drawing leaves no preview connection or pending handle',j(p,'!flowUi.connecting && !flowUi.api.connectionStartHandle.value') and p.locator('.vue-flow__connection').count()==0)
        draw(p);p.locator('[data-field="design-link-label"]').fill('Open configuration');act(p,'design-link-save');wait(p)
        edge=j(p,'design().links.at(-1).id')
        ok('Second draw after cancellation creates exactly one connection',j(p,'design().links.length')==before+1)
        anchors=j(p,'JSON.stringify(canvasState().anchors)');links=j(p,'JSON.stringify(design().links)');fp=j(p,'designFingerprint(design())')
        drag(p,'node-3',-90,-90)
        ok('Card movement preserves both structural and action endpoints',j(p,'JSON.stringify(canvasState().anchors)')==anchors and j(p,'JSON.stringify(design().links)')==links)
        ok('Movement leaves semantic generation inputs unchanged',j(p,'designFingerprint(design())')==fp)
        act(p,'design-undo');wait(p)
        ok('Undo preserves endpoint identities',j(p,'JSON.stringify(canvasState().anchors)')==anchors)
        act(p,'design-redo');wait(p)
        ok('Redo preserves endpoint identities',j(p,'JSON.stringify(canvasState().anchors)')==anchors)
        p.locator('.ref-arrange-popover summary').click();p.locator('#map-layout').select_option('horizontal');wait(p)
        ok('Applying another arrangement cannot repin existing connectors',j(p,'JSON.stringify(canvasState().anchors)')==anchors)
        # Explicit endpoint change uses the actual structural-edge editor.
        p.locator('.vue-flow__edge[data-id="contains-node-2"]').focus();p.keyboard.press('Enter')
        p.locator('[data-field="connection-structure-source"]').select_option('structure-out-left')
        p.locator('[data-field="connection-structure-target"]').select_option('structure-in-right');act(p,'connection-structure-save');wait(p)
        ok('Only an explicit line edit changes its chosen anchors',j(p,'canvasState().anchors["contains-node-2"].sourceHandle==="structure-out-left" && canvasState().anchors["contains-node-2"].targetHandle==="structure-in-right"'))
        ok('Endpoint-only editing remains outside generation fingerprint',j(p,'designFingerprint(design())')==fp)
        # Click handles still expose creation menus rather than leaving a line active.
        card(p,'node-3').locator('.map-card-title').click();act(p,'canvas-focus');wait(p)
        p.locator('[data-port-node="node-3"][data-port-side="right"]').click();wait(p)
        ok('A handle click opens its menu independently of drawing',p.locator('#connection-menu').is_visible())
        p.keyboard.press('Escape');wait(p)
        ok('Closing handle menu leaves the renderer in idle state',j(p,'!flowUi.connecting') and p.locator('.vue-flow__connection').count()==0)
        a=p.locator('[data-port-node="node-3"][data-port-side="right"]');x,y=center(a.bounding_box())
        p.mouse.move(x,y);p.mouse.down();p.mouse.move(x+60,y+40,steps=8);wait(p)
        ok('Drawing holds target handles visible during the gesture',j(p,'flowUi.connecting') and j(p,'document.querySelector("#vf-root").dataset.connecting==="true"'))
        p.keyboard.press('Escape');p.mouse.up();wait(p)
        ok('Escape fully resets a mid-draw gesture',j(p,'!flowUi.connecting&&!flowUi.api.connectionStartHandle.value') and p.locator('.vue-flow__connection').count()==0)
        # Intentional window event models an application losing focus.
        x,y=center(a.bounding_box());p.mouse.move(x,y);p.mouse.down();p.mouse.move(x+60,y+25,steps=6)
        p.evaluate('window.dispatchEvent(new Event("blur"))');p.mouse.up();wait(p)
        ok('Loss-of-focus cancellation clears drawing state',j(p,'!flowUi.connecting&&!flowUi.api.connectionStartHandle.value'),'synthetic window-focus lifecycle fixture')
        photo(p,'02-refined-card')
        p.close();p=new();compact(p)
        # Controlled two-position scene; the actual guideline gesture is driven by mouse.
        j(p,'''(()=>{const d=design();d.nodes=d.nodes.filter(n=>["node-1","node-2"].includes(n.id));d.links=[];d.nodes.forEach(n=>n.parent=null);const c=canvasState();c.positions={"node-1":{x:80,y:110},"node-2":{x:470,y:200}};c.snap=false;c.custom=true;c.zoom=.75;c.pan={x:100,y:20};c.fitted=true;render()})()''');wait(p)
        fp=j(p,'designFingerprint(design())');origin=j(p,'canvasState().positions["node-2"]')
        drag(p,'node-2',0,(110-200)*.75,hold=True);wait(p)
        ok('Dragging near a peer displays real alignment guides',p.locator('.alignment-guide').count()>0)
        photo(p,'03-alignment-guides');p.mouse.up();wait(p)
        ok('Guide snapping aligns the card top in diagram coordinates',abs(j(p,'canvasState().positions["node-2"].y')-110)<.01)
        ok('Alignment guides clear after release without source changes',p.locator('.alignment-guide').count()==0 and j(p,'designFingerprint(design())')==fp)
        act(p,'design-undo');wait(p)
        ok('One undo restores the pre-alignment position',j(p,'canvasState().positions["node-2"]')==origin)
        p.keyboard.down('Alt');drag(p,'node-2',0,(110-200)*.75,hold=True);wait(p)
        ok('Alt suspends alignment guidance and magnetic snapping',p.locator('.alignment-guide').count()==0)
        p.mouse.up();p.keyboard.up('Alt');wait(p)
        ok('Alt movement does not snap to the peer top',abs(j(p,'canvasState().positions["node-2"].y')-110)>1)
        act(p,'flow-settings',scope='.ref-main-dock')
        p.locator('[data-field="flow-guides"]').uncheck();p.locator('[data-field="flow-guideSnap"]').uncheck();close(p)
        ok('Guide visibility and snapping are independent preferences',j(p,'!canvasPreferences().guides && !canvasPreferences().guideSnap && designFingerprint(design())')==fp)
        p.close();p=new();compact(p)
        act(p,'ref-section',scope='.ref-main-dock');p.locator('[data-field="ref-section-name"]').fill('Application area');act(p,'ref-section-save');act(p,'canvas-fit');wait(p)
        ok('Empty section provides a visible card drop target',p.locator('.spatial-zone[data-section="section-1"]').is_visible() and 'Drop a card here' in p.locator('.spatial-zone[data-section="section-1"]').inner_text())
        fp=j(p,'designFingerprint(design())');rev=j(p,'design().revision');before=j(p,'JSON.stringify(canvasState().positions)')
        zone=p.locator('.spatial-zone[data-section="section-1"]').bounding_box();title=card(p,'node-5').locator('.map-card-title').bounding_box();x,y=center(title);tx,ty=center(zone)
        p.mouse.move(x,y);p.mouse.down();p.mouse.move(tx,ty,steps=25);wait(p)
        ok('Dragging a card into a section gives drop feedback',p.locator('.spatial-zone.drop-active[data-section="section-1"]').count()==1)
        photo(p,'04-section-drop');p.mouse.up();wait(p)
        ok('Dropping assigns only the visual membership',j(p,'sectionForCard(design(),"node-5")==="section-1"') and j(p,'designFingerprint(design())')==fp and j(p,'design().revision')==rev)
        geometry=j(p,'sectionZones(design()).find(z=>z.id==="section-1")')
        ok('Section bounds contain the entire card plus padding',j(p,'(()=>{const z=sectionZones(design()).find(z=>z.id==="section-1"),n=design().nodes.find(n=>n.id==="node-5"),p=canvasState().positions[n.id],s=brickSurfaceSize(n);return z.x<=p.x-39&&z.y<=p.y-63&&z.x+z.width>=p.x+s.width+39&&z.y+z.height>=p.y+s.height+39})()'))
        act(p,'design-undo');wait(p)
        ok('One undo restores drop position and membership together',j(p,'sectionForCard(design(),"node-5")==="main"') and j(p,'JSON.stringify(canvasState().positions)')==before)
        act(p,'design-redo');wait(p)
        ok('Redo restores section assignment',j(p,'sectionForCard(design(),"node-5")==="section-1"'))
        # Add actual content through the full-page component editor and observe bounds.
        card(p,'node-5').locator('.map-card-title').click();act(p,'canvas-focus');wait(p)
        act(p,'ref-content','node-5',scope='#ref-node-toolbar');act(p,'ref-editor-library');p.locator('#ref-library-search').fill('pattern-calendar');act(p,'ref-block-add');act(p,'ref-content-save');wait(p)
        ok('Section grows when its card content grows',j(p,'sectionZones(design()).find(z=>z.id==="section-1").height')>geometry['height'])
        n=card(p,'node-5');actual=n.bounding_box();model=j(p,'brickSurfaceSize(design().nodes.find(n=>n.id==="node-5"))');zoom=j(p,'canvasState().zoom')
        ok('Rendered card dimensions agree with spatial measurements',abs(actual['height']/zoom-model['height'])<2 and abs(actual['width']/zoom-model['width'])<2)
        ok('Card contents have consistent nonzero inner padding',n.evaluate('e=>parseFloat(getComputedStyle(e).paddingLeft)===8 && parseFloat(getComputedStyle(e).paddingRight)===8'))
        act(p,'ref-inspect','node-5',scope='#ref-node-toolbar')
        p.locator('[data-field="unified-section"]').select_option('main');wait(p)
        ok('Section assignment has a non-drag alternative',j(p,'sectionForCard(design(),"node-5")==="main"'))
        photo(p,'05-sections')
        p.close();p=new()
        # Compatibility, malicious data and exact thresholds are explicit model fixtures.
        result=j(p,'''(()=>{const d=designCopy(design());d.library=d.library.filter(c=>!c.id.startsWith('pattern-'));d.librarySchema=2;const c=d.library.find(c=>c.name==='RecordCard');delete c.contentSpec;delete c.tags;c.preview='record';const props=c.props;d.nodes[0].components=[{id:c.id,slot:'content',version:c.version}];const old=d.nodes[0].bricks.map(b=>b.id);ensureBrickLibrary(d);const first=JSON.stringify(d);ensureBrickLibrary(d);return {schema:d.librarySchema,contract:d.library.find(x=>x.id===c.id).props===props,preserved:old.every(id=>d.nodes[0].bricks.some(b=>b.id===id)),converted:d.nodes[0].components.length===0&&d.nodes[0].bricks.some(b=>b.definition===c.id),idempotent:first===JSON.stringify(d)}})()''')
        for field in ['contract','preserved','converted','idempotent']:ok('Legacy migration: '+field,result[field],'legacy-model fixture')
        ok('Library migration adopts schema 3 explicitly',result['schema']==3,'legacy-model fixture')
        ok('Invalid/future canvas and malformed tags are rejected',j(p,'!validCanvas({schema:99})&&!validAnchorMap({x:{source:"a",target:"b",sourceHandle:"script",targetHandle:"in-left"}})&&!validComponentTags(["<img>"])&&!validComponentTags(["tag","tag"])'),'validation-model fixture')
        result=j(p,'''(()=>{const d=designCopy(design());d.library=d.library.filter(c=>c.id!=='pattern-hero');ensureBrickLibrary(d);return !d.library.some(c=>c.id==='pattern-hero')})()''')
        ok('Deleted definitions are not reseeded on ordinary reads',result,'deletion-model fixture')
        ok('Guideline tolerance is stable in screen pixels',j(p,'alignPosition({x:90,y:90},{width:50,height:50},[{id:"a",x:100,y:100,width:50,height:50}],.5).guides.length===2&&alignPosition({x:90,y:90},{width:50,height:50},[{id:"a",x:100,y:100,width:50,height:50}],2).guides.length===0'),'geometry-model fixture')
        ok('Source plan uses ordered component instances',j(p,'productPlanFiles(design()).find(f=>f.path==="src/bootstrap/component-bindings.ts").content.includes("definition")'),'source-plan model fixture')
        ok('Visual endpoint ownership is part of portable canvas metadata',j(p,'(()=>{const d=portableDesign();return Object.keys(d.canvas.anchors).length>0 && !Object.hasOwn(generationSnapshot(design()),"canvas")})()'),'serialization-model fixture')
        ok('Overlapping imported section memberships are rejected',j(p,'!validReferenceSections([{id:"section-1",name:"A",roots:[],members:["node-1"]},{id:"section-2",name:"B",roots:[],members:["node-1"]}])'),'section-validation model fixture')
        ok('Missing legacy definitions remain visibly preserved',j(p,'(()=>{const d=designCopy(design());d.librarySchema=2;d.nodes[0].components.push({id:"missing-library-ref",slot:"content",version:"1.0.0"});ensureBrickLibrary(d);return d.nodes[0].components.some(b=>b.id==="missing-library-ref") && retainedBindingNotice(d.nodes[0]).includes("older placement")})()'),'legacy-model fixture')
        for i in range(4):
            act(p,'nav','components','#sidebar');act(p,'nav','sitemap','#sidebar');wait(p)
        ok('Repeated view switches leave one current renderer',p.locator('#vf-root .vue-flow').count()==1 and j(p,'!flowUi.connecting && !flowUi.dragging'))
        photo(p,'06-map-light');act(p,'theme');wait(p);photo(p,'07-map-dark');p.close()
        p=new(390,844,'dark');ok('Narrow canvas has no horizontal document overflow',j(p,'document.documentElement.scrollWidth<=innerWidth'))
        photo(p,'08-narrow-map');act(p,'menu');act(p,'nav','components','#sidebar');wait(p)
        ok('Narrow unified library has no horizontal document overflow',j(p,'document.documentElement.scrollWidth<=innerWidth'))
        photo(p,'09-narrow-library');p.close();p=None
        ok('Zero observed page/console errors',not errors,'observed runtime output')
        ok('Zero observed network requests',not requests,'observed network output')
    except Exception as e:
        fatal=str(e);print('FAILED',fatal,flush=True)
        if p:
            try:photo(p,'failure')
            except Exception:pass
    finally:
        browser.close()
        (OUT/'checks.json').write_text(json.dumps({'scope':'Browser concept only; model/event fixtures labeled. No native/CLI evidence.','html_sha256':hashlib.sha256(HTML.read_bytes()).hexdigest(),'checks':checks,'passed':sum(x['result']=='passed' for x in checks),'failed':sum(x['result']=='failed' for x in checks),'fatal':fatal,'errors':errors,'requests':requests},indent=2)+'\n')
if fatal:raise SystemExit(1)
