import type { Agent } from '../../domain/agents/types'
import type { PluginState } from '../../domain/shared/PluginState'
import type { CharacterRegionId } from '../../application/ports/CharacterSelection'
export type CharacterEditorMode = 'character' | 'world'
export type CharacterEditorCategoryId = CharacterRegionId
export interface CharacterEditorCategory { id: CharacterEditorCategoryId; icon: string; label: string; title: string; description: string; requirementId: string; accent: string }
export const CHARACTER_EDITOR_CATEGORIES: readonly CharacterEditorCategory[] = [
{id:'identity',icon:'◆',label:'Identity',title:'Identity & purpose',description:'Define who this agent is, why it exists, and how others should recognize it.',requirementId:'identity.mission',accent:'#a78bfa'},
{id:'appearance',icon:'◉',label:'Look',title:'Appearance & presence',description:'Create a recognizable teammate without using appearance as a proxy for capability or authority.',requirementId:'identity.embodiment',accent:'#f0abfc'},
{id:'mind',icon:'✦',label:'Mind',title:'Mind & instructions',description:'Shape goals, operating instructions, and autonomy without one monolithic prompt.',requirementId:'instructions.scopes',accent:'#67e8f9'},
{id:'skills',icon:'✧',label:'Skills',title:'Skills',description:'Attach reusable procedural capabilities: the character’s learned techniques.',requirementId:'skills.packaging',accent:'#6ee7b7'},
{id:'tools',icon:'⚒',label:'Tools',title:'Tools',description:'Equip bounded actions and retrieval capabilities with explicit risk.',requirementId:'tools.boundaries',accent:'#fdba74'},
{id:'memory',icon:'▦',label:'Memory',title:'Memory & vault',description:'Configure working context, durable knowledge, retrieval, and path scope.',requirementId:'memory.long',accent:'#5eead4'},
{id:'safety',icon:'⚑',label:'Safety',title:'Safety & autonomy',description:'Set guardrails, approvals, stop conditions, and the permission envelope.',requirementId:'safety.guardrails',accent:'#fda4af'},
{id:'network',icon:'↔',label:'Network',title:'Relations & delegation',description:'Define delegation, consultation, review, inheritance, and collaboration.',requirementId:'relations.multiagent',accent:'#93c5fd'},
{id:'character',icon:'♟',label:'Sheet',title:'Character sheet',description:'Express strengths and learned capabilities through the GURPS-compatible sheet.',requirementId:'identity.mission',accent:'#c4b5fd'},
{id:'evals',icon:'✓',label:'Evals',title:'Evaluation & evidence',description:'Attach scenario evidence rather than treating configuration coverage as quality.',requirementId:'evals.feedback',accent:'#86efac'},
{id:'runtime',icon:'↗',label:'Runtime',title:'Runtime & projection',description:'Project one neutral character definition into runtime-specific files.',requirementId:'runtime.adapters',accent:'#f0abfc'}] as const
const positive=(value:unknown)=>Boolean(Array.isArray(value)?value.length:typeof value==='string'?value.trim():value)
export const agentConfigurationCoverage=(agent:Agent):number=>{const checks=[positive(agent.description),positive(agent.appearance.modelId),positive(agent.appearance.primaryColor),agent.goals.length>1,agent.skillIds.length>0,agent.toolIds.length>0,agent.pathPolicies.length>0,agent.guardrailIds.length>0,agent.evals.length>0];return Math.round(checks.filter(Boolean).length/checks.length*100)}
export const categoryReadiness=(agent:Agent,state:PluginState,category:CharacterEditorCategoryId):number=>{const ratio=(c:boolean[])=>c.length?Math.round(c.filter(Boolean).length/c.length*100):0;switch(category){case'identity':return ratio([positive(agent.name),positive(agent.description),positive(agent.roleId),positive(agent.invocation.handoffDescription)]);case'appearance':return ratio([positive(agent.appearance.modelId),positive(agent.appearance.primaryColor),positive(agent.appearance.teamNickname||agent.name),agent.appearance.scale>=.75&&agent.appearance.scale<=1.3]);case'mind':return ratio([positive(agent.systemPrompt),agent.goals.length>1,agent.instructionLayerIds.length>0,agent.autonomy.maxSteps>0]);case'skills':return ratio([agent.skillIds.length>0,agent.skillIds.every(id=>state.skills.some(x=>x.id===id))]);case'tools':return ratio([agent.toolIds.length>0,agent.toolIds.every(id=>state.tools.some(x=>x.id===id))]);case'memory':return ratio([agent.shortTermMemory.tokenBudget>0,positive(agent.shortTermMemory.retrieval),positive(agent.longTermMemory.summaryPath),agent.pathPolicies.length>0]);case'safety':return ratio([agent.guardrailIds.length>0,positive(agent.autonomy.approvalPolicy),agent.autonomy.stopConditions.length>0]);case'network':return ratio([state.relations.some(r=>r.fromAgentId===agent.id||r.toAgentId===agent.id)]);case'character':return ratio([agent.gurps.pointTotal>0,agent.gurps.skills.length>0]);case'evals':return ratio([agent.evals.length>0,agent.evals.some(e=>e.status==='passing')]);case'runtime':return ratio([state.runtimeAdapters.length>0,state.runtimeAdapters.some(a=>!a.generated)])}}
export const relationPeerId=(agentId:string,relation:{fromAgentId:string;toAgentId:string})=>relation.fromAgentId===agentId?relation.toAgentId:relation.fromAgentId
export const toggleMembership=(values:readonly string[],id:string):string[]=>values.includes(id)?values.filter(v=>v!==id):[...values,id]
