// source-project-split AC-3: acceptance test stub generated by `node scripts/delivery/acceptance.mjs stubs`.
// Replace the pending test with assertions that prove the criterion; this file then is its Evidence.
// Increment: [[docs/increments/source-project-split]]
// AC-3: Compilers and starter generation emit a coherent named-source plugin project with working local imports.
import test from 'node:test';

test.todo('source-project-split AC-3: Compilers and starter generation emit a coherent named-source plugin project with working local imports.');
