import {activeScenario,announce,clone,commit,dateText,esc,euro,num,stateRef,uid} from "./core.ts";
import {baselineComparison,scenarioMetrics} from "./metrics.ts";
import {exportMarkdownZip,markdownPreviewHtml} from "./persistence.ts";
import {render} from "./render.ts";
import {openDialog} from "./dialogs-common.ts";

export function commercialDialog() {
  const scenario=activeScenario(),m=scenarioMetrics(scenario),costs=(scenario.nonLaborCosts||[]).map(cost=>`<div class="management-row"><div><strong>${esc(cost.name)}</strong><span>planned ${euro.format(cost.planned)} · actual ${euro.format(cost.actual)}</span></div><div class="row-actions"><button type="button" data-action="edit-nonlabor" data-cost-id="${esc(cost.id)}">Edit</button><button type="button" data-action="remove-nonlabor" data-cost-id="${esc(cost.id)}">Remove</button></div></div>`).join("");
  const partial=!m.forecastComplete,coverage=`${num.format(m.scopeCoverage*100)}%`;
  openDialog(`Commercials · ${scenario.name}`,`<div class="commercial-grid"><div class="metric-preview"><span>${partial?"Covered forecast":"Forecast incl. contingency"}</span><strong>${euro.format(m.forecastWithContingency)}</strong><small>${partial?`${coverage} of scope costed · ${num.format(m.unallocatedHours)} h unpriced`:`Budget ${euro.format(scenario.budget)}`}</small></div><div class="metric-preview"><span>${partial?"Covered margin":"Forecast margin"}</span><strong>${euro.format(m.margin)}</strong><small>${num.format(m.marginPct*100)}% vs ${num.format(scenario.targetMarginPct)}% target</small></div><div class="metric-preview"><span>Actual internal cost</span><strong>${euro.format(m.actualInternalCost)}</strong><small>Actual rates are snapshotted with bookings</small></div><div class="metric-preview"><span>ETC labor</span><strong>${euro.format(m.etcLaborCost)}</strong><small>${num.format(m.etcHours)} allocated hours remaining</small></div></div>${partial?`<div class="callout">This forecast is incomplete until the remaining ${num.format(m.unallocatedHours)} h of scope is allocated to roles/iterations. Budget variance and margin are therefore shown as covered values, not final EAC.</div>`:""}<div class="dialog-section-head"><div><strong>Non-labor costs</strong><span>Planned and actual commercial items.</span></div><button type="button" data-action="add-nonlabor">Add cost</button></div><div class="management-list">${costs||`<div class="empty">No non-labor costs.</div>`}</div><div class="callout subtle">Role rates can vary by iteration in Plan FTE. Role budget buckets are configured in Team → Role.</div>`,null,"",{hideSubmit:true});
}
export function nonLaborDialog(costId=null) {
  const scenario=activeScenario(),cost=costId?scenario.nonLaborCosts.find(item=>item.id===costId):null;
  openDialog(cost?`Cost · ${cost.name}`:"Add non-labor cost",`<div class="form-grid"><label class="wide">Name<input name="name" required maxlength="80" value="${cost?esc(cost.name):""}"></label><label>Planned (€)<input name="planned" type="number" min="0" step="100" required value="${cost?esc(cost.planned):"0"}"></label><label>Actual (€)<input name="actual" type="number" min="0" step="100" required value="${cost?esc(cost.actual):"0"}"></label></div>`,data=>{const name=String(data.get("name")||"").trim(),planned=Number(data.get("planned")),actual=Number(data.get("actual"));if(!name||!Number.isFinite(planned)||!Number.isFinite(actual)||planned<0||actual<0){announce("Enter valid cost values.");return false;}if(cost){cost.name=name;cost.planned=planned;cost.actual=actual;commit("commercial.cost.updated",name);}else{scenario.nonLaborCosts.push({id:uid("cost"),name,planned,actual});commit("commercial.cost.created",name);}render();announce(cost?"Cost saved.":"Cost added.");return true;},cost?"Save cost":"Add cost");
}
export function removeNonLabor(costId) {const scenario=activeScenario(),cost=scenario.nonLaborCosts.find(item=>item.id===costId);if(!cost)return;scenario.nonLaborCosts=scenario.nonLaborCosts.filter(item=>item.id!==costId);commit("commercial.cost.removed",cost.name);render();announce("Non-labor cost removed.");}

export function baselinesDialog() {
  const scenario=activeScenario(),items=stateRef.state.baselines.filter(item=>item.scenarioId===scenario.id),rows=items.map(item=>{const diff=baselineComparison(item,scenario);return `<div class="baseline-row"><div><strong>${esc(item.name)}${item.approvedAt?" · approved":""}</strong><span>r${item.revision} · ${dateText(item.createdAt.slice(0,10))} · Δ forecast ${euro.format(diff.costDelta)} · Δ hours ${num.format(diff.hoursDelta)}</span></div><div class="row-actions">${!item.approvedAt?`<button type="button" data-action="approve-baseline" data-baseline-id="${esc(item.id)}">Approve</button>`:""}<button type="button" data-action="restore-baseline" data-baseline-id="${esc(item.id)}">Restore as plan</button></div></div>`;}).join("");
  openDialog(`Baselines · ${scenario.name}`,`<div class="dialog-section-head"><div><strong>Immutable plan snapshots</strong><span>Use an approved baseline as the review reference; restore creates a new scenario rather than overwriting history.</span></div><button type="button" data-action="create-baseline">Create baseline</button></div><div class="management-list">${rows||`<div class="empty">No baselines for this plan yet.</div>`}</div>`,null,"",{hideSubmit:true});
}
export function createBaselineDialog() {
  const scenario=activeScenario();openDialog("Create baseline",`<div class="form-grid"><label class="wide">Baseline name<input name="name" required maxlength="80" value="${esc(scenario.name)} · r${stateRef.state.revision}"></label><label>Approve immediately<select name="approve"><option value="false">No · review snapshot</option><option value="true">Yes · approved baseline</option></select></label></div><div class="formula">The snapshot stores the active scenario plus the project timeline, roles, people, tasks and holidays needed to explain the plan at this revision.</div>`,data=>{const name=String(data.get("name")||"").trim(),approve=String(data.get("approve"))==="true";if(!name){announce("Baseline name is required.");return false;}const createdAt=new Date().toISOString(),baseline={id:uid("baseline"),scenarioId:scenario.id,name,createdAt,approvedAt:approve?createdAt:null,revision:stateRef.state.revision,summary:scenarioMetrics(scenario),snapshot:{scenario:clone(scenario),project:{iterations:clone(stateRef.state.project.iterations),roles:clone(stateRef.state.project.roles),people:clone(stateRef.state.project.people),tasks:clone(stateRef.state.project.tasks),holidays:clone(stateRef.state.project.holidays)}}};stateRef.state.baselines.unshift(baseline);commit("baseline.created",`${name}${approve?" approved":""}`);render();announce("Baseline snapshot created.");return true;},"Create baseline");
}
export function approveBaseline(baselineId) {const baseline=stateRef.state.baselines.find(item=>item.id===baselineId);if(!baseline||baseline.approvedAt)return;baseline.approvedAt=new Date().toISOString();commit("baseline.approved",baseline.name);render();announce(`${baseline.name} approved.`);baselinesDialog();}
export function restoreBaseline(baselineId) {const baseline=stateRef.state.baselines.find(item=>item.id===baselineId);if(!baseline)return;const restored=clone(baseline.snapshot.scenario);restored.id=uid("scenario");restored.name=`${baseline.name} restored`;restored.status="draft";restored.createdAt=new Date().toISOString();stateRef.state.scenarios.push(restored);stateRef.state.activeScenarioId=restored.id;commit("baseline.restored",`${baseline.name} restored as ${restored.name}`);render();announce(`${restored.name} opened.`);if(document.querySelector("dialog[open]"))document.querySelector("dialog[open]").close();}

export function auditDialog() {
  const rows=stateRef.state.audit.slice(0,100).map(item=>`<div class="audit-row"><span>r${item.revision}</span><strong>${esc(item.action)}</strong><span>${esc(item.detail)}</span><time>${esc(new Date(item.at).toLocaleString())}</time></div>`).join("");
  openDialog("Audit & revisions",`<div class="callout subtle">Workspace ${esc(stateRef.state.id)} · current revision r${stateRef.state.revision}. Imports compare revision tokens according to the configured conflict policy.</div><div class="audit-list">${rows}</div>`,null,"",{hideSubmit:true});
}
export function persistenceDialog() {
  const p=stateRef.state.project.persistence;
  openDialog("Obsidian persistence contract",`<div class="form-grid"><label class="wide">Base path<input name="basePath" required value="${esc(p.basePath)}"></label><label>Project path<input name="projectPath" required value="${esc(p.projectPath)}"></label><label>Resource plans<input name="scenarioPath" required value="${esc(p.scenarioPath)}"></label><label>Iterations<input name="iterationPath" required value="${esc(p.iterationPath)}"></label><label>Roles<input name="rolePath" required value="${esc(p.rolePath)}"></label><label>People<input name="personPath" required value="${esc(p.personPath)}"></label><label>Tasks<input name="taskPath" required value="${esc(p.taskPath)}"></label><label>Actuals<input name="actualPath" required value="${esc(p.actualPath||"Actuals")}"></label><label>Baselines<input name="baselinePath" required value="${esc(p.baselinePath)}"></label><label>Audit<input name="auditPath" required value="${esc(p.auditPath)}"></label><label>Import conflict policy<select name="conflictPolicy"><option value="warn" ${p.conflictPolicy==="warn"?"selected":""}>Warn and ask</option><option value="block-old" ${p.conflictPolicy==="block-old"?"selected":""}>Block older revision</option></select></label></div>${markdownPreviewHtml()}<div class="dialog-section-head"><div><strong>Portable Markdown handoff</strong><span>Self-contained prototype cannot write into a vault; it exports the exact configured Markdown files as a ZIP.</span></div><button type="button" data-action="export-markdown">Export Markdown ZIP</button></div>`,data=>{for(const key of ["basePath","projectPath","scenarioPath","iterationPath","rolePath","personPath","taskPath","actualPath","baselinePath","auditPath"]){const value=String(data.get(key)||"").trim().replace(/^\/+|\/+$/g,"");if(!value){announce("All persistence paths are required.");return false;}p[key]=value;}p.conflictPolicy=String(data.get("conflictPolicy"));commit("persistence.updated",`Base path ${p.basePath}`);render();announce("Persistence contract saved.");return true;},"Save persistence");
}
export function scenarioComparisonDialog() {
  const rows=stateRef.state.scenarios.filter(item=>item.status!=="archived").map(item=>{const m=scenarioMetrics(item),partial=!m.forecastComplete;return `<tr class="${item.id===stateRef.state.activeScenarioId?"selected-row":""}"><td>${esc(item.name)}</td><td>${esc(item.status)}</td><td>${euro.format(item.budget)}</td><td>${partial?"Covered ":""}${euro.format(m.forecastWithContingency)}</td><td>${num.format(m.scopeCoverage*100)}%</td><td>${euro.format(m.budgetVariance)}</td><td>${num.format(m.marginPct*100)}%</td><td>${num.format(m.unallocatedHours)} h</td><td><button type="button" data-action="activate-scenario" data-scenario-id="${esc(item.id)}">Open</button></td></tr>`;}).join("");
  openDialog("Compare resource plans",`<div class="callout subtle">Forecast and margin remain covered values while a plan has unallocated scope. Coverage makes that uncertainty explicit instead of treating incomplete plans as fully forecast.</div><div class="table-scroll"><table class="compare-table"><thead><tr><th>Plan</th><th>Status</th><th>Budget</th><th>Forecast</th><th>Coverage</th><th>Variance</th><th>Margin</th><th>Open work</th><th></th></tr></thead><tbody>${rows}</tbody></table></div>`,null,"",{hideSubmit:true});
}
