// main-reconciliation AC-1: acceptance test stub generated by `node scripts/delivery/acceptance.mjs stubs`.
// Replace the pending test with assertions that prove the criterion; this file then is its Evidence.
// Increment: [[docs/increments/main-reconciliation]]
// AC-1: Workbench CLI sources live under src/cli and a built bin copy runs without the source checkout or installed framework dependencies. Evidence: `tests/acceptance/main-reconciliation/ac-1.checks.mjs`
import test from 'node:test';

test.todo('main-reconciliation AC-1: Workbench CLI sources live under src/cli and a built bin copy runs without the source checkout or installed framework dependencies. Evidence: `tests/acceptance/main-reconciliation/ac-1.checks.mjs`');
