import {activeScenario,announce,commit,dateText,dialog,esc,euro,num,stateRef,uid} from "./core.ts";
import {personAvailability,roleEnvelope,rolePlan} from "./metrics.ts";
import {render} from "./render.ts";
import {openDialog,parseLines} from "./dialogs-common.ts";

export function teamDialog() {
  const p=stateRef.state.project,roles=p.roles.map(role=>{const people=p.people.filter(person=>person.roleId===role.id&&!person.inactive);const first=p.iterations[0],env=first?roleEnvelope(role,first):{fte:0};return `<div class="management-row"><div><strong>${esc(role.name)}${role.inactive?" · inactive":""}</strong><span>${people.length} people · ${num.format(env.fte)} FTE available in ${esc(first?.name||"timeline")} · ${euro.format(role.dayRate)}/PT</span></div><div class="row-actions"><button type="button" data-action="edit-role" data-role-id="${esc(role.id)}">Edit</button><button type="button" data-action="plan-fte" data-role-id="${esc(role.id)}">Plan FTE</button></div></div>`;}).join(""),people=p.people.map(person=>{const role=p.roles.find(r=>r.id===person.roleId),leave=(person.leave||[]).length;return `<div class="management-row"><div><strong>${esc(person.name)}${person.inactive?" · inactive":""}</strong><span>${esc(role?.name||"No role")} · ${num.format(person.baseFte)} base FTE · ${leave} leave entries</span></div><div class="row-actions"><button type="button" data-action="edit-person" data-person-id="${esc(person.id)}">Edit</button><button type="button" data-action="person-availability" data-person-id="${esc(person.id)}">Availability</button></div></div>`;}).join("");
  openDialog("Team & role catalog",`<div class="dialog-section-head"><div><strong>Roles</strong><span>Commercial rate, manual fallback envelope and role budget bucket.</span></div><button type="button" data-action="add-role">Add role</button></div><div class="management-list">${roles||`<div class="empty">No roles yet.</div>`}</div><div class="dialog-section-head"><div><strong>People</strong><span>Named people drive available FTE; leave and iteration overrides reduce availability.</span></div><button type="button" data-action="add-person">Add person</button></div><div class="management-list">${people||`<div class="empty">No people yet. Roles use their manual fallback FTE.</div>`}</div>`,null,"",{hideSubmit:true});
}
export function roleDialog(roleId=null) {
  const p=stateRef.state.project,role=roleId?p.roles.find(item=>item.id===roleId):null;
  openDialog(role?`Role · ${role.name}`:"Add role",`<div class="form-grid"><label class="wide">Role name<input name="name" required maxlength="60" value="${role?esc(role.name):""}"></label><label>Default day rate (€ / PT)<input name="dayRate" type="number" min="0" step="any" required value="${role?esc(role.dayRate):"850"}"></label><label>Manual fallback FTE<input name="manualFte" type="number" min="0" max="20" step="any" required value="${role?esc(role.manualFte):"1"}"></label><label>Role budget bucket (€)<input name="budgetCap" type="number" min="0" step="any" value="${role?esc(role.budgetCap||0):"0"}"></label><label>Status<select name="inactive"><option value="false" ${!role?.inactive?"selected":""}>Active</option><option value="true" ${role?.inactive?"selected":""}>Inactive</option></select></label></div><div class="formula">Named people assigned to this role override the manual FTE envelope. The fallback is used only when no active people exist for the role.</div>`,data=>{
    const name=String(data.get("name")||"").trim(),dayRate=Number(data.get("dayRate")),manualFte=Number(data.get("manualFte")),budgetCap=Number(data.get("budgetCap")||0),inactive=String(data.get("inactive"))==="true";if(!name||![dayRate,manualFte,budgetCap].every(Number.isFinite)){announce("Enter valid role settings.");return false;}
    if(role){role.name=name;role.dayRate=dayRate;role.manualFte=manualFte;role.budgetCap=budgetCap;role.inactive=inactive;commit("role.updated",name);}else{const created={id:uid("role"),name,dayRate,manualFte,budgetCap,inactive:false};p.roles.push(created);for(const scenario of stateRef.state.scenarios)scenario.rolePlans[created.id]={fteByIteration:{},rateByIteration:{}};commit("role.created",name);}
    render();announce(role?"Role saved.":`${name} added.`);return true;
  },role?"Save role":"Add role");
}
export function fteDialog(roleId) {
  const p=stateRef.state.project,scenario=activeScenario(),role=p.roles.find(item=>item.id===roleId);if(!role)return;const plan=scenario.rolePlans[role.id]||(scenario.rolePlans[role.id]={fteByIteration:{},rateByIteration:{}}),its=p.iterations,options=its.map(it=>`<option value="${esc(it.id)}">${esc(it.name)} · ${dateText(it.start)}</option>`).join(""),first=its[0];
  openDialog(`Plan FTE & rate · ${role.name}`,`<div class="form-grid"><label>From<select name="from">${options}</select></label><label>Through<select name="through">${options}</select></label><label>Planned FTE / week<input name="fte" type="number" min="0" max="20" step="any" required value="${esc(plan.fteByIteration[first?.id]||0)}"></label><label>Rate override (€ / PT)<input name="rate" type="number" min="0" step="any" placeholder="Default ${esc(role.dayRate)}"></label></div><div class="formula">Rate left blank uses the role default. Planned FTE may exceed people-derived availability for scenario exploration; the gap remains flagged.</div>`,data=>{
    const from=its.findIndex(it=>it.id===data.get("from")),through=its.findIndex(it=>it.id===data.get("through")),fte=Number(data.get("fte")),rateText=String(data.get("rate")||"").trim(),rate=rateText===""?null:Number(rateText);if(from<0||through<from||!Number.isFinite(fte)||fte<0||fte>20||(rate!==null&&!Number.isFinite(rate))){announce("Choose a valid range, FTE and rate.");return false;}
    for(let i=from;i<=through;i++){plan.fteByIteration[its[i].id]=fte;if(rate===null)delete plan.rateByIteration[its[i].id];else plan.rateByIteration[its[i].id]=rate;}commit("staffing.plan.updated",`${role.name}: ${num.format(fte)} FTE for iterations ${from+1}-${through+1}`);render();announce("FTE and rate plan saved.");return true;
  },"Save range");
  const from=dialog.querySelector('[name="from"]'),through=dialog.querySelector('[name="through"]');through.selectedIndex=Math.max(0,its.length-1);from.addEventListener("change",()=>{if(through.selectedIndex<from.selectedIndex)through.selectedIndex=from.selectedIndex;});
}
function parseLeave(text) {
  const result=[];for(const line of parseLines(text)){const [range,...label]=line.split("|");const [start,end]=range.split("..");if(!/^\d{4}-\d{2}-\d{2}$/.test(start)||!/^\d{4}-\d{2}-\d{2}$/.test(end))throw new Error(`Invalid leave: ${line}`);result.push({id:uid("leave"),start,end,label:label.join("|").trim()||"Leave"});}return result;
}
export function personDialog(personId=null) {
  const p=stateRef.state.project,person=personId?p.people.find(item=>item.id===personId):null,roles=p.roles.filter(role=>!role.inactive||role.id===person?.roleId),roleOptions=roles.map(role=>`<option value="${esc(role.id)}" ${role.id===person?.roleId?"selected":""}>${esc(role.name)}</option>`).join(""),leave=(person?.leave||[]).map(item=>`${item.start}..${item.end}|${item.label||"Leave"}`).join("\n");
  openDialog(person?`Person · ${person.name}`:"Add person",`<div class="form-grid"><label class="wide">Name<input name="name" required maxlength="60" value="${person?esc(person.name):""}"></label><label>Role<select name="roleId" required>${roleOptions}</select></label><label>Base FTE<input name="baseFte" type="number" min="0" max="2" step="any" required value="${person?esc(person.baseFte):"1"}"></label><label>Status<select name="inactive"><option value="false" ${!person?.inactive?"selected":""}>Active</option><option value="true" ${person?.inactive?"selected":""}>Inactive</option></select></label><label class="wide">Leave · one per line: YYYY-MM-DD..YYYY-MM-DD|Label<textarea name="leave" rows="5">${esc(leave)}</textarea></label></div><div class="formula">Leave subtracts only project working days and excludes project holidays. Iteration-specific FTE overrides are managed through Availability.</div>`,data=>{
    try{const name=String(data.get("name")||"").trim(),roleId=String(data.get("roleId")),baseFte=Number(data.get("baseFte")),inactive=String(data.get("inactive"))==="true";if(!name||!p.roles.some(role=>role.id===roleId)||!Number.isFinite(baseFte)||baseFte<0||baseFte>2)throw new Error("Enter valid person settings.");const leaveEntries=parseLeave(data.get("leave"));if(person){person.name=name;person.roleId=roleId;person.baseFte=baseFte;person.inactive=inactive;person.leave=leaveEntries;commit("person.updated",name);}else{p.people.push({id:uid("person"),name,roleId,baseFte,inactive:false,availabilityByIteration:{},leave:leaveEntries});commit("person.created",name);}render();announce(person?"Person saved.":`${name} added.`);return true;}catch(error){announce(error.message||"Person settings are invalid.");return false;}
  },person?"Save person":"Add person");
}
export function personAvailabilityDialog(personId) {
  const p=stateRef.state.project,person=p.people.find(item=>item.id===personId);if(!person)return;const its=p.iterations,options=its.map(it=>`<option value="${esc(it.id)}">${esc(it.name)} · ${dateText(it.start)}</option>`).join("");
  openDialog(`Availability · ${person.name}`,`<div class="form-grid"><label>From<select name="from">${options}</select></label><label>Through<select name="through">${options}</select></label><label>Available FTE override<input name="fte" type="number" min="0" max="2" step="any" value="${esc(person.baseFte)}" required></label></div><div class="callout subtle">Overrides represent onboarding, part-time changes or temporary availability. Leave is subtracted after the override.</div>`,data=>{const from=its.findIndex(it=>it.id===data.get("from")),through=its.findIndex(it=>it.id===data.get("through")),fte=Number(data.get("fte"));if(from<0||through<from||!Number.isFinite(fte)||fte<0||fte>2){announce("Choose a valid range and FTE.");return false;}for(let i=from;i<=through;i++)person.availabilityByIteration[its[i].id]=fte;commit("person.availability.updated",`${person.name}: ${num.format(fte)} FTE for iterations ${from+1}-${through+1}`);render();announce("Availability saved.");return true;},"Save availability");
  const from=dialog.querySelector('[name="from"]'),through=dialog.querySelector('[name="through"]');through.selectedIndex=Math.max(0,its.length-1);from.addEventListener("change",()=>{if(through.selectedIndex<from.selectedIndex)through.selectedIndex=from.selectedIndex;});
}
