import assert from 'node:assert/strict';
const { test } = await (process.env.VITEST ? import('vitest') : import('node:test'));
import { parseFrontmatter as dorFrontmatter } from '../../scripts/delivery/handoff.mjs';
import { createWorkspace, planThenApply, readyFragment } from '../support/increment-workspace.mjs';

const fails = (outcome, code) => { assert.equal(outcome.status, 'failed', JSON.stringify(outcome)); assert.equal(outcome.diagnostics[0].code, code, outcome.diagnostics[0].message); };
async function inWorkspace(options, body) {
  const ws = createWorkspace(options);
  try { await body(ws); } finally { ws.remove(); }
}
const newIncrement = (ws, options = {}) => planThenApply(ws, 'increment new', ['delivery'], { title: 'Delivery pipeline', owner: 'Luis', ...options });

test('increment new previews without writing, then creates the increment, kick-off pull request, issue and branch in one reviewed plan', () => inWorkspace({ delivery: true }, async ws => {
  const options = { title: 'Delivery pipeline', owner: 'Luis' };
  const preview = await ws.run('increment new', ['delivery'], options);
  assert.equal(preview.status, 'planned', JSON.stringify(preview.diagnostics));
  assert.equal(ws.exists('docs'), false); assert.deepEqual(ws.branches(), ['main']);
  assert.deepEqual(preview.data.changes.map(change => [change.path, change.status]), [
    ['docs/increments/delivery.md', 'create'], ['docs/pull-requests/delivery-kickoff.md', 'create'], ['docs/issues/delivery.md', 'create']]);
  assert.deepEqual(preview.data.steps, [{ kind: 'git-branch', name: 'increment/delivery', start: 'main', commit: ws.git('rev-parse', 'main'), switch: false, fetch: null }]);
  assert.deepEqual(preview.data.summary.created, { increment: 'docs/increments/delivery.md', pullRequest: 'docs/pull-requests/delivery-kickoff.md', issue: 'docs/issues/delivery.md', stubs: [] });
  assert.equal((await ws.run('increment new', ['delivery'], options)).data.planHash, preview.data.planHash, 'the same inputs plan the same hash');
  const applied = await ws.run('increment new', ['delivery'], { ...options, apply: preview.data.planHash });
  assert.equal(applied.status, 'applied'); assert.equal(applied.data.applied.written.length, 3);
  assert.deepEqual(applied.data.applied.steps, { name: 'increment/delivery', status: 'created', start: 'main' });
  assert.deepEqual(ws.branches(), ['increment/delivery', 'main']); assert.equal(ws.git('rev-parse', '--abbrev-ref', 'HEAD'), 'main');
  const increment = ws.read('docs/increments/delivery.md');
  assert.match(increment, /^pullRequests: \[delivery-kickoff\]\nissues: \[delivery\]\nbranch: "increment\/delivery"\nbase: main\n---/m);
  assert.match(increment, /<!-- wb:pull-requests generated by node bin\/app; edits here are replaced -->\n- \[\[docs\/pull-requests\/delivery-kickoff\|Kick-off: Delivery pipeline\]\] · New\n/);
  assert.match(increment, /- \[\[docs\/issues\/delivery\|Delivery pipeline\]\] · New\n/);
  assert.deepEqual(dorFrontmatter(increment.split('\n')).errors, [], 'the Definition of Ready parser reads the written frontmatter');
  assert.match(ws.read('docs/pull-requests/delivery-kickoff.md'), /^kind: kickoff\nincrement: delivery\nstatus: New\nhead: "increment\/delivery"\nbase: main\n/m);
  assert.match(ws.read('docs/issues/delivery.md'), /^status: New\nincrement: delivery\n---/m);
  fails(await ws.run('increment new', ['delivery'], options), 'INCREMENT_EXISTS');
}));

test('the plan hash binds the branch start commit: a new commit on main makes the reviewed plan stale', () => inWorkspace({ delivery: true }, async ws => {
  const preview = await ws.run('increment new', ['delivery'], { title: 'Delivery pipeline' });
  ws.write('CHANGE.md', 'moved\n'); ws.git('add', '-A'); ws.git('commit', '-q', '-m', 'move main');
  fails(await ws.run('increment new', ['delivery'], { title: 'Delivery pipeline', apply: preview.data.planHash }), 'PLAN_STALE');
  assert.equal(ws.exists('docs/increments/delivery.md'), false); assert.deepEqual(ws.branches(), ['main']);
}));

test('--no-issue and --no-branch leave them out; an existing branch is kept and --switch checks a new one out', () => inWorkspace({ delivery: true }, async ws => {
  const skipped = await newIncrement(ws, { 'no-issue': true, 'no-branch': true });
  assert.equal(skipped.status, 'applied'); assert.equal(ws.exists('docs/issues/delivery.md'), false); assert.deepEqual(ws.branches(), ['main']);
  assert.equal(skipped.data.summary.branch.status, 'skipped'); assert.equal(skipped.data.steps, undefined);
  ws.git('branch', 'increment/second');
  const kept = await planThenApply(ws, 'increment new', ['second'], { title: 'Second' });
  assert.equal(kept.data.summary.branch.status, 'exists');
  const switched = await planThenApply(ws, 'increment new', ['third'], { title: 'Third', switch: true });
  assert.equal(switched.data.applied.steps.status, 'created-and-switched'); assert.equal(ws.git('rev-parse', '--abbrev-ref', 'HEAD'), 'increment/third');
  fails(await ws.run('increment new', ['fourth'], { title: 'Fourth', switch: true, 'no-branch': true }), 'INVALID_OPTION');
  fails(await ws.run('increment new', ['fourth'], { title: 'Fourth', branch: true, 'no-branch': true }), 'INVALID_OPTION');
}));

test('outside a git work tree the branch is reported unavailable and an explicit --branch refuses', () => inWorkspace({ delivery: true, git: false }, async ws => {
  const planned = await ws.run('increment new', ['delivery'], { title: 'Delivery pipeline' });
  assert.equal(planned.status, 'planned'); assert.equal(planned.data.summary.branch.status, 'unavailable');
  fails(await ws.run('increment new', ['delivery'], { title: 'Delivery pipeline', branch: true }), 'GIT_UNAVAILABLE');
  fails(await ws.run('increment new', ['delivery'], {}), 'INCREMENT_INPUT_INVALID');
  fails(await ws.run('increment new', ['Not A Slug'], { title: 'x' }), 'INCREMENT_ID_INVALID');
}));

test('criteria from --input get pending acceptance stubs and default evidence in the same plan; existing stubs are kept', () => inWorkspace({ delivery: true }, async ws => {
  ws.write('handoff.md', readyFragment);
  ws.write('tests/acceptance/delivery/ac-2.checks.mjs', '// already written\n');
  ws.write('tests/acceptance/delivery/ac-9.checks.mjs', '// orphan\n');
  const created = await newIncrement(ws, { input: 'handoff.md' });
  assert.equal(created.status, 'applied', JSON.stringify(created.diagnostics));
  assert.deepEqual(created.data.summary.stubs.created, ['tests/acceptance/delivery/ac-1.checks.mjs']);
  assert.deepEqual(created.data.summary.stubs.existing, ['tests/acceptance/delivery/ac-2.checks.mjs']);
  assert.deepEqual(created.data.summary.stubs.orphans, ['tests/acceptance/delivery/ac-9.checks.mjs']);
  assert.ok(created.data.summary.warnings.some(warning => warning.code === 'ACCEPTANCE_STUB_ORPHAN'));
  const stub = ws.read('tests/acceptance/delivery/ac-1.checks.mjs');
  assert.match(stub, /test\.todo\('delivery AC-1: Given a planned pull request When it is published Then a draft exists'\)/);
  assert.match(stub, /\[\[docs\/increments\/delivery\]\]/); assert.match(stub, /\/\/ Then a draft exists/);
  assert.equal(ws.read('tests/acceptance/delivery/ac-2.checks.mjs'), '// already written\n', 'an existing stub is never overwritten');
  assert.match(ws.read('docs/increments/delivery.md'), /- \[ \] AC-1: Given a planned pull request When it is published Then a draft exists\n {2}Evidence: `tests\/acceptance\/delivery\/ac-1\.checks\.mjs`\n/);
}));

test('increment edit, scope, ac add, ac set and ref add plan exact span edits; a new criterion brings its stub', () => inWorkspace({ delivery: true }, async ws => {
  await newIncrement(ws, { 'no-branch': true });
  const before = ws.read('docs/increments/delivery.md');
  const edited = await planThenApply(ws, 'increment edit', ['delivery'], { size: 'L', title: 'Delivery pipeline v2' });
  assert.equal(edited.status, 'applied'); assert.deepEqual(edited.data.applied.written, ['docs/increments/delivery.md']);
  const after = ws.read('docs/increments/delivery.md');
  assert.equal(after, before.replace('title: "Delivery pipeline"', 'title: "Delivery pipeline v2"').replace('size: M', 'size: L').replace('# Delivery pipeline\n', '# Delivery pipeline v2\n'));
  ws.write('summary.md', 'A new summary paragraph.\n');
  await planThenApply(ws, 'increment edit', ['delivery'], { section: 'Summary', input: 'summary.md' });
  assert.match(ws.read('docs/increments/delivery.md'), /## Summary\n\nA new summary paragraph\.\n\n## Outcome/);
  await planThenApply(ws, 'increment scope add', ['delivery', 'The publish command']);
  await planThenApply(ws, 'increment out-of-scope add', ['delivery', 'Merging']);
  const scope = ws.read('docs/increments/delivery.md');
  assert.match(scope, /### In scope\n\n- The publish command\n\n### Out of scope\n\n- Merging\n/, 'a new item replaces the template placeholder');
  const added = await planThenApply(ws, 'increment ac add', ['delivery', 'Publishing twice adopts the existing draft']);
  assert.equal(added.status, 'applied'); assert.deepEqual(added.data.summary.stubs.created, ['tests/acceptance/delivery/ac-1.checks.mjs']);
  assert.ok(ws.exists('tests/acceptance/delivery/ac-1.checks.mjs'));
  await planThenApply(ws, 'increment ac set', ['delivery', 'AC-1'], { status: 'done', evidence: 'README.md' });
  assert.match(ws.read('docs/increments/delivery.md'), /- \[x\] AC-1: Publishing twice adopts the existing draft\n {2}Evidence: `README\.md`\n/);
  fails(await ws.run('increment ac set', ['delivery', 'AC-1'], {}), 'INCREMENT_INPUT_INVALID');
  fails(await ws.run('increment ac set', ['delivery', 'AC-7'], { status: 'done' }), 'INCREMENT_AC_NOT_FOUND');
  fails(await ws.run('increment ac set', ['delivery', 'AC-1'], { status: 'finished' }), 'INVALID_OPTION');
  await planThenApply(ws, 'increment ref add', ['delivery', '[[README]]']);
  assert.match(ws.read('docs/increments/delivery.md'), /^refs: \["\[\[README\]\]"\]$/m);
  fails(await ws.run('increment ref add', ['delivery', '[[docs/missing]]']), 'WIKILINK_UNRESOLVED');
  fails(await ws.run('increment ref add', ['delivery', '[[README]]']), 'INCREMENT_UNCHANGED');
  fails(await ws.run('increment edit', ['delivery'], {}), 'INCREMENT_INPUT_INVALID');
  fails(await ws.run('increment edit', ['missing'], { size: 'S' }), 'INCREMENT_NOT_FOUND');
}));

test('status transitions: Ready runs the Definition of Ready, refused moves name the allowed ones, Cancelled locks edits', () => inWorkspace({ delivery: true }, async ws => {
  await newIncrement(ws, { 'no-branch': true });
  const notReady = await ws.run('increment status', ['delivery', 'Ready']);
  fails(notReady, 'INCREMENT_NOT_READY'); assert.match(notReady.diagnostics[0].message, /DOR-0\d/);
  fails(await ws.run('increment status', ['delivery', 'Done']), 'INCREMENT_STATUS_TRANSITION');
  fails(await ws.run('increment status', ['delivery', 'Shipped']), 'INCREMENT_STATUS_TRANSITION');
  const refining = await planThenApply(ws, 'increment status', ['delivery', 'refining']);
  assert.deepEqual([refining.data.summary.statusBefore, refining.data.summary.statusAfter], ['New', 'Refining']);
  await planThenApply(ws, 'increment status', ['delivery', 'Cancelled']);
  fails(await ws.run('increment scope add', ['delivery', 'More']), 'INCREMENT_LOCKED');
  fails(await ws.run('pr new', ['delivery'], { title: 'Late' }), 'INCREMENT_LOCKED');
  assert.equal((await planThenApply(ws, 'increment status', ['delivery', 'Refining'])).status, 'applied', 'Cancelled reopens to Refining');
}));

test('a refined increment moves to Ready through the Definition of Ready; without delivery.json the structural gate decides', async () => {
  await inWorkspace({ delivery: true }, async ws => {
    ws.write('handoff.md', readyFragment);
    await newIncrement(ws, { input: 'handoff.md', 'no-branch': true });
    const ready = await planThenApply(ws, 'increment status', ['delivery', 'Ready']);
    assert.equal(ready.status, 'applied', JSON.stringify(ready.diagnostics)); assert.equal(ready.data.summary.readiness, 'definition-of-ready');
    assert.match(ws.read('docs/increments/delivery.md'), /^status: Ready$/m);
  });
  await inWorkspace({ delivery: false }, async ws => {
    ws.write('handoff.md', readyFragment);
    await newIncrement(ws, { input: 'handoff.md', 'no-branch': true });
    const ready = await planThenApply(ws, 'increment status', ['delivery', 'Ready']);
    assert.equal(ready.status, 'applied', JSON.stringify(ready.diagnostics)); assert.equal(ready.data.summary.readiness, 'structural');
  });
});

test('attach moves a New pull request to another increment and updates both lists', () => inWorkspace({ delivery: true }, async ws => {
  await newIncrement(ws, { 'no-branch': true });
  await planThenApply(ws, 'increment new', ['other'], { title: 'Other', 'no-branch': true });
  await planThenApply(ws, 'pr new', ['delivery'], { title: 'Hosting set', 'no-branch': true });
  const moved = await planThenApply(ws, 'increment attach', ['other', 'delivery-1']);
  assert.equal(moved.status, 'applied'); assert.deepEqual(moved.data.summary.moved, { pullRequest: 'delivery-1', from: 'delivery', to: 'other' });
  assert.match(ws.read('docs/increments/delivery.md'), /^pullRequests: \[delivery-kickoff\]$/m);
  assert.match(ws.read('docs/increments/other.md'), /^pullRequests: \[other-kickoff, delivery-1\]$/m);
  const pull = ws.read('docs/pull-requests/delivery-1.md');
  assert.match(pull, /^increment: other$/m); assert.match(pull, /- \[\[docs\/increments\/other\|Increment: Other\]\]/); assert.doesNotMatch(pull, /docs\/increments\/delivery\|/);
  fails(await ws.run('increment attach', ['other', 'delivery-1']), 'INCREMENT_UNCHANGED');
  const valid = await ws.run('increment validate');
  assert.equal(valid.data.drift.length, 0); assert.ok(!valid.data.documents.some(doc => doc.problems.some(problem => problem.code === 'INCREMENT_LINK_DRIFT')));
}));

test('delivery.json without the extension keys: no branch, base or issues keys are written and a warning says why', () => inWorkspace({ delivery: true, narrow: true }, async ws => {
  const created = await newIncrement(ws);
  assert.equal(created.status, 'applied');
  const increment = ws.read('docs/increments/delivery.md');
  assert.doesNotMatch(increment, /^(?:branch|base|issues):/m); assert.doesNotMatch(increment, /## Issues/);
  assert.deepEqual(created.data.summary.warnings.map(warning => warning.code), ['DELIVERY_SCHEMA_UNSUPPORTED', 'DELIVERY_SCHEMA_UNSUPPORTED']);
  assert.ok(ws.exists('docs/issues/delivery.md'), 'the issue still names its increment');
  assert.deepEqual(ws.branches(), ['increment/delivery', 'main']);
}));

test('write commands refuse a delivery.json pointing at other folders (DELIVERY_PATHS_DRIFT); read commands report it', () => inWorkspace({ delivery: true }, async ws => {
  await newIncrement(ws, { 'no-branch': true });
  const config = JSON.parse(ws.read('configs/delivery/delivery.json'));
  config.handoff.glob = 'docs/handoffs/*.md';
  ws.write('configs/delivery/delivery.json', JSON.stringify(config));
  fails(await ws.run('increment scope add', ['delivery', 'More']), 'DELIVERY_PATHS_DRIFT');
  const listed = await ws.run('increment list');
  assert.equal(listed.status, 'ok'); assert.equal(listed.data.drift[0].code, 'DELIVERY_PATHS_DRIFT');
  const validated = await ws.run('increment validate');
  assert.equal(validated.status, 'blocked'); assert.equal(validated.diagnostics[0].code, 'DELIVERY_PATHS_DRIFT');
}));
