const { test } = await (process.env.VITEST ? import('vitest') : import('node:test'));
import assert from 'node:assert/strict';
import { cp, mkdir, readFile, rename } from 'node:fs/promises';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { makerFixture, makerSourceRoot, installMakerFoundation, copyMakerSuite } from './maker-fixture.mjs';
import { applyFilePlan } from '../../scripts/shared/file-plan.ts';
import { parseArguments } from '../../bin/adapters/makers/arguments.ts';
import { planMaker } from '../../bin/adapters/makers/plan.ts';

// Plans and applies every built-in recipe, a generated local custom recipe and a pending locale through the
// real maker runtime (bin/adapters/makers) under the maker floors; generated bytes are checked by the makers suite.
const plan = (root, values) => planMaker(root, parseArguments(values));
async function apply(root, values) {
  const planned = await plan(root, values);
  await applyFilePlan(planned.plan);
  assert.ok((await plan(root, values)).plan.changes.every(change => change.status === 'unchanged'), values.join(' '));
  return planned;
}
const paths = planned => planned.plan.changes.filter(change => change.status === 'create').map(change => change.path);
async function authorFixture(root) {
  await installMakerFoundation(root); await copyMakerSuite(root);
  await mkdir(join(root, 'src/locales'), { recursive: true });
  await cp(join(makerSourceRoot, 'src/locales/en.json'), join(root, 'src/locales/en.json'));
  await mkdir(join(root, 'plugins'), { recursive: true });
  for (const file of ['api.ts', 'runtime.ts', 'registry.ts']) await cp(join(makerSourceRoot, 'plugins', file), join(root, 'plugins', file));
  await apply(root, ['feature', 'bookmarks', '--entity', 'bookmark']);
}

test('every built-in recipe composes its declared sources, registrations and targeted tests', () => makerFixture(async root => {
  await authorFixture(root);
  const created = {};
  for (const values of [
    ['view', 'dashboard', '--feature', 'bookmarks'], ['component', 'summary', '--feature', 'bookmarks'], ['store', 'draft', '--feature', 'bookmarks'],
    ['usecase', 'normalize', '--feature', 'bookmarks'], ['command', 'help', '--feature', 'bookmarks'], ['modal', 'rename', '--feature', 'bookmarks'],
    ['setting', 'compact', '--feature', 'bookmarks'], ['setting', 'header', '--feature', 'bookmarks', '--preference', 'hideObsidianViewHeader'],
    ['event', 'refreshed', '--feature', 'bookmarks'], ['listener', 'observe', '--feature', 'bookmarks', '--event', 'refreshed'],
    ['style', 'border', '--feature', 'bookmarks', '--view', 'dashboard'],
    ['file-extension', 'board', '--feature', 'bookmarks', '--extension', 'board'],
    ['file-extension', 'plain', '--feature', 'bookmarks', '--extension', 'plaintxt', '--format', 'text'],
    ['context-menu', 'share', '--feature', 'bookmarks', '--extensions', 'md,canvas'],
    ['entity', 'project-note', '--feature', 'bookmarks', '--preset', 'project', '--document'],
    ['plugin', 'sample-tool'],
  ]) created[values.slice(0, 2).join(' ')] = paths(await apply(root, values));
  assert.ok(created['view dashboard'].includes('src/presentation/stores/bookmarks-dashboard.ts'));
  assert.ok(!created['component summary'].some(path => path.includes('/stores/')));
  assert.ok(created['usecase normalize'].includes('src/features/bookmarks/normalize.usecase-action.ts'));
  assert.ok(created['event refreshed'].includes('tests/runtime/generated/bookmarks-refreshed-event-contract.test.ts'));
  assert.deepEqual(created['style border'], ['src/styles/generated/bookmarks-border.css']);
  assert.ok(created['plugin sample-tool'].includes('plugins/sample-tool/src/index.ts'));
  const authoring = await readFile(join(root, 'src/bootstrap/authoring.ts'), 'utf8');
  for (const local of ['bookmarksHelpCommand', 'bookmarksRenameModal', 'bookmarksNormalizeUsecase', 'bookmarksHeaderSetting', 'bookmarksObserveListener', 'bookmarksRefreshedEvent'])
    assert.match(authoring, new RegExp(local));
  assert.match(await readFile(join(root, 'src/presentation/components/generated/bookmarks-dashboard.vue'), 'utf8'), /styles\/generated\/bookmarks-border\.css/);
  assert.match(await readFile(join(root, 'src/bootstrap/native-integrations.ts'), 'utf8'), /bookmarksShareContextMenu/);
  assert.match(await readFile(join(root, 'plugins/registry.ts'), 'utf8'), /PluginObject as SampleToolPlugin/);
  await assert.rejects(plan(root, ['file-extension', 'board-two', '--feature', 'bookmarks', '--extension', 'board']), { message: 'NATIVE_EXTENSION_CONFLICT: .board is already registered by bookmarks-board' });
  await assert.rejects(plan(root, ['listener', 'late', '--feature', 'bookmarks', '--event', 'missing']), { code: 'ENOENT' });
  await assert.rejects(plan(root, ['style', 'card', '--feature', 'bookmarks', '--view', 'summary-missing']), { code: 'ENOENT' });
}));

test('a generated local recipe and pending locale run in a source checkout and an extracted kit layout', () => makerFixture(async root => {
  await authorFixture(root);
  const maker = await apply(root, ['maker', 'nudge']);
  assert.deepEqual(paths(maker).sort(), ['scripts/makers/custom/nudge.mjs', 'tests/tooling/custom-nudge.checks.mjs']);
  const recipe = await readFile(join(root, 'scripts/makers/custom/nudge.mjs'), 'utf8');
  assert.match(recipe, /new URL\('\.\.\/\.\.\/\.\.\/bin\/adapters\/makers\/', import\.meta\.url\)/);
  assert.match(recipe, /bin\/template\/bin\/adapters\/makers\//);
  assert.ok(paths(await apply(root, ['nudge', 'review', '--feature', 'bookmarks'])).includes('src/features/bookmarks/review.command.ts'));
  await assert.rejects(plan(root, ['maker', 'feature']), { message: 'CUSTOM_RECIPE_BUILTIN_CONFLICT' });
  await assert.rejects(plan(root, ['unknown', 'x', '--feature', 'bookmarks']), { message: 'Unknown maker. Use --list for the implemented catalog.' });
  const locale = await apply(root, ['locale', 'fr']);
  assert.deepEqual(paths(locale).sort(), ['src/locales/pending/fr.json', 'src/locales/pending/fr.status.json', 'tests/tooling/locale-fr.checks.mjs']);
  const status = JSON.parse(await readFile(join(root, 'src/locales/pending/fr.status.json'), 'utf8'));
  assert.deepEqual([status.status, status.selectable, status.fallback], ['pending-translation-review', false, 'en']);
  // An extracted kit ships the editable maker sources under bin/template and no project-level bin/adapters.
  await mkdir(join(root, 'bin/template/bin/adapters'), { recursive: true });
  await rename(join(root, 'bin/adapters/makers'), join(root, 'bin/template/bin/adapters/makers'));
  await mkdir(join(root, 'bin/template/scripts'), { recursive: true });
  await cp(join(root, 'scripts/makers'), join(root, 'bin/template/scripts/makers'), { recursive: true });
  await cp(join(root, 'scripts/shared'), join(root, 'bin/template/scripts/shared'), { recursive: true });
  const kitRecipe = await import(`${pathToFileURL(join(root, 'scripts/makers/custom/nudge.mjs')).href}?layout=kit`);
  assert.equal(kitRecipe.nudgeMaker.name, 'nudge');
  const outputs = new Map(); const registrations = [];
  await kitRecipe.nudgeMaker.plan({ tests: new Set(), async add(path, content) { outputs.set(path, content); }, async editArray(...entry) { registrations.push(entry[1]); } }, { owner: 'bookmarks', name: 'later' });
  assert.ok(outputs.has('src/features/bookmarks/later.command.ts'));
  assert.deepEqual([...new Set(registrations)].sort(), ['authoringFactories', 'authoringLocaleModules']);
}));
