import { getIteration, getItem, mondayOnOrAfter, plusDays, summary, type Workspace } from './model.ts';
import { esc, button, field, textarea, options, personOptions, statusBadge, badge, owner, type ViewState } from './ui.ts';
import { workForm } from './ceremonies.ts';
export interface DialogSpec { title: string; intro: string; body: string; submit: string; ownForm?: boolean }
export function dialogSpec(kind: string, state: Workspace, ui: ViewState, id = '', detail = ''): DialogSpec {
  const iteration = state.iterations.find(value=>value.id===ui.selectedId);
  const select = (label:string,name:string,content:string) => `<label class="field" for="f-${name}"><span>${esc(label)}</span><select id="f-${name}" name="${name}">${content}</select></label>`;
  switch (kind) {
    case 'iteration': {
      const edit = id ? getIteration(state,id) : null;
      const lastEnd = state.iterations.reduce((end,value)=>value.end>end?value.end:end,'');
      const start = edit?.start??mondayOnOrAfter(lastEnd&&lastEnd>=state.clock?plusDays(lastEnd,1):state.clock);
      const index = edit?.index??state.nextIteration;
      return {title:edit?'Edit iteration plan':'Create the next iteration',intro:'A clear goal is the only thing you need to start. Dates are prefilled; resources and scope can follow.',
        body:`<div class="index-preview">ITERATION <strong>${String(index).padStart(2,'0')}</strong><span>Automatic index · never reused</span></div>${field('What should become possible?','goal',edit?.goal??'','text',true)}${textarea('Description / why this matters','description',edit?.description??'')}<div class="form-grid">${field('Start date','start',start,'date',true)}${field('End date','end',edit?.end??plusDays(start,4),'date',true)}</div><p class="muted">Suggested rhythm: planning on the first day, a daily each working day, review and retro at the end. Monday starts are a default, not a restriction.</p>`,submit:edit?'Save plan':'Create iteration'};
    }
    case 'item':
    case 'feedback': {
      const item = id?getItem(state,id):null;
      const backlog = item?.backlogId??(ui.backlogFilter==='all'?state.backlogs[0].id:ui.backlogFilter);
      return {title:item?'Maintain backlog item':kind==='feedback'?'Capture review feedback':'Capture a backlog item',intro:'Keep it lightweight. A title is enough; add detail when it becomes useful.',
        body:`${field('Title','title',item?.title??'','text',true)}${textarea('Description / acceptance notes','description',item?.description??(kind==='feedback'?`Review follow-up from iteration ${iteration?.index}: ${iteration?.goal}`:''))}<div class="form-grid">${select('Backlog','backlogId',options(state.backlogs,backlog))}${field('Type (your own vocabulary)','itemType',item?.type??(kind==='feedback'?'Feedback':'Item'))}</div><div class="form-grid">${select('Priority','priority',options([{id:'high',title:'High'},{id:'medium',title:'Medium'},{id:'low',title:'Low'}],item?.priority??'medium'))}${select('Owner','ownerId',personOptions(state,item?.ownerId??null))}</div><label class="field" for="f-estimate"><span>Estimated hours (optional)</span><input id="f-estimate" name="estimate" type="number" min="0" max="10000" step="0.25" value="${item?.estimate??''}" placeholder="Not estimated"></label>${item?`<div class="notice-box">${statusBadge(item.status)} Planning snapshots and old increments are preserved when you edit this item.</div>${button(item.archived?'Restore item':'Archive item',item.archived?'restore-item':'archive-item',item.id,'quiet')}`:''}`,submit:item?'Save item':'Add item'};
    }
    case 'work': {
      const work = iteration?.work.find(value=>value.itemId===id);
      if (!work||!iteration) throw new Error('Work item is no longer available.');
      if (iteration.stage==='active') return {title:'Update the work',intro:'Keep progress, blockers, and delivery distinct.',body:workForm(state,iteration,work,false),submit:'',ownForm:true};
      return {title:work.title,intro:iteration.stage==='closed'?'Frozen at review. This is a historical record.':'Selected during planning. Progress can be updated after the iteration starts.',body:`${statusBadge(work.status)}<p>${esc(state.items.find(item=>item.id===id)?.description)}</p><p><strong>Planned owner:</strong> ${esc(owner(state,work.ownerId))}</p><p><strong>Planned estimate:</strong> ${work.estimate??'Not estimated'}${work.estimate===null?'':'h'}</p><h3>Progress note</h3><p class="pre-wrap">${esc(work.note)||'None yet.'}</p><h3>Changelog entry</h3><p>${esc(work.releaseNote)||'Not delivered.'}</p>`,submit:''};
    }
    case 'backlog': return {title:id?'Rename backlog':'Create a backlog',intro:'A backlog can contain any kind of work.',body:field('Backlog title','title',state.backlogs.find(value=>value.id===id)?.title??'','text',true),submit:id?'Rename backlog':'Create backlog'};
    case 'person': {
      const person = state.resources.find(value=>value.id===id);
      return {title:person?'Edit person':'Add a person',intro:'People are reusable resources. Available hours are set separately for each iteration.',body:field('Name','name',person?.name??'','text',true)+field('Role / contribution','role',person?.role??''),submit:person?'Save person':'Add person'};
    }
    case 'allocate': return {title:'Allocate capacity',intro:'Use realistic availability for this iteration, not contracted working time.',body:select('Person','resourceId',options(state.resources.map(person=>({id:person.id,title:person.name})),id))+`<label class="field" for="f-hours"><span>Available hours in this iteration</span><input id="f-hours" name="hours" type="number" min="0" max="10000" step="0.25" required value="${iteration?.members.find(member=>member.resourceId===id)?.hours??0}"></label>`,submit:'Save capacity'};
    case 'reference': return {title:'Add an iteration reference',intro:'Links are only opened when you explicitly click them. They are not fetched or embedded.',body:field('Reference title','title','','text',true)+field('HTTP(S) URL','url','','url',true),submit:'Add reference'};
    case 'confidence': return {title:'Assess goal confidence',intro:'This is your team’s judgment about reaching the goal, not a prediction based on the number of tasks.',body:select('Team assessment','confidence',options([{id:'unknown',title:'Not assessed'},{id:'on-track',title:'On track'},{id:'at-risk',title:'At risk'},{id:'off-track',title:'Off track'}],iteration?.confidence??'unknown')),submit:'Save assessment'};
    case 'scope-add': return {title:'Add to the iteration',intro:detail,body:iteration?.stage==='active'?field('Why is this scope being added?','reason','','text',true)+'<p class="muted">The original planning agreement will not change.</p>':'<p>Selected items will become part of this draft plan.</p>',submit:'Add selected items'};
    case 'scope-remove': return {title:'Remove from the iteration?',intro:iteration?.work.find(work=>work.itemId===id)?.title??'',body:'<p>The item stays in the product backlog. Its progress is not erased.</p>'+(iteration?.stage==='active'?field('Why is this scope being removed?','reason','','text',true):''),submit:'Remove from iteration'};
    case 'start': return {title:'Agree the plan & start?',intro:iteration?.goal??'',body:`<div class="notice-box">${iteration?.work.length??0} items will become the original planning agreement. The goal, dates, titles, and estimates are preserved. Later scope changes need a reason.</div><p>One active iteration per workspace. Any existing active iteration must be reviewed first.</p>`,submit:'Agree plan & start'};
    case 'finish-daily': return {title:'Close the daily conversation',intro:'Every current backlog item must be discussed before the daily can be finished.',body:textarea('What will the team focus on next?','summary',iteration?.daily.find(day=>day.date===state.clock)?.summary??''),submit:'Finish daily'};
    case 'close-review': {
      const stats = iteration?summary(iteration):null;
      return {title:'Record this increment?',intro:'The review becomes a frozen snapshot. It will not change when future work is edited.',body:`<div class="review-confirm"><strong>${stats?.done??0} delivered</strong><span>${(stats?.total??0)-(stats?.done??0)} not delivered</span></div><p>Unfinished work returns to the available backlog with its status preserved. Nothing is automatically carried forward or marked Done.</p><p>Next, choose one improvement in the retrospective. Closing is not publishing a release.</p>`,submit:'Freeze increment & close'};
    }
    case 'retro': return {title:'Add a retrospective thought',intro:'Be specific about the work or process. Keep the conversation blameless.',body:select('Column','category',options([{id:'keep',title:'Keep doing'},{id:'change',title:'Change something'},{id:'try',title:'Try next'}],id||'try'))+field('Thought or improvement','text','','text',true)+select('Owner (optional)','ownerId',personOptions(state,null)),submit:'Add thought'};
    case 'promote-retro': return {title:'Make an improvement actionable',intro:iteration?.retro.find(note=>note.id===id)?.text??'',body:select('Destination backlog','backlogId',options(state.backlogs,state.backlogs.find(backlog=>backlog.id==='improvements')?.id??state.backlogs[0].id))+'<p>The new item keeps its owner and links back to this retrospective. It is not automatically added to another iteration.</p>',submit:'Create backlog action'};
    case 'settings': return {title:'Prototype workspace',intro:'This is an offline interaction prototype with synthetic data, not your vault or team’s live backlog.',body:field('Product name','productName',state.productName,'text',true)+field('Simulation date','clock',state.clock,'date',true)+`<label class="inline-check"><input type="checkbox" name="remember" ${ui.remember?'checked':''}> Remember this workspace in this browser</label><p class="muted">Off by default. Storage may be unavailable for local files. JSON export is the portable backup.</p><div class="settings-actions">${button('Restore example workspace','reset-demo','','secondary')}${button('Start with an empty workspace','reset-empty','','secondary')}</div>`,submit:'Save workspace settings'};
    case 'import': return {title:'Replace the current workspace?',intro:detail,body:'<div class="notice-box">This replaces all in-memory backlogs, iterations, resources, and history. Export the current workspace first to keep a backup. Cancelling makes no changes.</div><p>The planner JSON format is separate from Companion project JSON.</p>',submit:'Replace workspace'};
    case 'confirm': return {title:'Confirm this change',intro:detail,body:'<p>This action changes only this prototype workspace.</p>',submit:'Confirm'};
    case 'help': return {title:'From an open backlog to a useful increment',intro:'A simple loop for building and improving a product together.',body:`<div class="help-steps"><h3>1. Capture freely</h3><p>Use any backlog vocabulary. A title is enough. Prioritize and refine as you learn.</p><h3>2. Plan a focused iteration</h3><p>Set a goal, choose dates, allocate available people and add items. Agree the plan to preserve the baseline.</p><h3>3. Walk the work daily</h3><p>Discuss blockers first, then every iteration item. Update progress and the next useful step. Done needs a quality check and a changelog entry.</p><h3>4. Review the increment</h3><p>Show what became usable. Assess the goal, capture feedback, and freeze a truthful review. Unfinished work returns to the backlog.</p><h3>5. Improve the way you work</h3><p>Keep what helped. Pick a change. Turn it into a backlog action for a future planning decision.</p></div><div class="notice-box">One increment record per iteration is this concept’s reporting model. It is not a claim that Scrum allows only one technical increment. Gauges show Done-item counts, not value or individual productivity.</div><p><strong>Prototype boundaries:</strong> browser memory or opt-in local storage; no Obsidian writes, shared editing, calendar invitations, or production integration. The current fallback is TypeScript + native browser UI; Vue/Pinia/Nuxt qualification is pending.</p>`,submit:''};
    default: throw new Error('Unknown dialog.');
  }
}
