import { assignment, nameOf, summary, type Workspace, type Iteration } from './model.ts';
import { esc, icon, button, iconButton, badge, statusBadge, heading, empty, formatDate, avatar, options, type ViewState } from './ui.ts';

export function backlogView(state: Workspace, ui: ViewState): string {
  const term = ui.search.toLowerCase();
  const items = state.items.filter(item => (ui.showArchived || !item.archived) &&
    (ui.backlogFilter==='all'||item.backlogId===ui.backlogFilter) &&
    (!term||`${item.title} ${item.description} ${item.type}`.toLowerCase().includes(term)) &&
    (ui.statusFilter==='all'||(ui.statusFilter==='unassigned'?!assignment(state,item.id)&&item.status!=='done':item.status===ui.statusFilter)));
  const start = ui.page*30; const visible = items.slice(start,start+30);
  const backlogs = [{id:'all',title:'All backlogs'},...state.backlogs];
  const open = state.iterations.filter(iteration=>iteration.stage!=='closed');
  const selection = ui.selectedItems.size;
  return heading('Product backlog','A home for every next idea.','Features, bugs, research, chores, or anything else. Only a title is required.',
    button('New backlog','new-backlog','','secondary','plus')+button('New item','new-item','','primary','plus'))+
    `<section class="card backlog-card"><div class="filter-bar"><label class="search-field" for="backlog-search">${icon('search')}<input id="backlog-search" type="search" placeholder="Find an item…" aria-label="Search backlog" value="${esc(ui.search)}"></label>
      <select id="backlog-filter" aria-label="Choose backlog">${options(backlogs,ui.backlogFilter)}</select>
      <select id="status-filter" aria-label="Filter item status">${options([{id:'all',title:'Any status'},{id:'unassigned',title:'Available to plan'},{id:'backlog',title:'Backlog'},{id:'ready',title:'Ready'},{id:'doing',title:'In progress'},{id:'blocked',title:'Blocked'},{id:'done',title:'Done'}],ui.statusFilter)}</select>
      <label class="inline-check"><input id="show-archived" type="checkbox" ${ui.showArchived?'checked':''}> Include archived</label>
      ${ui.backlogFilter!=='all'?iconButton('Rename this backlog','rename-backlog',ui.backlogFilter,'edit'):''}</div>
      <div class="table-scroll"><table class="backlog-table"><thead><tr><th><span class="sr-only">Select</span></th><th>BACKLOG ITEM</th><th>PRIORITY</th><th>ESTIMATE</th><th>OWNER</th><th>PLANNING</th><th>ORDER</th></tr></thead><tbody>
      ${visible.map(item=>{
        const assigned = assignment(state,item.id); const selectable = !assigned&&!item.archived&&item.status!=='done';
        return `<tr><td><input type="checkbox" data-select-item="${esc(item.id)}" aria-label="Select ${esc(item.title)}" ${ui.selectedItems.has(item.id)?'checked':''} ${selectable?'':'disabled'}></td><td><button class="item-title text-button" data-action="edit-item" data-id="${esc(item.id)}">${esc(item.title)}</button><div class="row-meta">${badge(item.type)}<span>${esc(state.backlogs.find(backlog=>backlog.id===item.backlogId)?.title)}</span>${item.archived?badge('Archived'):''}</div></td>
          <td><span class="priority ${item.priority}">${item.priority==='high'?'↑':item.priority==='low'?'↓':'–'} ${item.priority}</span></td><td class="tabular">${item.estimate===null?'Not estimated':`${item.estimate}h`}</td><td>${avatar(state,item.ownerId)}</td>
          <td>${assigned?`<button class="iteration-pill" data-action="select-iteration" data-id="${esc(assigned.id)}">#${String(assigned.index).padStart(2,'0')} · ${esc(assigned.stage)}</button>`:statusBadge(item.status)}</td>
          <td class="order-buttons"><button class="icon-btn" data-action="move-up" data-id="${esc(item.id)}" aria-label="Move ${esc(item.title)} up">↑</button><button class="icon-btn" data-action="move-down" data-id="${esc(item.id)}" aria-label="Move ${esc(item.title)} down">↓</button></td></tr>`;
      }).join('')||'<tr><td colspan="7"><div class="empty-inline"><h3>No matching items</h3><p>Try another filter or capture your first idea below.</p></div></td></tr>'}</tbody></table></div>
      <form id="quick-add-form" class="quick-add">${icon('plus',18)}<label class="sr-only" for="quick-title">Quick-add item title</label><input id="quick-title" name="title" required maxlength="180" placeholder="Capture an idea… just a title, then Enter"><button class="btn quiet" type="submit">Add item</button></form>
      <div class="table-footer"><span>${items.length} matching items · order is maintained within each backlog</span><div>${button('Previous','previous-page','','quiet')}${badge(`${Math.min(ui.page+1,Math.max(1,Math.ceil(items.length/30)))} / ${Math.max(1,Math.ceil(items.length/30))}`)}${button('Next','next-page',String(items.length),'quiet')}</div></div></section>
      ${selection?`<div class="selection-bar"><strong>${selection} selected</strong>${button('Clear selection','clear-selection','','quiet')}
        ${open.length?`<label class="sr-only" for="bulk-iteration">Destination iteration</label><select id="bulk-iteration">${options(open.map(iteration=>({id:iteration.id,title:`#${iteration.index} · ${iteration.goal}`})),ui.selectedId)}</select>${button('Add to iteration','add-selected','','primary','arrow')}`:button('Create an iteration first','new-iteration','','primary','plus')}</div>`:''}
      <p class="page-note">A backlog stays flexible. Planning creates a snapshot of the title and estimate; later backlog edits do not rewrite the agreement.</p>`;
}
export function planningView(state: Workspace, ui: ViewState, iteration?: Iteration): string {
  if (!iteration) return heading('Iteration planning','Choose one useful outcome.','Start with a goal, not a full task list.')+empty('No iteration yet','The index starts at 0 and increases automatically. Dates are suggested, not forced.',button('Create iteration','new-iteration','','primary','plus'));
  const stats = summary(iteration); const editable = iteration.stage!=='closed';
  const pool = state.items.filter(item=>!item.archived&&item.status!=='done'&&!assignment(state,item.id));
  const actions = iteration.stage==='planning'?button('Edit goal & dates','edit-iteration',iteration.id)+button('Agree plan & start','start-iteration',iteration.id,'primary','check'):button('Go to daily','navigate','daily','primary','arrow');
  return heading(`Iteration ${String(iteration.index).padStart(2,'0')} · ${iteration.stage}`,'Make the next increment intentional.','Decide why this iteration matters, what fits, and how the team will make progress.',actions)+
    `<section class="card planning-goal"><div><div class="eyebrow">THE GOAL</div><h2>${esc(iteration.goal)}</h2><p>${esc(iteration.description)||'Add context about the outcome this iteration should create.'}</p></div><div class="planning-dates"><strong>${formatDate(iteration.start)} – ${formatDate(iteration.end)}</strong><span>${badge(iteration.stage==='planning'?'Draft plan':'Agreement preserved',iteration.stage==='planning'?'neutral':'done')}</span><small>${esc(nameOf(iteration))}</small></div></section>
    <div class="planning-layout"><section class="card planning-pool"><div class="card-heading"><div><h2>Available backlog</h2><p>${pool.length} items not committed elsewhere.</p></div>${button('New item','new-item','','quiet','plus')}</div><div class="pool-list">${pool.slice(0,60).map(item=>`<article class="pool-item"><div>${badge(item.type)}<h3><button class="text-button" data-action="edit-item" data-id="${esc(item.id)}">${esc(item.title)}</button></h3><div class="row-meta"><span>${item.estimate===null?'No estimate':`${item.estimate}h estimated`}</span>${avatar(state,item.ownerId)}</div></div>${editable?iconButton('Add '+item.title+' to iteration','add-plan-item',item.id,'plus'):''}</article>`).join('')||'<div class="empty-inline"><p>No available items. Capture the next useful step in your backlog.</p></div>'}</div>${pool.length>60?button('Browse the full backlog','navigate','backlog','quiet','arrow'):''}</section>
    <section class="card plan-selection"><div class="card-heading"><div><h2>The iteration backlog ${badge(String(stats.total))}</h2><p>${stats.baseline} originally agreed · ${stats.estimate}h estimated${stats.unestimated?` · ${stats.unestimated} unestimated`:''}</p></div>${badge(iteration.stage==='planning'?'Build your plan':'Scope is explicit','active')}</div>
      <div class="planned-list">${iteration.work.map((work,index)=>`<article class="planned-item"><span class="number-circle">${index+1}</span><div><button class="text-button" data-action="work" data-id="${esc(work.itemId)}">${esc(work.title)}</button><div class="row-meta">${statusBadge(work.status)}<span>${work.estimate===null?'Not estimated':`${work.estimate}h`}</span>${avatar(state,work.ownerId)}</div></div>${editable&&work.status!=='done'?iconButton('Remove '+work.title+' from iteration','remove-work',work.itemId,'close'):''}</article>`).join('')||'<div class="empty-inline"><h3>Leave room for a focused plan.</h3><p>Add a few items from the backlog on the left.</p></div>'}</div>
      <div class="planning-summary"><div><span>Estimated workload</span><strong>${stats.estimate}h ${stats.unestimated?`+ ${stats.unestimated} unestimated`:''}</strong></div><div><span>Available team capacity</span><strong>${stats.capacity}h</strong></div>${stats.estimate>stats.capacity?'<p class="warning-text">The estimate exceeds capacity. Discuss scope; this is a warning, not a productivity score.</p>':'<p>Estimates and available hours are planning aids, not promised output.</p>'}${button('Manage people & resources','navigate','resources','secondary')}</div></section></div>
    ${iteration.baseline?`<section class="card scope-card"><div class="card-heading"><div><h2>Agreement & scope changes</h2><p>The original agreement is preserved; additions and removals are explained.</p></div>${badge(`${iteration.scopeChanges.length} changes`)}</div><details><summary>View original agreement (${iteration.baseline.length} items)</summary><ul>${iteration.baseline.map(work=>`<li>${esc(work.title)} — ${work.estimate===null?'not estimated':`${work.estimate}h`}</li>`).join('')}</ul></details>${iteration.scopeChanges.map(change=>`<div class="scope-row">${badge(change.action,change.action==='added'?'doing':'neutral')}<span>${esc(state.items.find(item=>item.id===change.itemId)?.title)}</span><p>${esc(change.reason)}</p><time>${formatDate(change.date)}</time></div>`).join('')||'<p class="muted padded">No scope changes since planning.</p>'}</section>`:''}`;
}
export function resourcesView(state: Workspace, iteration?: Iteration): string {
  return heading('People & supporting resources','Give the plan room to succeed.','Keep people, available hours, and reference material close to the work.',button('Add person','new-person','','primary','plus'))+
    `<div class="resource-layout"><section class="card"><div class="card-heading"><div><h2>People directory</h2><p>People can contribute to different iterations.</p></div></div>${state.resources.map(person=>`<div class="resource-row">${avatar(state,person.id,true)}<span class="muted">${esc(person.role)||'Role not specified'}</span>${iconButton('Edit '+person.name,'edit-person',person.id,'edit')}${iteration&&iteration.stage!=='closed'?button('Allocate','allocate',person.id,'quiet'):''}</div>`).join('')||'<p class="padded muted">Add a person to start a capacity conversation.</p>'}</section>
    <section class="card"><div class="card-heading"><div><h2>This iteration’s capacity</h2><p>${iteration?esc(iteration.goal):'Create an iteration to allocate people.'}</p></div></div>${iteration?.members.map(member=>`<div class="resource-row">${avatar(state,member.resourceId,true)}<strong class="hours">${member.hours}h</strong>${iteration.stage!=='closed'?iconButton('Edit available hours','allocate',member.resourceId,'edit')+iconButton('Remove capacity allocation','remove-allocation',member.resourceId,'close'):''}</div>`).join('')||'<p class="padded muted">No capacity allocated yet. Allocation is optional.</p>'}${iteration?`<div class="total-row"><span>Available team hours</span><strong>${summary(iteration).capacity}h</strong></div>`:''}</section></div>
    <section class="card references"><div class="card-heading"><div><h2>Iteration references</h2><p>Link the brief, Definition of Done, designs, or other supporting material.</p></div>${iteration&&iteration.stage!=='closed'?button('Add reference','new-reference','','secondary','plus'):''}</div>${iteration?.references.map(ref=>`<div class="reference-row">${icon('link',20)}<a href="${esc(ref.url)}" target="_blank" rel="noopener noreferrer">${esc(ref.title)}<small>${esc(ref.url)} · opens an external site</small></a>${iteration.stage!=='closed'?iconButton('Remove '+ref.title,'remove-reference',ref.id,'close'):''}</div>`).join('')||'<p class="muted padded">No references added. Links are never fetched automatically.</p>'}</section>`;
}
export function historyView(state: Workspace): string {
  return heading('Iteration history','Small increments. A growing product.','Every reviewed increment keeps its own changelog and unfinished-work snapshot.',button('New iteration','new-iteration','','primary','plus'))+
    `<div class="history-grid">${[...state.iterations].reverse().map(iteration=>{const stats=summary(iteration);return `<article class="card history-card"><div class="card-heading"><span class="eyebrow">ITERATION ${String(iteration.index).padStart(2,'0')}</span>${badge(iteration.stage,iteration.stage==='closed'?'done':'active')}</div><h2>${esc(iteration.goal)}</h2><p>${formatDate(iteration.start)} – ${formatDate(iteration.end)}</p><div class="history-stats"><strong>${stats.done}<span> / ${stats.total} delivered</span></strong>${badge(iteration.increment.goalOutcome)}</div><div class="thin-track"><span style="width:${stats.percent}%"></span></div>${button('Open iteration','select-iteration',iteration.id,'secondary','arrow')}</article>`;}).join('')||empty('Your history starts with iteration 0','An index is never reused, and there is no ten-iteration limit.')}</div>`;
}
