/**
 * Help metadata of the increment, pr and issue commands: usage lines, examples, option documentation and
 * per-command overrides. Spread into help-text.ts so the terminal help and the generated manual share it.
 */
import type { OptionHelp } from './help-text.ts';
import { incrementCommands } from './increment-catalog.ts';

const app = 'node bin/app';
const plan = '[--dry-run | --yes | --apply <sha256>] [--json]';
const branchFlags = '[--branch | --no-branch] [--switch] [--fetch]';
export const incrementGroup = { id: 'increments', title: 'Increments, issues and pull requests', commands: incrementCommands.map(command => command.id) };
export const incrementUsage: Record<string, string> = {
  'increment new': `${app} increment new <id> --title <title> [--owner <name>] [--size S|M|L] [--e2e none|optional|required] [--from <path>] [--input <md|->] [--issue | --no-issue] ${branchFlags} ${plan}`,
  'increment list': `${app} increment list [--status <status>] [--json]`,
  'increment show': `${app} increment show <id> [--json]`,
  'increment edit': `${app} increment edit <id> [--title <title>] [--owner <name>] [--size S|M|L] [--e2e <decision>] [--section <name> --input <md|->] ${plan}`,
  'increment status': `${app} increment status <id> <status> ${plan}`,
  'increment scope add': `${app} increment scope add <id> <text> ${plan}`,
  'increment out-of-scope add': `${app} increment out-of-scope add <id> <text> ${plan}`,
  'increment ac add': `${app} increment ac add <id> <text> ${plan}`,
  'increment ac set': `${app} increment ac set <id> <AC-n> [--status open|done] [--text <text>] [--evidence <path,...>] ${plan}`,
  'increment ref add': `${app} increment ref add <id> <path|[[wikilink]]> ${plan}`,
  'increment attach': `${app} increment attach <id> <pr> ${plan}`,
  'increment validate': `${app} increment validate [id] [--json]`,
  'increment check': `${app} increment check <id> [--gate ready|done] [--base <ref>] [--json]`,
  'increment complete': `${app} increment complete <id> [--base <ref>] ${plan}`,
  'pr new': `${app} pr new <increment> --title <title> [--id <id>] [--summary <text>] [--head <branch>] [--base <branch>] [--delivers AC-1,AC-2] [--input <md|->] ${branchFlags} ${plan}`,
  'pr list': `${app} pr list [--increment <id>] [--status <status>] [--json]`,
  'pr show': `${app} pr show <pr> [--json]`,
  'pr edit': `${app} pr edit <pr> [--title <title>] [--summary <text>] [--head <branch>] [--base <branch>] [--section <name> --input <md|->] ${plan}`,
  'pr status': `${app} pr status <pr> New|Closed ${plan}`,
  'pr task add': `${app} pr task add <pr> <text> ${plan}`,
  'pr task set': `${app} pr task set <pr> <T-n> [--status open|done] [--text <text>] ${plan}`,
  'pr doc add': `${app} pr doc add <pr> <path|[[wikilink]]> [--label <label>] ${plan}`,
  'pr scope add': `${app} pr scope add <pr> <text> ${plan}`,
  'pr out-of-scope add': `${app} pr out-of-scope add <pr> <text> ${plan}`,
  'pr notes': `${app} pr notes <pr> --input <md|-> [--replace] ${plan}`,
  'pr amend': `${app} pr amend <pr> [text] [--input <md|->] ${plan}`,
  'pr issue add': `${app} pr issue add <pr> <issue> ${plan}`,
  'pr validate': `${app} pr validate [pr] [--json]`,
  'pr publish': `${app} pr publish <pr> [--platform github|azure-devops] [--no-push] [--dry-run | --yes | --apply <sha256>] [--json]`,
  'pr sync': `${app} pr sync <pr> [--prefer local|remote] [--resolutions <json|file>] [--dry-run | --yes | --apply <sha256>] [--json]`,
  'issue new': `${app} issue new <increment> [--id <id>] [--title <title>] [--summary <text>] [--input <md|->] ${plan}`,
  'issue list': `${app} issue list [--increment <id>] [--status <status>] [--json]`,
  'issue show': `${app} issue show <issue> [--json]`,
  'issue edit': `${app} issue edit <issue> [--title <title>] [--summary <text>] [--section <name> --input <md|->] ${plan}`,
  'issue status': `${app} issue status <issue> <status> ${plan}`,
  'issue ac add': `${app} issue ac add <issue> <text|AC-n> ${plan}`,
  'issue ac set': `${app} issue ac set <issue> <AC-n|IC-n> [--status open|done] [--text <text>] ${plan}`,
};
export const incrementExamples: Record<string, string[]> = {
  'increment new': [`${app} increment new delivery-pipeline --title "Delivery pipeline" --owner Luis --dry-run`, `${app} increment new delivery-pipeline --title "Delivery pipeline" --no-branch --yes`],
  'increment list': [`${app} increment list`, `${app} increment list --status Ready --json`],
  'increment show': [`${app} increment show delivery-pipeline --json`],
  'increment edit': [`${app} increment edit delivery-pipeline --size L --dry-run`, `${app} increment edit delivery-pipeline --section Summary --input summary.md --yes`],
  'increment status': [`${app} increment status delivery-pipeline Ready --dry-run`],
  'increment scope add': [`${app} increment scope add delivery-pipeline "The publish command" --yes`],
  'increment out-of-scope add': [`${app} increment out-of-scope add delivery-pipeline "Merging pull requests" --yes`],
  'increment ac add': [`${app} increment ac add delivery-pipeline "pr publish previews before writing" --dry-run`],
  'increment ac set': [`${app} increment ac set delivery-pipeline AC-1 --status done --yes`],
  'increment ref add': [`${app} increment ref add delivery-pipeline "[[docs/prds/delivery]]" --yes`],
  'increment attach': [`${app} increment attach other-increment delivery-pipeline-2 --dry-run`],
  'increment validate': [`${app} increment validate`, `${app} increment validate delivery-pipeline --json`],
  'increment check': [`${app} increment check delivery-pipeline --gate ready`, `${app} increment check delivery-pipeline --gate done --base origin/main --json`],
  'increment complete': [`${app} increment complete delivery-pipeline --dry-run`],
  'pr new': [`${app} pr new delivery-pipeline --title "Hosting set command" --dry-run`, `${app} pr new delivery-pipeline --title "Hosting set command" --delivers AC-1 --switch --yes`],
  'pr list': [`${app} pr list --increment delivery-pipeline`],
  'pr show': [`${app} pr show delivery-pipeline-1 --json`],
  'pr edit': [`${app} pr edit delivery-pipeline-1 --summary "Adds hosting set." --dry-run`],
  'pr status': [`${app} pr status delivery-pipeline-1 Closed --dry-run`],
  'pr task add': [`${app} pr task add delivery-pipeline-1 "Add the planner" --yes`],
  'pr task set': [`${app} pr task set delivery-pipeline-1 T-1 --status done --yes`],
  'pr doc add': [`${app} pr doc add delivery-pipeline-1 docs/development/HOSTING-PLATFORMS.md --label "Hosting platforms" --yes`],
  'pr scope add': [`${app} pr scope add delivery-pipeline-1 "The planner" --yes`],
  'pr out-of-scope add': [`${app} pr out-of-scope add delivery-pipeline-1 "Azure support" --yes`],
  'pr notes': [`${app} pr notes delivery-pipeline-1 --input notes.md --dry-run`],
  'pr amend': [`${app} pr amend delivery-pipeline-1 "Split the docs task." --dry-run`],
  'pr issue add': [`${app} pr issue add delivery-pipeline-1 delivery-pipeline --yes`],
  'pr validate': [`${app} pr validate`, `${app} pr validate delivery-pipeline-1 --json`],
  'pr publish': [`${app} pr publish delivery-pipeline-1 --dry-run`, `${app} pr publish delivery-pipeline-1 --apply <sha256>`],
  'pr sync': [`${app} pr sync delivery-pipeline-1`, `${app} pr sync delivery-pipeline-1 --prefer remote --yes`],
  'issue new': [`${app} issue new delivery-pipeline --title "Publish command" --dry-run`],
  'issue list': [`${app} issue list --increment delivery-pipeline`],
  'issue show': [`${app} issue show delivery-pipeline --json`],
  'issue edit': [`${app} issue edit delivery-pipeline --summary "The publish command." --yes`],
  'issue status': [`${app} issue status delivery-pipeline Ready --yes`],
  'issue ac add': [`${app} issue ac add delivery-pipeline AC-1 --yes`, `${app} issue ac add delivery-pipeline "Errors name the next step" --yes`],
  'issue ac set': [`${app} issue ac set delivery-pipeline IC-1 --status done --yes`],
};
export const incrementOptionHelp: Record<string, OptionHelp> = {
  title: { description: 'Single-line title of at most 120 characters.' },
  owner: { description: 'Owner of the increment (a name or handle).' },
  size: { description: 'Increment size; sets the acceptance-criteria and affected-area budgets.', values: ['S', 'M', 'L'], default: 'M' },
  e2e: { description: 'End-to-end test decision of the increment.', values: ['none', 'optional', 'required'], default: 'optional' },
  section: { description: 'Section whose body --input replaces, for example Summary, Outcome or In scope.' },
  summary: { description: 'Summary text (Markdown, one paragraph).' },
  head: { description: 'Head branch of the pull request.', default: 'increment/<id> for the kick-off, pr/<increment>/<pr> for change pull requests' },
  increment: { description: 'Only list documents of this increment.' },
  delivers: { description: 'Comma-separated acceptance criteria of the increment this pull request delivers, for example AC-1,AC-3.' },
  gate: { description: 'Which gate to run.', values: ['ready', 'done'], default: 'ready' },
  text: { description: 'New single-line text of the criterion or task.' },
  evidence: { description: 'Comma-separated evidence paths of the criterion; defaults to its acceptance test stub.' },
  platform: { description: 'Hosting platform to publish to.', values: ['github', 'azure-devops'], default: 'the binding, tooling.hosting, then the origin remote' },
  prefer: { description: 'Resolve every sync conflict with this side.', values: ['local', 'remote'] },
  issue: { description: 'Also create the corresponding Issue document (the default).' },
  'no-issue': { description: 'Do not create an Issue document.' },
  branch: { description: 'Create the branch (the default when git is available and the branch does not exist).' },
  'no-branch': { description: 'Do not create a branch.' },
  switch: { description: 'Check the new branch out after creating it.' },
  fetch: { description: 'Fetch the start branch from origin before branching; nothing is fetched otherwise.' },
  'no-push': { description: 'Refuse instead of pushing a head branch that is not on the remote (PR_HEAD_NOT_PUSHED).' },
};
type OptionOverride = [(id: string, name: string) => boolean, (doc: OptionHelp) => void];
const family = (prefix: string, ...names: string[]) => (id: string, name: string) => id.startsWith(prefix) && names.includes(name);
const one = (command: string, name: string) => (id: string, option: string) => id === command && option === name;
const set = (fields: OptionHelp) => (doc: OptionHelp) => { delete doc.values; delete doc.default; Object.assign(doc, fields); };
export const incrementOptionOverrides: OptionOverride[] = [
  [family('increment ', 'status'), set({ description: 'Only list increments with this status.', values: ['New', 'Refining', 'Ready', 'In progress', 'Done', 'Cancelled'] })],
  [family('pr ', 'status'), set({ description: 'Only list pull requests with this status.', values: ['New', 'Draft', 'Ready', 'Merged', 'Closed'] })],
  [family('issue ', 'status'), set({ description: 'Only list issues with this status.', values: ['New', 'Ready', 'In progress', 'Done', 'Cancelled'] })],
  [(id, name) => id.endsWith(' ac set') || id === 'pr task set' ? name === 'status' : false, set({ description: 'Tick (done) or reopen (open) the item.', values: ['open', 'done'] })],
  [family('increment ', 'base'), set({ description: 'Ref the gate diffs against (merge base with HEAD).', default: 'origin/main when it exists, else main' })],
  [family('pr ', 'base'), set({ description: 'Base branch of the pull request; a change pull request normally targets the increment branch.', default: 'the increment branch (change) or main (kick-off)' })],
  [(id, name) => /^(?:increment|pr|issue) /.test(id) && name === 'input', set({ description: 'Markdown fragment with ## sections (use - for stdin).' })],
  [one('increment new', 'from'), set({ description: 'Source document (PRD, PBI or task) recorded in the increment refs.' })],
  [one('pr new', 'id'), set({ description: 'Pull-request id (slug).', default: '<increment>-<n>' })],
  [one('issue new', 'id'), set({ description: 'Issue id (slug).', default: 'the increment id, then <increment>-<n>' })],
  [one('pr doc add', 'label'), set({ description: 'Link text shown for the document.' })],
  [one('pr notes', 'replace'), set({ description: 'Replace the notes instead of appending.' })],
  [one('pr sync', 'resolutions'), set({ description: 'JSON object (inline or a file) mapping conflict keys to local or remote.' })],
];
