// Generated by the compiler from the project's surfaces; regenerating replaces this file. These checks are
// accessibility and layout evidence for the generated preview. They are not product acceptance, not a native
// Obsidian result and keep no screenshot baselines.
import { test, expect, type Page, type TestInfo } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

interface Surface { id: string; label: string }
const surfaces: Surface[] = [
  {"id":"node-1","label":"Workbench"},
  {"id":"node-3","label":"Project overview"},
  {"id":"node-5","label":"Project Starters"},
  {"id":"node-7","label":"Product requirements"},
  {"id":"node-9","label":"Storymaps overview"},
  {"id":"node-11","label":"Storymap editor"},
  {"id":"node-13","label":"Sitemap & views"},
  {"id":"node-15","label":"Pages overview"},
  {"id":"node-17","label":"Page editor"},
  {"id":"node-19","label":"Component editor"},
  {"id":"node-21","label":"Entity relationships"},
  {"id":"node-23","label":"Data Sources"},
  {"id":"node-25","label":"Test Data"},
  {"id":"node-27","label":"Design System"},
  {"id":"node-29","label":"Component library"},
  {"id":"node-31","label":"Blueprints"},
  {"id":"node-33","label":"Action patterns"},
  {"id":"node-35","label":"Prepare project"},
  {"id":"node-37","label":"Generate a feature"},
  {"id":"node-39","label":"Development"},
  {"id":"node-41","label":"Quality & verification"},
  {"id":"node-43","label":"Shell capabilities"},
  {"id":"node-45","label":"Release readiness"},
  {"id":"node-47","label":"Runs & recovery"},
  {"id":"node-49","label":"Workbench preferences"},
];
const themes = ['light', 'dark'] as const;
type Theme = (typeof themes)[number];
type Violation = Awaited<ReturnType<AxeBuilder['analyze']>>['violations'][number];
const wcagTags = ['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa'];
const primaryControls = 'button, a[href], [role="button"], input:not([type="hidden"]):not([type="radio"]), select, textarea';

/** Opens a surface by its preview address and returns the page errors collected since. */
async function openSurface(page: Page, surface: Surface): Promise<string[]> {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/#surface=' + encodeURIComponent(surface.id));
  await expect(page.locator('html')).toHaveAttribute('data-prototype-ready', 'true');
  await expect(page.locator('#clickdummy-surface')).toHaveValue(surface.id);
  return errors;
}
/** Switches the host theme class and proves the page really restyled: a dark theme needs a dark background. */
async function applyTheme(page: Page, theme: Theme): Promise<void> {
  await page.evaluate((next: Theme) => {
    document.body.classList.toggle('theme-dark', next === 'dark');
    document.body.classList.toggle('theme-light', next === 'light');
  }, theme);
  await expect.poll(() => page.evaluate(() => {
    const [red = 0, green = 0, blue = 0] = (getComputedStyle(document.body).backgroundColor.match(/\d+(\.\d+)?/g) ?? []).map(Number);
    return (red * 299 + green * 587 + blue * 114) / 1000 < 128 ? 'dark' : 'light';
  }), { message: 'the ' + theme + ' theme is applied to the page' }).toBe(theme);
}
function readable(violation: Violation): string {
  const nodes = violation.nodes.slice(0, 5).map(node => '    ' + node.target.join(' ') + '\n      ' + (node.failureSummary ?? '').replace(/\n\s*/g, '\n      '));
  const head = (violation.impact ?? 'unknown') + ' ' + violation.id + ': ' + violation.help + ' (' + violation.nodes.length + ' element(s)) ' + violation.helpUrl;
  return [head, ...nodes].join('\n');
}
/** Narrow, documented exceptions for defects inside a dependency that this project cannot fix. Each one that applies is
 * recorded as a test annotation, never dropped silently. Add none for the project's own markup. */
const upstreamExceptions = [
  { rule: 'aria-input-field-name', html: /data-slot="content"[^>]*role="listbox"|role="listbox"[^>]*data-slot="content"/,
    reason: 'Nuxt UI CommandPalette renders its listbox without an accessible name and has no prop to name it.' },
];
function withoutUpstreamExceptions(violations: Violation[], testInfo: TestInfo): Violation[] {
  return violations.flatMap(violation => {
    const known = upstreamExceptions.find(exception => exception.rule === violation.id);
    const nodes = violation.nodes.filter(node => !known?.html.test(node.html));
    if (known && nodes.length < violation.nodes.length) testInfo.annotations.push({ type: 'known-upstream-issue', description: violation.id + ': ' + known.reason });
    return nodes.length ? [{ ...violation, nodes }] : [];
  });
}
async function scan(page: Page, testInfo: TestInfo, name: string): Promise<void> {
  const analysis = await new AxeBuilder({ page }).withTags(wcagTags).analyze();
  const violations = withoutUpstreamExceptions(analysis.violations, testInfo);
  if (violations.length) await testInfo.attach('axe-' + name + '.json', { body: JSON.stringify(violations, null, 2), contentType: 'application/json' });
  expect(violations.map(readable), 'WCAG 2.1 A/AA violations (' + name + ')').toEqual([]);
}
/** Tags the visible, enabled primary controls of the workbench in document order and returns their descriptions.
 * Tabs, options and menu items use one tab stop with arrow keys and hidden form mirrors are not user controls, so they are left out. */
function tagPrimaryControls(page: Page): Promise<string[]> {
  return page.evaluate((selector: string) => {
    const root = document.querySelector('.generated-workbench');
    const controls = [...(root?.querySelectorAll(selector) ?? [])].filter(element => {
      const box = element.getBoundingClientRect();
      return box.width > 0 && box.height > 0 && !element.matches(':disabled, [aria-disabled="true"], [role="tab"], [role="option"], [role="menuitem"]')
        && !element.closest('[inert], [hidden], [aria-hidden="true"]');
    });
    controls.forEach((element, index) => element.setAttribute('data-ui-quality-index', String(index)));
    return controls.map(element => element.tagName.toLowerCase() + ' ' + (element.getAttribute('aria-label') ?? element.textContent ?? '').trim().slice(0, 40));
  }, primaryControls);
}
/** Presses Tab once; reports which tagged control has focus and whether its focus indicator is drawn. */
function focusStop(page: Page): Promise<{ index: number; visible: boolean }> {
  return page.evaluate(async () => {
    const element = document.activeElement;
    const index = Number(element?.getAttribute('data-ui-quality-index') ?? -1);
    if (!element || index < 0) return { index: -1, visible: false };
    for (let frame = 0; frame < 20; frame++) {
      const style = getComputedStyle(element);
      if ((style.outlineStyle !== 'none' && parseFloat(style.outlineWidth) > 0) || style.boxShadow !== 'none') return { index, visible: true };
      await new Promise(resolve => requestAnimationFrame(resolve));
    }
    return { index, visible: false };
  });
}

for (const surface of surfaces) {
  const name = '[' + surface.id + '] ' + surface.label;
  for (const theme of themes) {
    test(name + ': axe WCAG 2.1 A/AA in the ' + theme + ' theme', async ({ page }, testInfo) => {
      const errors = await openSurface(page, surface);
      await applyTheme(page, theme);
      await scan(page, testInfo, surface.id + '-' + theme);
      expect(errors).toEqual([]);
    });
  }
  test(name + ': 360px reflow without horizontal scrolling', async ({ page }) => {
    await page.setViewportSize({ width: 360, height: 800 });
    await openSurface(page, surface);
    const fit = await page.evaluate(() => {
      const scroller = document.scrollingElement ?? document.documentElement;
      const wide = [...document.body.querySelectorAll('*')].filter(element => element.getBoundingClientRect().right > scroller.clientWidth + 1).slice(0, 5)
        .map(element => element.tagName.toLowerCase() + (typeof element.className === 'string' && element.className.trim() ? '.' + element.className.trim().split(/\s+/).join('.') : ''));
      return { scrollWidth: scroller.scrollWidth, clientWidth: scroller.clientWidth, wide };
    });
    expect(fit.scrollWidth, 'scrollWidth must fit clientWidth; elements past the edge: ' + fit.wide.join(', ')).toBeLessThanOrEqual(fit.clientWidth);
  });
  test(name + ': primary actions are keyboard reachable with a visible focus indicator', async ({ page }) => {
    await openSurface(page, surface);
    const labels = await tagPrimaryControls(page);
    const reached = new Map<number, boolean>();
    for (let press = 0; press < labels.length + 60 && reached.size < labels.length; press++) {
      await page.keyboard.press('Tab');
      const stop = await focusStop(page);
      if (stop.index >= 0) reached.set(stop.index, stop.visible);
    }
    expect(labels.filter((_, index) => !reached.has(index)), 'primary controls the Tab key never reached').toEqual([]);
    expect(labels.filter((_, index) => reached.get(index) === false), 'focused controls without a visible focus indicator').toEqual([]);
  });
}
