/** Reviewed generated-output baseline for every Companion starter (project v6). `--check` (default) compares, `--write` records. */
import { readFile, readdir, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { compileProject, compilerVersion, loadTemplateSnapshot } from '../../src/cli/compiler/index.ts';

const GOLDEN_FILE = 'tests/fixtures/compiler/starter-golden.json';
const STARTERS = 'configs/starters';
const sha256 = value => createHash('sha256').update(value).digest('hex');
/** Product scope: what the compiler derives from the project. Shell files it carries along verbatim or rewrites
 * (including src/plugin/bootstrap/features.ts, the template registry plus generated registrations) are qualified by the
 * distribution, template and generator tests, so consumer or shell edits never require a new baseline. */
export function productPath(model, path) {
  return [model.sourceRoot + '/', model.testRoot + '/', 'harness/prototype/', 'design/'].some(prefix => path.startsWith(prefix)) ||
    ['src/plugin/main.ts', 'PROJECT-IMPLEMENTATION.md'].includes(path);
}
export function artifactDigests(model, artifacts) {
  return Object.fromEntries(artifacts.filter(file => productPath(model, file.path))
    .map(file => [file.path, sha256(file.encoding ? Buffer.from(file.content, file.encoding) : file.content)]));
}
/** Compiles every Companion starter definition with the live template into its reviewed digest case. */
export async function starterCases(root, template) {
  const snapshot = template ?? await loadTemplateSnapshot(root), cases = [];
  for (const name of (await readdir(join(root, STARTERS))).filter(file => file.endsWith('.json')).sort()) {
    const bytes = await readFile(join(root, STARTERS, name)), definition = JSON.parse(bytes.toString('utf8'));
    if (definition.generator?.kind !== 'companion') continue;
    const result = await compileProject({ source: JSON.stringify(definition.generator.document), sourceName: name, template: snapshot });
    if (result.status !== 'ok') throw new Error('GOLDEN_COMPILE: ' + name + ' ' + JSON.stringify(result.diagnostics));
    cases.push({ starter: definition.id, source: STARTERS + '/' + name, sourceSha256: sha256(bytes), files: artifactDigests(result.model, result.artifacts) });
  }
  return cases;
}
/** Files every case emits with identical bytes are recorded once, keeping the reviewed baseline small. */
export function goldenDocument(cases) {
  const [first, ...rest] = cases, shared = {};
  for (const [path, hash] of Object.entries(first?.files ?? {})) if (rest.every(item => item.files[path] === hash)) shared[path] = hash;
  return { schemaVersion: 1, compilerVersion, scope: 'Product-scope generated bytes of every Companion starter in ' + STARTERS + '; not build, test or native acceptance.',
    shared, starters: cases.map(item => ({ ...item, files: Object.fromEntries(Object.entries(item.files).filter(([path]) => !Object.hasOwn(shared, path))) })) };
}
function expanded(golden) {
  return new Map(golden.starters.map(item => [item.starter, { ...item, files: { ...golden.shared, ...item.files } }]));
}
/** Every difference is reported; an empty list is the only passing result. */
export function goldenDifferences(golden, cases) {
  const differences = [], expected = expanded(golden), actual = new Map(cases.map(item => [item.starter, item]));
  if (golden.schemaVersion !== 1) differences.push('baseline: unsupported schemaVersion');
  if (golden.compilerVersion !== compilerVersion) differences.push(`baseline: compiler ${golden.compilerVersion} differs from ${compilerVersion}`);
  for (const id of expected.keys()) if (!actual.has(id)) differences.push(id + ': starter missing from ' + STARTERS);
  for (const [id, item] of actual) {
    const reviewed = expected.get(id);
    if (!reviewed) { differences.push(id + ': starter has no reviewed baseline'); continue; }
    if (reviewed.source !== item.source || reviewed.sourceSha256 !== item.sourceSha256) differences.push(id + ': starter input changed');
    for (const [path, hash] of Object.entries(reviewed.files)) {
      if (!Object.hasOwn(item.files, path)) differences.push(id + ': missing ' + path);
      else if (item.files[path] !== hash) differences.push(id + ': changed ' + path);
    }
    for (const path of Object.keys(item.files)) if (!Object.hasOwn(reviewed.files, path)) differences.push(id + ': undeclared ' + path);
  }
  return differences;
}
export async function readGolden(root) {
  return JSON.parse(await readFile(join(root, GOLDEN_FILE), 'utf8'));
}
if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  const args = process.argv.slice(2), root = fileURLToPath(new URL('../../', import.meta.url));
  if (args.length > 1 || args.some(arg => !['--check', '--write'].includes(arg))) throw new Error('GOLDEN_USAGE: node tooling/compiler/golden.mjs [--check|--write]');
  const cases = await starterCases(root);
  if (args.includes('--write')) {
    await writeFile(join(root, GOLDEN_FILE), JSON.stringify(goldenDocument(cases), null, 1) + '\n');
    console.log(`Recorded ${cases.length} starter baselines in ${GOLDEN_FILE}. Review the diff before committing.`);
  } else {
    const differences = goldenDifferences(await readGolden(root), cases);
    if (differences.length) {
      console.error(differences.join('\n'));
      throw new Error(`GOLDEN_STALE: ${differences.length} undeclared generated-output difference(s). Review them, then run node tooling/compiler/golden.mjs --write.`);
    }
    console.log(`Verified ${cases.length} starter baselines against ${GOLDEN_FILE}.`);
  }
}
