/**
 * The CLI-owned lists in an Increment: `## Issues` and `## Pull requests`, each a marked region regenerated
 * from the documents together with the matching frontmatter key. Not lock-checked, so sync and status changes
 * of linked documents can refresh them; the commands that link documents check the Increment's lock first.
 */
import {
  defaultDeliverySchema, issuesRegion, issuesSection, pullRequestsRegion, pullRequestsSection, type IssueRow, type Problem, type PullRequestRow,
} from './model.ts';
import { lineEnding, listField, parseFrontmatter, setFrontmatterValue } from './frontmatter.ts';
import { findMarkedRegion, findSection, insertSection, outline, replaceMarkedRegion, replaceSectionContent } from './sections.ts';
import { formatWikilink } from './wikilinks.ts';

/** `- [[path|title]] · status · [#n](url)`. */
export function pullRequestRow(row: PullRequestRow): string {
  const link = row.number !== undefined && row.url ? ` · [#${row.number}](${row.url})` : '';
  return `- ${formatWikilink(row.path, row.title)} · ${row.status}${link}`;
}
/** `- [[path|title]] · status`. */
const issueRow = (row: IssueRow): string => `- ${formatWikilink(row.path, row.title)} · ${row.status}`;

interface ListKind { key: 'pullRequests' | 'issues'; region: string; section: string; before: readonly string[]; noun: string }
const pullRequestList: ListKind = { key: 'pullRequests', region: pullRequestsRegion, section: pullRequestsSection, before: [defaultDeliverySchema.handoff.generatedSection], noun: 'Pull request' };
const issueList: ListKind = { key: 'issues', region: issuesRegion, section: issuesSection, before: [pullRequestsSection, defaultDeliverySchema.handoff.generatedSection], noun: 'Issue' };
/** Frontmatter keys follow `refs` in this order. */
const keyOrder = ['type', 'id', 'title', 'owner', 'size', 'status', 'e2e', 'refs', 'pullRequests', 'issues', 'branch', 'base'];

function setList(text: string, kind: ListKind, lines: readonly string[]): string {
  const eol = lineEnding(text), body = lines.join(eol), replaced = replaceMarkedRegion(text, kind.region, body);
  if (replaced !== null) return replaced;
  const block = [`<!-- wb:${kind.region} generated by node bin/app; edits here are replaced -->`, ...(body ? [body] : []), `<!-- /wb:${kind.region} -->`].join(eol);
  const section = findSection(outline(text), kind.section);
  return section ? replaceSectionContent(text, section, block) : insertSection(text, kind.section, block, kind.before);
}
/** Rewrites the generated pull-request list, adding the section before the Completion record when needed. */
export const setPullRequestTable = (text: string, rows: readonly PullRequestRow[]): string => setList(text, pullRequestList, rows.map(pullRequestRow));
/** Rewrites the generated issue list, adding the section before Pull requests when needed. */
export const setIssueTable = (text: string, rows: readonly IssueRow[]): string => setList(text, issueList, rows.map(issueRow));
const keyed = (text: string, kind: ListKind, ids: readonly string[]) => setFrontmatterValue(text, kind.key, [...ids], { after: keyOrder.slice(0, keyOrder.indexOf(kind.key)) });
/** Sets the `pullRequests` ids and the generated list together. */
export const setPullRequests = (text: string, ids: readonly string[], rows: readonly PullRequestRow[]): string => setPullRequestTable(keyed(text, pullRequestList, ids), rows);
/** Sets the `issues` ids and the generated list together. */
export const setIssues = (text: string, ids: readonly string[], rows: readonly IssueRow[]): string => setIssueTable(keyed(text, issueList, ids), rows);

function listIds(text: string, region: string): string[] {
  const found = findMarkedRegion(text, region);
  if (!found) return [];
  return [...text.slice(found.start, found.end).matchAll(/^\s*-\s+\[\[([^[\]|#\n]+)/gm)].map(match => match[1]!.trim().split('/').at(-1)!.replace(/\.md$/i, ''));
}
/** Pull-request ids the generated list links to, by file name. */
export const pullRequestTableIds = (text: string): string[] => listIds(text, pullRequestsRegion);
/** Issue ids the generated list links to, by file name. */
export const issueTableIds = (text: string): string[] => listIds(text, issuesRegion);
/** Differences between each frontmatter key and its generated list. */
export function generatedListDrift(text: string): Problem[] {
  const data = parseFrontmatter(text).data;
  return [pullRequestList, issueList].flatMap(kind => {
    const listed = listField(data, kind.key), table = listIds(text, kind.region);
    const drift = [...new Set([...listed.filter(id => !table.includes(id)), ...table.filter(id => !listed.includes(id))])];
    return drift.length ? [{ code: 'INCREMENT_LINK_DRIFT', message: `The ${kind.key} key and the generated list differ for ${drift.join(', ')}.` }] : [];
  });
}
/**
 * Linked documents that name the increment but are not listed, and listed ids without a matching document.
 * `kind` picks the list: pull requests (default) or issues.
 */
export function incrementLinkDrift(increment: { id: string; pullRequests: readonly string[]; issues?: readonly string[] }, documents: readonly { id: string; increment: string }[], kind: 'pullRequests' | 'issues' = 'pullRequests'): Problem[] {
  const listed = kind === 'issues' ? increment.issues ?? [] : increment.pullRequests, noun = kind === 'issues' ? issueList.noun : pullRequestList.noun;
  const owned = documents.filter(item => item.increment === increment.id).map(item => item.id);
  const unlisted = owned.filter(id => !listed.includes(id)), orphaned = listed.filter(id => !owned.includes(id));
  return [...unlisted.map(id => ({ code: 'INCREMENT_LINK_DRIFT', message: `${noun} ${id} names ${increment.id} but is not in its ${kind} list.` })),
    ...orphaned.map(id => ({ code: 'INCREMENT_LINK_DRIFT', message: `${increment.id} lists ${id}, which has no document or names another increment.` }))];
}
