import { summary, statusLabels, type Workspace, type Iteration, type Work, type Status } from './model.ts';
import { esc, icon, button, iconButton, badge, statusBadge, heading, empty, formatDate, owner, avatar, personOptions, options, textarea, type ViewState } from './ui.ts';

export function workForm(state: Workspace, iteration: Iteration, work: Work, daily: boolean): string {
  const item = state.items.find(value=>value.id===work.itemId);
  const statuses: Status[] = ['ready','doing','blocked','done'];
  return `<form id="work-form" data-item-id="${esc(work.itemId)}" data-daily="${daily}"><div class="work-form-heading"><span class="eyebrow">${esc(item?.type??'Item')} · ${esc(work.itemId)}</span><h2>${esc(work.title)}</h2><p>${esc(item?.description)}</p></div>
    <fieldset class="status-fieldset"><legend>Where is this item now?</legend><div class="status-options">${statuses.map(status=>`<label class="status-option ${status}"><input type="radio" name="status" value="${status}" ${work.status===status?'checked':''}><span>${status==='done'?icon('check',15):''}${esc(statusLabels[status])}</span></label>`).join('')}</div></fieldset>
    <div class="form-grid"><label class="field" for="w-ownerId"><span>Who is taking the next step?</span><select id="w-ownerId" name="ownerId">${personOptions(state,work.ownerId)}</select></label><div class="field"><span>Planned estimate</span><div class="read-value">${work.estimate===null?'Not estimated':`${work.estimate} hours`} <small>not time spent</small></div></div></div>
    ${textarea('What changed or became clearer?','note',work.note,'w',3)}${textarea('What is the next useful step?','nextAction',work.nextAction,'w',2)}
    <div class="conditional-block warning-surface" data-status-section="blocked" ${work.status==='blocked'?'':'hidden'}>${textarea('What is blocking progress?','blocker',work.blocker,'w',2)}<p>Make the decision or dependency visible, not just the red status.</p></div>
    <div class="conditional-block done-surface" data-status-section="done" ${work.status==='done'?'':'hidden'}><label class="inline-check"><input name="doneCheck" type="checkbox" ${work.doneCheck?'checked':''}> The agreed Definition of Done is met.</label>${textarea('Changelog — what can the team or user do now?','releaseNote',work.releaseNote,'w',2)}<p>Only Done items belong in the delivered increment. A progress note alone is not delivery.</p></div>
    <p class="form-error" id="work-error" role="alert"></p><div class="form-footer"><span>${daily?'Save an item-level note for this daily.':'This updates the live increment, not an old review.'}</span><button class="btn primary" type="submit">${daily?'Save & next item':'Save progress'} ${icon('arrow',16)}</button></div></form>`;
}
export function dailyView(state: Workspace, ui: ViewState, iteration?: Iteration): string {
  if (!iteration||iteration.stage!=='active') return heading('Daily walkthrough','Walk the work, not the people.','Inspect progress toward the goal and agree the next useful steps.')+
    empty(iteration?.stage==='closed'?'This iteration has been reviewed.':'Start an iteration to walk its backlog.','Daily updates belong to an active iteration. Previous notes remain available in the increment.',button('Open iteration planning','navigate','planning','primary','arrow'))+
    (iteration?.daily.map(day=>`<details class="card daily-history"><summary>${formatDate(day.date,true)} · ${day.notes.length} items discussed</summary><p>${esc(day.summary)}</p>${day.notes.map(note=>`<p><strong>${esc(state.items.find(item=>item.id===note.itemId)?.title)}</strong><br>${esc(note.note)}<br><small>Next: ${esc(note.nextAction)}</small></p>`).join('')}</details>`).join('')??'');
  const day = iteration.daily.find(value=>value.date===state.clock);
  const count = iteration.work.filter(work=>day?.notes.some(note=>note.itemId===work.itemId)).length;
  const ranked = [...iteration.work].sort((a,b)=>({blocked:0,doing:1,ready:2,backlog:3,done:4}[a.status]-{blocked:0,doing:1,ready:2,backlog:3,done:4}[b.status]));
  const selected = iteration.work.find(work=>work.itemId===ui.dailyItemId)??ranked.find(work=>!day?.notes.some(note=>note.itemId===work.itemId))??ranked[0];
  const percent = iteration.work.length?Math.round(count/iteration.work.length*100):0;
  return heading('Daily · '+formatDate(state.clock,true),'Walk the work, not the people.','Start with blockers. Inspect every item. Finish with a shared next step.',button(day?.finished?'Edit daily summary':'Finish daily','finish-daily','','primary','check'))+
    `<section class="daily-goal"><span>${icon('leaf',20)} <strong>${esc(iteration.goal)}</strong></span><span>${count} / ${iteration.work.length} discussed ${day?.finished?badge('Daily completed','done'):''}</span><div class="daily-progress" role="progressbar" aria-label="Daily backlog walkthrough" aria-valuenow="${count}" aria-valuemin="0" aria-valuemax="${iteration.work.length||1}"><span style="width:${percent}%"></span></div></section>
    <div class="daily-layout"><section class="card daily-queue"><div class="card-heading"><div><h2>Iteration backlog</h2><p>Every item is part of the conversation.</p></div></div>${ranked.map((work,index)=>{const visited=day?.notes.some(note=>note.itemId===work.itemId);return `<button class="queue-item ${selected?.itemId===work.itemId?'selected':''}" data-action="daily-select" data-id="${esc(work.itemId)}" ${selected?.itemId===work.itemId?'aria-current="true"':''}><span class="queue-check ${visited?'visited':''}">${visited?icon('check',13):index+1}</span><span><strong>${esc(work.title)}</strong><span class="queue-meta">${statusBadge(work.status)}<small>${esc(owner(state,work.ownerId).split(' ')[0])}</small>${visited?'<small>Discussed</small>':''}</span></span></button>`;}).join('')||'<p class="padded muted">No current work. Add scope in planning or review the outcome.</p>'}<div class="queue-foot">A daily is for adapting the plan, not reporting individual productivity.</div></section>
    <section class="card daily-detail">${selected?workForm(state,iteration,selected,true):empty('No items to walk','Add an item from the backlog or proceed to the review.')}</section></div>
    ${iteration.daily.filter(value=>value.date!==state.clock).map(value=>`<details class="card daily-history"><summary>${formatDate(value.date,true)} · ${value.finished?'Daily completed':'In progress'} · ${value.notes.length} items</summary><p>${esc(value.summary)}</p>${value.notes.map(note=>`<p><strong>${esc(state.items.find(item=>item.id===note.itemId)?.title)}</strong><br>${esc(note.note)}<br><small>Next: ${esc(note.nextAction)}</small></p>`).join('')}</details>`).join('')}`;
}
export function incrementView(state: Workspace, iteration?: Iteration): string {
  if (!iteration) return heading('Increment & review','Show what became usable.','Make progress tangible, without counting unfinished work as delivered.')+empty('Your increment grows from Done work','Create an iteration and agree its backlog first.',button('Plan an iteration','navigate','planning','primary','plus'));
  const stats = summary(iteration); const snap = iteration.increment.snapshot;
  const remaining = snap?.unfinished??iteration.work.filter(work=>work.status!=='done');
  const outcomes = [{id:'not-assessed',title:'Not assessed yet'},{id:'met',title:'Goal met'},{id:'partly-met',title:'Goal partly met'},{id:'not-met',title:'Goal not met'}];
  return heading(`Increment ${String(iteration.index).padStart(2,'0')} · ${snap?'frozen review':'live draft'}`,'Show what became usable.','Review the outcome against the goal. Capture what to do differently next.',button('Export changelog','export-changelog','','secondary','export'))+
    `<section class="card increment-hero"><span class="increment-symbol">${icon('increment',36)}</span><div><div class="eyebrow">${esc(iteration.increment.id)}</div><h2>${esc(iteration.goal)}</h2><p>${snap?'Reviewed on '+formatDate(snap.date)+' · This is not a published release.':'A live, honest view of what is delivered — and what is not.'}</p></div><div class="increment-stat"><strong>${stats.done}<span> / ${stats.total}</span></strong><span>items delivered</span></div></section>
    <div class="review-layout"><div><section class="card changelog-card"><div class="card-heading"><div><h2>Delivered changelog</h2><p>Only work that meets the Definition of Done.</p></div>${badge(`${stats.done} delivered`,'done')}</div>${stats.delivered.map(work=>`<article class="changelog-entry"><span class="done-dot">${icon('check',14)}</span><div><h3>${esc(work.title)}</h3><p>${esc(work.releaseNote)}</p><small>${esc(owner(state,work.ownerId))} · Definition of Done confirmed</small></div></article>`).join('')||'<div class="empty-inline"><h3>Nothing delivered yet.</h3><p>That is useful information. Progress notes remain in the work, not in this changelog.</p></div>'}</section>
    <section class="card unfinished-card"><div class="card-heading"><div><h2>Progress, not delivery</h2><p>${snap?'Returned to the backlog for a fresh planning decision.':'Keep unfinished work visible; decide what happens next.'}</p></div>${badge(`${remaining.length} not delivered`)}</div>${remaining.map(work=>`<article class="unfinished-entry"><div><h3>${esc(work.title)}</h3>${statusBadge(work.status)}</div><p>${esc(work.note)||'No progress note recorded.'}</p><small>Next: ${esc(work.nextAction)||'Discuss at review.'}</small></article>`).join('')||'<p class="padded muted">Every current item is Done.</p>'}</section></div>
    <section class="card review-panel"><div class="card-heading"><div><h2>${snap?'Review record':'Prepare the review'}</h2><p>${snap?'The increment snapshot cannot be rewritten.':'What changed for the product and the people using it?'}</p></div></div>
      ${iteration.stage==='active'?`<form id="review-form">${textarea('Increment summary','summary',iteration.increment.summary,'r',3)}<label class="field" for="r-goalOutcome"><span>Did we achieve the goal?</span><select id="r-goalOutcome" name="goalOutcome">${options(outcomes,iteration.increment.goalOutcome)}</select></label>${textarea('Review observations & feedback','reviewNotes',iteration.increment.reviewNotes,'r',4)}<div class="notice-box">Closing records one increment snapshot. ${remaining.length} unfinished items become available for planning again. Nothing is automatically marked Done or rolled forward.</div><p class="form-error" id="review-error" role="alert"></p><div class="stack-actions"><button class="btn secondary" type="submit" name="intent" value="save">Save review draft</button><button class="btn primary" type="submit" name="intent" value="close">Review & close iteration ${icon('check',16)}</button></div></form>`:
      `<div class="padded"><h3>Summary</h3><p class="pre-wrap">${esc(iteration.increment.summary)||'No summary yet.'}</p><h3>Goal outcome</h3>${badge(outcomes.find(value=>value.id===iteration.increment.goalOutcome)?.title??'Not assessed',snap?'done':'neutral')}<h3>Review observations</h3><p class="pre-wrap">${esc(iteration.increment.reviewNotes)||'Review is available after the iteration starts.'}</p>${snap?button('Continue to retrospective','navigate','retro','primary','arrow'):button('Agree the plan first','navigate','planning','primary','arrow')}</div>`}
      <div class="review-followup">${button('Capture a follow-up item','review-feedback','','quiet','plus')}<p>Feedback returns to the backlog, not silently into this increment.</p></div></section></div>`;
}
export function retroView(state: Workspace, iteration?: Iteration): string {
  if (!iteration) return heading('Retrospective','Make the next iteration better.','Keep the learning small, specific, and actionable.')+empty('Create an iteration first','Retrospective notes belong to the iteration that produced the learning.');
  const columns = [{id:'keep',title:'Keep doing',prompt:'What helped us make progress?',icon:'leaf'},
    {id:'change',title:'Change something',prompt:'What made the work harder?',icon:'settings'},
    {id:'try',title:'Try next',prompt:'One experiment for a better week.',icon:'plus'}];
  return heading(`Retrospective · iteration ${String(iteration.index).padStart(2,'0')}`,'A better way to work, one step at a time.','Turn a conversation into one concrete improvement. Give it a place in the backlog.',button('Plan the next iteration','new-iteration','','primary','arrow'))+
    `<div class="retro-context"><span>${icon('retro',21)} <strong>${esc(iteration.goal)}</strong></span><p>${iteration.retro.filter(note=>note.backlogItemId).length} improvement actions linked to the backlog</p></div>
    <div class="retro-board">${columns.map(column=>`<section class="retro-column ${column.id}"><div class="retro-heading"><span class="retro-icon">${icon(column.icon,21)}</span><h2>${column.title}</h2>${badge(String(iteration.retro.filter(note=>note.category===column.id).length))}<p>${column.prompt}</p></div><div class="retro-notes">${iteration.retro.filter(note=>note.category===column.id).map(note=>`<article class="retro-note"><p>${esc(note.text)}</p><div>${avatar(state,note.ownerId,true)}${!note.backlogItemId?iconButton('Remove retrospective note','delete-retro',note.id,'close'):''}</div><div class="retro-note-action">${note.backlogItemId?button('Open backlog action','edit-item',note.backlogItemId,'quiet','check'):button('Make a backlog action','promote-retro',note.id,'quiet','arrow')}</div></article>`).join('')}</div>${button('Add a thought','new-retro',column.id,'retro-add','plus')}</section>`).join('')}</div>
    <div class="learning-note">${icon('help',21)}<p><strong>Close the learning loop.</strong> A retrospective action is a normal backlog item, with an owner and a future planning decision. It does not secretly increase next week’s scope.</p></div>`;
}
