import { summary, workingDays, nameOf, type Workspace, type Iteration } from './model.ts';
import { esc, icon, button, badge, heading, empty, formatDate, workRow, avatar } from './ui.ts';

function gauge(percent: number, label: string, value: string): string {
  const length = 263.9; const offset = length*(1-percent/100);
  return `<div class="gauge" role="img" aria-label="${esc(label)}: ${esc(value)}"><svg viewBox="0 0 100 100" aria-hidden="true"><circle class="gauge-track" cx="50" cy="50" r="42"/><circle class="gauge-fill" cx="50" cy="50" r="42" stroke-dasharray="${length}" stroke-dashoffset="${offset}"/></svg><div><strong>${esc(value)}</strong><span>${esc(label)}</span></div></div>`;
}
export function overview(state: Workspace, iteration?: Iteration): string {
  if (!iteration) return heading('A small step, every week','Your next increment starts here.','Keep the backlog open-ended. Make each iteration focused.')+
    empty('Create your first iteration','Give it a goal, choose a few items, and make the next useful improvement together.',button('Create iteration','new-iteration','','primary','plus'));
  const stats = summary(iteration);
  const days = workingDays(iteration.start,iteration.end);
  const elapsed = days.filter(date=>date<=state.clock).length;
  const today = iteration.daily.find(daily=>daily.date===state.clock);
  const discussed = iteration.work.filter(work=>today?.notes.some(note=>note.itemId===work.itemId)).length;
  const confidence = {'unknown':'Not assessed','on-track':'On track','at-risk':'At risk','off-track':'Off track'}[iteration.confidence];
  const nextAction = iteration.stage==='planning'?button('Continue planning','navigate','planning','primary','arrow'):iteration.stage==='active'?button('Start today’s daily','navigate','daily','primary','arrow'):button('Reflect & improve','navigate','retro','primary','arrow');
  const focus = [...iteration.work].sort((a,b)=>({blocked:0,doing:1,ready:2,backlog:3,done:4}[a.status]-{blocked:0,doing:1,ready:2,backlog:3,done:4}[b.status])).slice(0,4);
  return heading('Iteration overview','A clear goal. A visible next step.','One shared view of the plan, the work, and what is becoming usable.',button('New iteration','new-iteration','','secondary','plus'))+
  `<section class="goal-banner"><div><div class="banner-kicker">${badge(iteration.stage==='closed'?'Reviewed increment':iteration.stage==='active'?'Iteration in progress':'Planning draft',iteration.stage==='closed'?'done':iteration.stage==='active'?'active':'neutral')}<span>ITERATION ${String(iteration.index).padStart(2,'0')}</span></div>
    <h2>${esc(iteration.goal)}</h2><p>${icon('planning',16)} ${formatDate(iteration.start)} – ${formatDate(iteration.end)} <span>·</span> ${days.length} working days <span>·</span> ${iteration.members.length} people</p>
    <div class="goal-actions">${nextAction}<button class="banner-link" data-action="navigate" data-id="planning">See the agreed plan ${icon('arrow',16)}</button></div></div>
    <div class="banner-art" aria-hidden="true"><div class="tile back">${icon('backlog',28)}</div><div class="tile middle">${icon('check',30)}</div><div class="tile front">${icon('increment',40)}</div><span>Every iteration, one step forward.</span></div></section>
  <div class="metrics-grid"><section class="card metric delivery">${gauge(stats.percent,'delivered',stats.total?`${stats.percent}%`:'—')}<div><h3>Increment progress</h3><div class="metric-number">${stats.done}<span> / ${stats.total} items</span></div><p>Done and ready to demonstrate.</p><button class="text-link" data-action="navigate" data-id="increment">Explore the increment ${icon('arrow',14)}</button></div></section>
    <section class="card metric compact"><span class="metric-icon">${icon('history',20)}</span><h3>Iteration time</h3><div class="metric-number">${iteration.stage==='closed'?'Closed':days.length?`Day ${elapsed}`:'No workdays'}<span>${iteration.stage==='closed'?'':` / ${days.length}`}</span></div><div class="day-track" aria-hidden="true">${days.slice(0,31).map((date)=>`<span class="${date<=state.clock?'elapsed':''}" title="${date}"></span>`).join('')}</div><p>Time elapsed is not work completed.</p></section>
    <section class="card metric compact"><span class="metric-icon ${stats.blocked?'amber':''}">${icon('warning',20)}</span><h3>Needs attention</h3><div class="metric-number">${stats.blocked}<span> blocked</span></div><p>${stats.blocked?'Unblock the next useful step together.':'No blocked work in this iteration.'}</p><button class="text-link" data-action="navigate" data-id="daily">Walk the backlog ${icon('arrow',14)}</button></section>
    <section class="card metric compact"><span class="metric-icon">${icon('leaf',20)}</span><h3>Goal confidence</h3><div class="confidence ${esc(iteration.confidence)}">${esc(confidence)}</div><p>A team assessment, not an algorithm.</p>${iteration.stage!=='closed'?button('Update assessment','confidence','','quiet'):badge('Review recorded','done')}</section></div>
  <section class="cadence-section"><div class="section-heading"><h2>Your iteration rhythm</h2><span>Plan together. Adapt daily. Learn from delivery.</span></div><div class="cadence-grid">
    <button class="cadence" data-action="navigate" data-id="planning"><span class="cadence-icon ${iteration.stage!=='planning'?'complete':''}">${icon(iteration.stage!=='planning'?'check':'planning',20)}</span><span><small>${formatDate(iteration.start,true)}</small><strong>Iteration planning</strong><em>${iteration.baseline?`${iteration.baseline.length} items agreed`:'Choose the next increment'}</em></span>${icon('chevron',15)}</button>
    <button class="cadence ${iteration.stage==='active'?'current':''}" data-action="navigate" data-id="daily"><span class="cadence-icon">${icon('daily',20)}</span><span><small>Every working day</small><strong>Daily walkthrough</strong><em>${iteration.stage==='active'?`${discussed} of ${stats.total} discussed today`:'Inspect and adapt the plan'}</em></span>${icon('chevron',15)}</button>
    <button class="cadence" data-action="navigate" data-id="increment"><span class="cadence-icon">${icon('increment',20)}</span><span><small>${formatDate(iteration.end,true)}</small><strong>Increment review</strong><em>${iteration.stage==='closed'?'Result recorded':'Show what became usable'}</em></span>${icon('chevron',15)}</button>
    <button class="cadence" data-action="navigate" data-id="retro"><span class="cadence-icon">${icon('retro',20)}</span><span><small>After the review</small><strong>Retrospective</strong><em>Choose one thing to improve</em></span>${icon('chevron',15)}</button></div></section>
  <div class="dashboard-bottom"><section class="card"><div class="card-heading"><div><h2>${iteration.stage==='closed'?'The reviewed work':'Move the work forward'}</h2><p>Start with blockers, then the work closest to Done.</p></div>${button('View all','navigate','daily','quiet','arrow')}</div><div class="work-list">${focus.map(work=>workRow(state,work,iteration)).join('')||'<p class="muted padded">No work selected yet.</p>'}</div></section>
    <section class="card capacity-card"><div class="card-heading"><div><h2>People & room to work</h2><p>Capacity is a planning conversation.</p></div></div><div class="capacity-number">${stats.estimate}<span> / ${stats.capacity}h</span></div><p class="muted">Estimated work / available team hours</p><div class="capacity-track" role="img" aria-label="${stats.estimate} hours estimated of ${stats.capacity} hours available"><span style="width:${stats.capacity?Math.min(100,stats.estimate/stats.capacity*100):0}%"></span></div>${stats.unestimated?`<p class="warning-text">${stats.unestimated} items have no estimate; totals are partial.</p>`:''}${stats.estimate>stats.capacity?'<p class="warning-text">Discuss scope or capacity before starting more work.</p>':''}
    <div class="team-stack">${iteration.members.map(member=>avatar(state,member.resourceId)).join('')}<span>${iteration.members.length} people in this iteration</span></div>${button('Manage resources','navigate','resources','secondary')}</section></div>`;
}
