import { defineConfig } from '@playwright/test';
// Generated by the compiler: browser checks of this project's own preview, not of the framework harness (which keeps
// configs/testing/playwright.config.ts and runs with npm run test:e2e:framework). The offline click-dummy is rebuilt
// from source and served on loopback. SHELL_CHROMIUM may name a Chromium executable when Playwright's pinned browser
// is not installed; nothing is downloaded.
const port = 4181;
export default defineConfig({
  testDir: 'tests/e2e', testMatch: ['ui-quality.spec.ts', 'journeys/**/*.spec.ts'],
  fullyParallel: false, workers: 1, retries: 0, timeout: 30000,
  reporter: [['list'], ['json', { outputFile: 'reports/e2e/results.json' }], ['html', { outputFolder: 'reports/e2e/html', open: 'never' }]],
  outputDir: 'reports/e2e/artifacts',
  use: { baseURL: `http://127.0.0.1:${port}`, browserName: 'chromium', locale: 'en-US', timezoneId: 'Europe/Berlin', reducedMotion: 'reduce',
    viewport: { width: 1280, height: 900 }, trace: 'retain-on-failure', screenshot: 'only-on-failure',
    launchOptions: process.env.SHELL_CHROMIUM ? { executablePath: process.env.SHELL_CHROMIUM } : {},
  },
  webServer: { command: `"${process.execPath}" scripts/e2e/serve-clickdummy.mjs ${port}`, url: `http://127.0.0.1:${port}/`, reuseExistingServer: false, timeout: 120000 },
});
