import { access } from 'node:fs/promises';
import { join } from 'node:path';
import { createFilePlan } from '../shared/file-plan.mjs';

const json = value => JSON.stringify(value, null, 2) + '\n';
const entries = [
  {
    path: '.mcp.json',
    content: json({
      mcpServers: {
        workbench: {
          command: 'node',
          args: ['${CLAUDE_PROJECT_DIR}/scripts/agent/workbench-mcp.mjs'],
        },
      },
    }),
  },
  {
    path: '.claude/settings.json',
    content: json({
      $schema: 'https://json.schemastore.org/claude-code-settings.json',
      permissions: { allow: ['mcp__workbench'] },
    }),
  },
  {
    path: '.codex/config.toml',
    content: `# Generated by npm run setup -- --mcp. Project-local and loaded only for trusted projects.
[mcp_servers.workbench]
command = "node"
args = ["scripts/agent/workbench-mcp.mjs"]
cwd = "."
startup_timeout_sec = 10
default_tools_approval_mode = "writes"
`,
  },
];

function previousHashes(previous) {
  const values = Array.isArray(previous?.files) ? previous.files : [];
  return new Map(values.filter(item => item && typeof item.path === 'string' && typeof item.afterHash === 'string')
    .map(item => [item.path, item.afterHash]));
}
export async function planLocalMcp(root, enabled, previous = null) {
  const plan = await createFilePlan(root, enabled ? entries : []);
  if (!enabled) return { version: 1, enabled: false, server: 'workbench', transport: 'stdio', clients: [], plan, files: [] };
  await access(join(root, 'scripts/agent/workbench-mcp.mjs'));
  const owned = previousHashes(previous);
  for (const change of plan.changes) {
    if (change.status === 'update' && owned.get(change.path) !== change.beforeHash) {
      throw new Error(`MCP_CONFIG_CONFLICT: ${change.path} has user or external changes; preserve/reconcile it before setup manages this file.`);
    }
  }
  return {
    version: 1, enabled: true, server: 'workbench', transport: 'stdio', clients: ['claude-code', 'codex'], plan,
    files: plan.changes.map(({ path, status, beforeHash, afterHash }) => ({ path, status, beforeHash, afterHash })),
  };
}
