"""Browser checks for the explicitly labelled vanilla-JS review, NOT the Vue application."""
import asyncio, json
from pathlib import Path
from playwright.async_api import async_playwright
ROOT=Path(__file__).resolve().parent.parent; HTML=(ROOT/'review-preview/editor-only-review.html').read_text()
async def main():
 checks=[]; errors=[]; requests=[]
 async with async_playwright() as p:
  browser=await p.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=['--no-sandbox'])
  page=await browser.new_page(viewport={'width':1600,'height':1000},device_scale_factor=1)
  page.on('pageerror',lambda e:errors.append(str(e)))
  page.on('console',lambda m:errors.append(m.text) if m.type=='error' else None)
  page.on('request',lambda r:requests.append(r.url))
  await page.set_content(HTML,wait_until='load'); await page.wait_for_timeout(6000)
  async def check(name,condition):
   assert condition,name
   checks.append(name)
  async def action(a):
   await page.locator(f'[data-action="{a}"]:visible').first.click(); await page.wait_for_timeout(120)
  await check('review runtime identity is explicit', await page.evaluate("JourneyLens.runtime === 'vanilla-js-review-not-vue'"))
  await check('no application navigation rail, account selector or preview shell', await page.locator('.rail,.brand,.workspace-button,.avatar-button,.preview-shell').count()==0)
  await check('initial model has 28 pages and a root', await page.evaluate('JourneyLens.getWorkspace().pages.length')==29)
  await page.locator('[data-action="close-toast"]').click() if await page.locator('[data-action="close-toast"]').count() else None
  await page.screenshot(path=str(ROOT/'qa/editor-desktop.png'))
  await action('toggle-page-tree')
  await check('page tree opens and shows the current hierarchy', await page.locator('#sitemap-tree').is_visible() and await page.locator('#sitemap-tree .tree-page').count()>15)
  await action('show-related')
  await check('related panel includes parent, siblings and children', 'Sibling pages' in await page.locator('#inspector').inner_text() and 'Child pages' in await page.locator('#inspector').inner_text())
  await page.screenshot(path=str(ROOT/'qa/editor-related-pages.png'))
  await page.locator('#inspector .nearby-page[data-id="project-files"]').click()
  await check('sibling link selects the same page entity', await page.locator('#page-route').input_value()=='/projects/files')
  await page.locator('#sitemap-tree .tree-page[data-id="project"]').click()
  await action('toggle-page-tree')
  await page.locator('#page-purpose').fill('Review the scope, ownership and progress of one project.')
  await page.locator('#page-route').click()
  await check('inspector edits update the exported model', await page.evaluate("JourneyLens.getWorkspace().pages.find(p=>p.id==='project').purpose")=='Review the scope, ownership and progress of one project.')
  await action('undo')
  await check('undo restores the previous purpose', await page.evaluate("JourneyLens.getWorkspace().pages.find(p=>p.id==='project').purpose")!='Review the scope, ownership and progress of one project.')
  await action('redo')
  await check('redo restores the edit', await page.evaluate("JourneyLens.getWorkspace().pages.find(p=>p.id==='project').purpose")=='Review the scope, ownership and progress of one project.')
  await action('add-page'); await page.locator('#new-page-title').fill('Timeline')
  await page.locator('#new-page-route').fill('/projects/:projectId/timeline')
  await page.locator('#modal-form button[type="submit"]').click(); await page.wait_for_timeout(180)
  new_id=await page.evaluate("JourneyLens.getWorkspace().pages.find(p=>p.title==='Timeline').id")
  await check('add page creates one new entity', await page.evaluate('JourneyLens.getWorkspace().pages.length')==30)
  await page.locator('#inspector [data-action="node-menu"]').click()
  await action('move-page'); await page.locator('#move-parent').select_option('projects')
  await page.locator('#modal-form button[type="submit"]').click(); await page.wait_for_timeout(180)
  moved=await page.evaluate('(id)=>JourneyLens.getWorkspace().pages.find(p=>p.id===id)',new_id)
  await check('moving a page preserves its URL', moved['parentId']=='projects' and moved['route']=='/projects/:projectId/timeline')
  await action('undo')
  await check('move is reversible',await page.evaluate('(id)=>JourneyLens.getWorkspace().pages.find(p=>p.id===id).parentId',new_id)=='project')
  await action('outline-view')
  await check('outline is a functional alternate editor view',await page.locator('.outline-table').is_visible())
  await action('map-view')
  await action('journeys')
  await page.locator('[data-action="activate-journey"]').first.click(); await page.wait_for_timeout(200)
  await check('journey remains a canvas overlay without simulated application', await page.locator('.preview-shell').count()==0 and 'Journey' in await page.locator('#inspector').inner_text())
  await page.screenshot(path=str(ROOT/'qa/editor-journey-overlay.png'))
  await action('project-menu')
  async with page.expect_download() as dl:
   await action('export-json')
  download=await dl.value; await download.save_as(ROOT/'qa/review-roundtrip.json')
  exported=json.loads((ROOT/'qa/review-roundtrip.json').read_text())
  await check('JSON export includes edited entities and journeys',len(exported['pages'])==30 and len(exported['journeys'])==3)
  await check('no external network requests from review',len(requests)==0)
  # Start a new mobile document, not a desktop window with a retained inspector.
  mobile=await browser.new_page(viewport={'width':390,'height':844},device_scale_factor=1)
  mobile.on('pageerror',lambda e:errors.append(str(e)))
  await mobile.set_content(HTML,wait_until='load');await mobile.wait_for_timeout(6000)
  if await mobile.locator('[data-action="close-toast"]').count(): await mobile.locator('[data-action="close-toast"]').click()
  await check('mobile does not open an inspector over the canvas initially',not await mobile.locator('#inspector').is_visible())
  await check('mobile has no document-wide horizontal overflow',await mobile.evaluate('document.documentElement.scrollWidth<=innerWidth'))
  await check('mobile add and map icons are visible',await mobile.locator('.add-page svg').is_visible() and await mobile.locator('#view-map svg').is_visible())
  await mobile.screenshot(path=str(ROOT/'qa/editor-mobile.png'))
  await mobile.locator('.tree-toggle').click();await mobile.wait_for_timeout(120)
  await check('mobile tree is reachable',await mobile.locator('#sitemap-tree').is_visible())
  await mobile.locator('#sitemap-tree .tree-page[data-id="project"]').click();await mobile.wait_for_timeout(120)
  await check('mobile selection switches from tree to inspector',not await mobile.locator('#sitemap-tree').is_visible() and await mobile.locator('#inspector').is_visible())
  await mobile.locator('[data-action="inspector-tab"][data-tab="related"]').click();await mobile.screenshot(path=str(ROOT/'qa/editor-mobile-related.png'))
  await check('no browser console exceptions',not errors)
  await browser.close()
  (ROOT/'qa/review-browser-tests.json').write_text(json.dumps({'scope':'VANILLA-JS REVIEW ONLY. Does not verify Vue/Nuxt UI/Vue Flow.','checks':checks,'passed':len(checks),'errors':errors,'network_requests':requests},indent=2))
  print(json.dumps({'passed':len(checks),'errors':errors},indent=2))
asyncio.run(main())
