import type { Model } from './model.ts';
import type { Add } from './file-code.ts';
import { uiQualitySpec, type UiQualitySurface } from './ui-quality-spec.ts';

/** Browser UI quality checks of the generated preview. The preview is the offline click-dummy: it is rebuilt from
 * source with the project's own build command, served on loopback and audited per surface. Framework harness specs keep their own config and script. */
const port = 4181;
const spec = 'tests/e2e/ui-quality.spec.ts';
const server = 'tooling/e2e/serve-clickdummy.mjs';

/** Page-like surfaces in model order, as the preview's surface picker lists them; dialogs, actions and groups have no address. */
export function uiQualitySurfaces(m: Model): UiQualitySurface[] {
  return m.screens.filter(screen => !['group', 'action', 'modal'].includes(screen.kind)).map(screen => ({ id: screen.id, label: screen.label.replace(/\s+/g, ' ').trim() }));
}
/** `test:e2e` runs this project's Playwright specs; the framework harness specs move to `test:e2e:framework`. */
export function uiQualityScripts(scripts: Record<string, string>): void {
  const framework = scripts['test:e2e'];
  if (framework !== undefined) scripts['test:e2e:framework'] = framework;
  scripts['test:e2e'] = 'playwright test';
  scripts['test:ui-quality'] = `playwright test ${spec}`;
}
function playwrightConfig(): string {
  return `import { defineConfig } from '@playwright/test';
// Generated by the compiler: browser checks of this project's own preview, not of the framework harness (which keeps
// configs/testing/playwright.config.ts and runs with npm run test:e2e:framework). The offline click-dummy is rebuilt
// from source and served on loopback. SHELL_CHROMIUM may name a Chromium executable when Playwright's pinned browser
// is not installed; nothing is downloaded.
const port = ${port};
export default defineConfig({
  testDir: 'tests/e2e', testMatch: ['ui-quality.spec.ts', 'journeys/**/*.spec.ts'],
  fullyParallel: false, workers: 1, retries: 0, timeout: 30000,
  reporter: [['list'], ['json', { outputFile: 'reports/e2e/results.json' }], ['html', { outputFolder: 'reports/e2e/html', open: 'never' }]],
  outputDir: 'reports/e2e/artifacts',
  use: { baseURL: \`http://127.0.0.1:\${port}\`, browserName: 'chromium', locale: 'en-US', timezoneId: 'Europe/Berlin', reducedMotion: 'reduce',
    viewport: { width: 1280, height: 900 }, trace: 'retain-on-failure', screenshot: 'only-on-failure',
    launchOptions: process.env.SHELL_CHROMIUM ? { executablePath: process.env.SHELL_CHROMIUM } : {},
  },
  webServer: { command: \`"\${process.execPath}" ${server} \${port}\`, url: \`http://127.0.0.1:\${port}/\`, reuseExistingServer: false, timeout: 120000 },
});
`;
}
function serveScript(): string {
  return `// Generated by the compiler. Rebuilds the offline click-dummy from source with the project's own command, then
// serves the resulting clickdummy.html on loopback only. The build replaces the previous local clickdummy.html.
import { spawnSync } from 'node:child_process';
import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const root = process.cwd(), port = Number(process.argv[2] ?? ${port}), page = resolve(root, 'clickdummy.html');
const build = spawnSync(process.execPath, ['bin/app', 'clickdummy', 'build', '--replace'], { cwd: root, encoding: 'utf8' });
if (build.status !== 0) { console.error('Click-dummy build failed (exit ' + build.status + ').\\n' + build.stdout + build.stderr); process.exit(1); }

const server = createServer(async (request, response) => {
  const path = new URL(request.url ?? '/', 'http://127.0.0.1').pathname;
  if (request.method !== 'GET' || !['/', '/index.html', '/clickdummy.html'].includes(path)) { response.writeHead(404).end(); return; }
  response.writeHead(200, { 'content-type': 'text/html; charset=utf-8', 'cache-control': 'no-store' }).end(await readFile(page));
});
server.listen(port, '127.0.0.1', () => console.log('Serving ' + page + ' at http://127.0.0.1:' + port + '/'));
`;
}
export function uiQualityCode(m: Model, add: Add): void {
  add('playwright.config.ts', playwrightConfig(), 'managed');
  add(server, serveScript(), 'managed');
  add(spec, uiQualitySpec(uiQualitySurfaces(m)), 'managed');
}
