/** Pure rendering of runtime-owned command metadata. No handler execution or filesystem access. */
const effects = Object.freeze({
  read: 'Inspection/discovery. Some commands write reports only when explicitly requested; inspect command-specific help.',
  plan: 'Reviewed file plan. Preview first; application requires explicit approval. Saving --plan-out itself writes a plan file.',
  process: 'Runs trusted project code and may write outputs/caches or access the network. Review --dry-run before execution.',
  fixtures: 'Owned test-data operation. Mutation/reset uses its own reviewed approval; not a general project write.',
  release: 'Release workflow. Publication requires separate candidate authorization; --yes does not grant it.',
  remote: 'Reviewed hosting-platform write: the preview reads GitHub or Azure DevOps; --apply <planHash> or --yes writes the remote first, then the local record. Never replayable with --plan-out or plan apply.',
});
const text = value => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('|', '&#124;').replaceAll('\r', '').replaceAll('\n', '<br>');
const slug = id => id.replaceAll(' ', '-');
function required(value, message) { if (!value) throw new Error(`MANUAL_CONTRACT: ${message}`); }
function code(value) {
  const runs = String(value).match(/`+/g) ?? [];
  const fence = '`'.repeat(Math.max(3, ...runs.map(run => run.length + 1)));
  return `${fence}sh\n${value}\n${fence}`;
}
/** Keep a machine-readable copy alongside Markdown; fail rather than silently omit an undocumented option. */
export function buildModel(commands, helpFor, parameterKinds, groups, version, diagnostics) {
  required(Array.isArray(commands) && commands.length > 0, 'empty command catalog');
  const ids = new Set(); const slugs = new Set();
  const entries = commands.map(command => {
    required(/^[a-z][a-z0-9-]*(?: [a-z][a-z0-9-]*)*$/.test(command.id), `unsafe command id: ${command.id}`);
    required(!ids.has(command.id) && !slugs.has(slug(command.id)), `duplicate command/anchor: ${command.id}`);
    ids.add(command.id); slugs.add(slug(command.id));
    required(command.summary?.trim(), `missing summary: ${command.id}`);
    required(Object.hasOwn(effects, command.effect), `unknown effect: ${command.id}`);
    required(Number.isInteger(command.maxArgs) && command.maxArgs >= 0, `invalid argument bound: ${command.id}`);
    const help = helpFor(command); const kinds = parameterKinds(command);
    required(help.usage?.trim() && help.examples?.length, `missing usage/examples: ${command.id}`);
    for (const name of Object.keys(command.options)) required(help.optionHelp[name]?.description?.trim(), `undocumented --${name}: ${command.id}`);
    const options = Object.entries(help.optionHelp).map(([name, detail]) => {
      required(['flag', 'value'].includes(kinds[name]), `help references unknown option --${name}: ${command.id}`);
      required(detail.description?.trim(), `empty option description --${name}: ${command.id}`);
      return { name, kind: kinds[name], ...detail };
    });
    return { id: command.id, summary: command.summary, effect: command.effect, maxArgs: command.maxArgs,
      group: help.group, usage: help.usage, examples: [...help.examples], options,
      parserOnlyOptions: Object.keys(kinds).filter(name => !Object.hasOwn(help.optionHelp, name)).sort() };
  });
  const grouping = new Map();
  for (const group of groups) {
    for (const id of group.commands) {
      required(ids.has(id), `group contains unknown command: ${id}`);
      required(!grouping.has(id), `command occurs in multiple groups: ${id}`);
      grouping.set(id, group.id);
    }
  }
  for (const entry of entries) required(grouping.get(entry.id) === entry.group, `missing/mismatched group: ${entry.id}`);
  return { schemaVersion: 1, frameworkVersion: String(version), source: 'src/cli/adapters/framework/catalog.ts + help-text.ts',
    groups: groups.map(group => ({ ...group, commands: [...group.commands] })), commands: entries,
    diagnostics: Object.entries(diagnostics).sort(([a], [b]) => a < b ? -1 : a > b ? 1 : 0).map(([id, help]) => ({ id, help })) };
}
export function renderReference(model) {
  const lines = ['# Command reference', '', '<!-- Generated by tooling/documentation/manual.mjs. Do not edit. -->', '',
    `Framework version: **${text(model.frameworkVersion)}**. Commands: **${model.commands.length}**.`, '',
    'Generated from the same catalog and explanatory metadata used by terminal help. This is command-contract evidence, not proof that a user journey or native interaction has passed acceptance.', '',
    'Examples are copied from maintained help metadata. Replace placeholders before running; examples are not executed during documentation generation.', '',
    'The tables list options with documented command semantics. Some common flags are syntactically accepted by the parser but have no documented effect for a particular command; they are identified separately, never advertised as working controls.', ''];
  const byId = new Map(model.commands.map(command => [command.id, command]));
  for (const group of model.groups) {
    lines.push(`## ${text(group.title)}`, '');
    for (const id of group.commands) lines.push(`- [${id}](#${slug(id)}) — ${text(byId.get(id).summary)}`);
    lines.push('');
  }
  for (const command of model.commands) {
    lines.push(`## ${command.id}`, '', command.summary, '', code(command.usage), '',
      `**Effect:** ${command.effect}. ${effects[command.effect]}`, '',
      `**Maximum positional arguments:** ${command.maxArgs}. See usage and examples for their meaning; this bound does not mean all arguments are optional.`, '',
      '| Option | Kind | Meaning | Values / default |', '| --- | --- | --- | --- |');
    for (const option of command.options) {
      const detail = [option.values?.length ? `Values: ${option.values.join(', ')}` : '', option.default !== undefined ? `Default: ${option.default}` : ''].filter(Boolean).join('; ');
      lines.push(`| --${text(option.name)} | ${option.kind} | ${text(option.description)} | ${text(detail || 'See command semantics')} |`);
    }
    if (command.parserOnlyOptions.length) lines.push('', `Parser-accepted common flags without documented semantics here: ${command.parserOnlyOptions.map(name => `\`--${name}\``).join(', ')}. Do not rely on them to prevent or authorize effects.`);
    lines.push('', '### Examples', '', code(command.examples.join('\n')), '');
  }
  return lines.join('\n');
}
export function renderDiagnostics(model) {
  const lines = ['# Compiler diagnostics', '', '<!-- Generated by tooling/documentation/manual.mjs. Do not edit. -->', '',
    'These stable codes and recovery hints come directly from the compiler diagnostic catalog. Other operation errors can also occur; this is not an exhaustive list of every CLI failure.', '',
    'Inspect a code with `node bin/app compiler explain CODE`. Do not automatically repeat a write after a failure.', ''];
  for (const item of model.diagnostics) lines.push(`## ${item.id}`, '', item.help, '');
  return lines.join('\n');
}
