import { requireSketch } from '#shared/contracts/sketch-errors.ts';
import { collectionField, collectionStatus, type CollectionDefinition } from './collection-definition.ts';
import { collectionOverdue, type CollectionRecord, type CollectionValue } from './collection-record.ts';
import { collectionCell } from './collection-query.ts';
/** A record with its note link relative to the register (the collection folder). */
export interface CollectionRegisterRow { record: CollectionRecord; href: string }
/** Table cells stay on one line; pipes are escaped so authored text cannot break the table. */
export const collectionTableText = (value: string) => value.replace(/\s+/g, ' ').replace(/\\/g, '\\\\').replace(/\|/g, '\\|').trim();
const collectionLink = (row: CollectionRegisterRow) => `[${row.record.id}](<${row.href.replace(/[<>]/g, '')}>)`;
function labelOf(definition: CollectionDefinition, key: string, value: CollectionValue | undefined): string {
  if (value === undefined) return '';
  const field = collectionField(definition, key);
  const label = key === 'status' ? collectionStatus(definition, String(value))?.label
    : field?.kind === 'choice' ? definition.vocabularies[field.vocabulary!]!.find(item => item.id === value)?.label : undefined;
  return label ?? (Array.isArray(value) ? value.join(', ') : String(value));
}
const heading = (definition: CollectionDefinition, key: string) => key === 'id' ? 'ID' : key === 'status' ? 'Status' : collectionField(definition, key)?.label ?? key;
function table(definition: CollectionDefinition, rows: readonly CollectionRegisterRow[]): string {
  const columns = definition.report.columns;
  const lines = [`| ${columns.map(key => heading(definition, key)).join(' | ')} |`, `| ${columns.map(() => '---').join(' | ')} |`];
  for (const row of rows) lines.push(`| ${columns.map(key => key === 'id' ? collectionLink(row) : collectionTableText(labelOf(definition, key, collectionCell(row.record, key)))).join(' | ')} |`);
  return lines.join('\n');
}
function overdueList(definition: CollectionDefinition, rows: readonly CollectionRegisterRow[], asOf: string): string {
  const fields = definition.fields.filter(field => field.overdue);
  const late = rows.filter(row => collectionOverdue(definition, row.record, asOf));
  if (!late.length) return '_None._';
  return late.map(row => `- ${collectionLink(row)} ${collectionTableText(row.record.title)} — ${fields.map(field => `${field.key} ${String(row.record.values[field.key] ?? '')}`).join(', ')}`).join('\n');
}
/**
 * The generated register body: every readable note in report order, the hook's extra section (for example a
 * probability × impact matrix), overdue notes and notes that could not be read. Deterministic for one reference date.
 */
export function collectionRegister(definition: CollectionDefinition, rows: readonly CollectionRegisterRow[], asOf: string, unreadable: readonly string[], extra = ''): string {
  const sections = [`_Generated by \`node bin/app ${definition.id} report\` for ${asOf} from ${rows.length} note(s). Edit the notes, not this block; text outside the markers is yours._`,
    rows.length ? table(definition, rows) : '_No notes yet._'];
  if (extra.trim()) sections.push(extra.trim());
  sections.push('### Overdue', overdueList(definition, rows, asOf));
  if (unreadable.length) sections.push('### Needs attention', unreadable.map(path => `- \`${collectionTableText(path).replace(/`/g, '')}\` (run \`node bin/app ${definition.id} check\`)`).join('\n'));
  return sections.join('\n\n') + '\n';
}
const escaped = (value: string) => value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
/**
 * Places the generated block between hash-stamped markers. Text outside the markers is preserved byte for byte; a
 * register without markers gets the block appended; a block whose content no longer matches its hash was edited by
 * hand and is never overwritten.
 */
export function mergeCollectionRegister(definition: CollectionDefinition, existing: string | null, inner: string, digest: (text: string) => string): string {
  if (existing === null) return `# ${definition.report.title}\n\n${collectionBlock(`${definition.id}-register`, inner, digest)}`;
  return mergeCollectionBlock(`${definition.id}-register`, existing, inner, digest);
}
/** One generated block, `<!-- <name>:start sha256=<hash of inner> -->` … `<!-- <name>:end -->`. */
export const collectionBlock = (name: string, inner: string, digest: (text: string) => string) => `<!-- ${name}:start sha256=${digest(inner)} -->\n${inner}<!-- ${name}:end -->\n`;
/**
 * The generic marker merge behind registers and other generated documents (release candidates): replaces exactly one
 * intact named block, appends it when the text has no such markers, and refuses duplicated, broken or hand-edited blocks.
 */
export function mergeCollectionBlock(name: string, existing: string, inner: string, digest: (text: string) => string): string {
  const start = `<!-- ${name}:start`, end = `<!-- ${name}:end -->`;
  const block = collectionBlock(name, inner, digest);
  const starts = existing.split(start).length - 1, ends = existing.split(end).length - 1;
  if (!starts && !ends) return existing.replace(/\n*$/, existing ? '\n\n' : '') + block;
  const match = new RegExp(`^${escaped(start)} sha256=([0-9a-f]{64}) -->\\n([\\s\\S]*?)^${escaped(end)}[^\\S\\n]*\\n?`, 'm').exec(existing);
  requireSketch(starts === 1 && ends === 1 && match, 'COLLECTION_REGISTER_MARKERS', `Expected exactly one ${start} … ${end} block; nothing was overwritten.`);
  requireSketch(digest(match[2]!) === match[1], 'COLLECTION_REGISTER_EDITED', `The generated ${name} block was edited by hand. Move your text outside the markers (or restore the block); nothing was overwritten.`);
  return existing.slice(0, match.index) + block + existing.slice(match.index + match[0].length);
}
/** An Obsidian Bases table over the collection's notes beside it, in the fake-data Bases format. */
export function collectionBase(definition: CollectionDefinition): Record<string, unknown> {
  const keys = [...new Set(['id', definition.titleField, 'status', ...definition.report.columns])].filter(key => /^[A-Za-z][A-Za-z0-9_]*$/.test(key));
  return {
    filters: { and: ['file.folder == this.file.folder', 'file.ext == "md"', `note.type == "${definition.type}"`] },
    properties: Object.fromEntries(keys.map(key => ['note.' + key, { displayName: heading(definition, key) }])),
    views: [{ type: 'table', name: definition.report.title, order: ['file.name', ...keys.map(key => 'note.' + key)] }],
  };
}
