// Original low-fidelity diagrams: no copied Octopus artwork or remote assets.
function brickSketch(kind){const extended=componentWireframe(kind);if(extended)return extended;
 const shapes={
 heading:'<rect x="12" y="7" width="82" height="7" rx="2"/><rect x="12" y="23" width="160" height="3" rx="1"/><rect x="12" y="31" width="126" height="3" rx="1"/>',
 text:'<path d="M12 9h180M12 18h166M12 27h180M12 36h118"/>',
 navigation:'<rect x="12" y="10" width="35" height="24" rx="3"/><path d="M60 18h29m14 0h29m14 0h38M60 27h120"/>',
 toolbar:'<rect x="12" y="11" width="113" height="23" rx="3"/><circle cx="23" cy="21" r="4"/><path d="m26 24 4 4M139 16h26m11 0h22M139 28h59"/>',
 list:'<rect x="12" y="7" width="17" height="12" rx="2"/><rect x="12" y="27" width="17" height="12" rx="2"/><path d="M41 10h128M41 17h75M41 29h148M41 37h100"/>',
 table:'<rect x="12" y="5" width="188" height="34" rx="2"/><path d="M12 16h188M12 27h188M71 5v34M142 5v34"/>',
 board:'<rect x="12" y="6" width="53" height="34" rx="3"/><rect x="80" y="6" width="53" height="34" rx="3"/><rect x="148" y="6" width="53" height="34" rx="3"/><path d="M21 15h35M21 24h27M89 15h35M157 15h35M157 24h23"/>',
 detail:'<path d="M12 7h60M12 19h38M12 31h50M94 7h105M94 19h80M94 31h98"/>',
 form:'<path d="M12 8h33M12 30h41"/><rect x="73" y="3" width="128" height="14" rx="2"/><rect x="73" y="24" width="128" height="14" rx="2"/>',
 chart:'<path d="M13 5v34h188"/><rect x="28" y="23" width="24" height="15"/><rect x="71" y="14" width="24" height="24"/><rect x="114" y="20" width="24" height="18"/><rect x="157" y="5" width="24" height="33"/>',
 media:'<rect x="12" y="3" width="188" height="37" rx="2"/><path d="m29 33 28-19 28 19 24-27 35 27"/><circle cx="174" cy="15" r="5"/>',
 actions:'<rect x="12" y="10" width="93" height="25" rx="3"/><rect x="120" y="10" width="80" height="25" rx="3"/><path d="M31 23h53M138 23h43"/>',
 empty:'<rect x="12" y="8" width="31" height="28" rx="3"/><path d="M62 13h120M62 23h97M62 33h59"/>',
 notice:'<circle cx="26" cy="23" r="11"/><path d="M26 16v8m0 4v1M51 16h144M51 29h118"/>'
 };
 return `<svg class="brick-wireframe" viewBox="0 0 212 44" aria-hidden="true" focusable="false">${shapes[kind]||shapes.text}</svg>`;
}
function brickTile(n,b,index,mode){
 const spec=BRICK_KINDS[b.kind],value=esc(n.id+':'+b.id),c=design().library.find(c=>c.id===b.definition);
 return `<div class="content-brick nodrag nopan ${brickUi.selected===b.id&&brickUi.node===n.id?'active':''}" data-brick-id="${esc(b.id)}" data-brick-node="${esc(n.id)}" data-group="${spec.group}" style="--ref-block-height:${referenceBrickHeight(b.kind,mode)}px"><button type="button" class="brick-grip nodrag nopan" draggable="true" data-brick-drag="${value}" aria-label="Reorder ${esc(b.title)}. Drag, or use Alt plus Arrow Up or Down." title="Drag to reorder · Alt + ↑ / ↓">${icon('menu')}<span>${String(index+1).padStart(2,'0')}</span></button><button class="brick-open nodrag nopan" data-action="ref-content" data-value="${value}" title="Write content for this screen instance"><span class="brick-title-row"><strong>${esc(b.title)}</strong><span>${c&&b.version!==c.version?'<span class="brick-version-warning" title="Library version changed">Review</span>':''}</span></span>${mode==='wireframes'?referenceSketch(b.kind):''}<span class="brick-kind">${esc(spec.label)}<span>${esc(b.region)}</span></span></button><div class="brick-reorder-actions" role="group" aria-label="Reorder ${esc(b.title)}"><button class="nodrag nopan" data-action="brick-up" data-value="${value}" aria-label="Move ${esc(b.title)} earlier" title="Move earlier" ${index===0?'disabled':''}>${icon('arrow')}</button><button class="nodrag nopan" data-action="brick-down" data-value="${value}" aria-label="Move ${esc(b.title)} later" title="Move later" ${index===bricksOf(n).length-1?'disabled':''}>${icon('arrow')}</button></div></div>`;
}
function brickCardContents(n,lib,children,collapsed){return referenceCardContents(n,lib,children,collapsed);}
function brickViewControl(){const m=brickDisplay();return `<div class="brick-display-bar"><div class="segmented" role="group" aria-label="Card content display">${[['structure','Structure'],['labels','Content blocks'],['wireframes','Wireframes']].map(([id,label])=>`<button data-action="brick-display" data-value="${id}" aria-pressed="${m===id}" class="${m===id?'selected':''}">${label}</button>`).join('')}</div><div class="brick-legend" aria-label="Content roles">${Object.entries(BRICK_GROUPS).map(([id,label])=>`<span data-group="${id}"><i></i>${label}</span>`).join('')}</div>${button('Method','brick-method','','ghost small','help')}</div>`;}
function brickPalette(n){
 const q=brickUi.query.toLowerCase();return design().library.filter(c=>isBrickComponent(c)&&c.status!=='deprecated'&&componentSearchText(c).includes(q)).map(c=>`<button class="brick-palette-item" data-action="library-pick" data-value="${esc(n.id+':'+c.id)}" data-brick-kind="${c.contentSpec.kind}" data-brick-definition="${esc(c.id)}" data-brick-palette-node="${esc(n.id)}" draggable="true" data-group="${BRICK_KINDS[c.contentSpec.kind].group}">${brickSketch(c.contentSpec.kind)}<span><strong>${esc(c.contentSpec.title)}</strong><small>${esc(c.name)} · v${esc(c.version)}<br>${esc(c.description)}</small></span>${icon('plus')}</button>`).join('')||'<p class="small muted">No available components match. Clear the search or add one to your library.</p>';
}
function brickInspector(d,n){
 if(!n)return `<div class="flow-empty-selection"><h2>Structure + content</h2><p>Each card is a screen. Its bricks show what the user sees and does, in order.</p><h3>Start with the main screen</h3><p>Describe the primary experience, then connect the next screens.</p>${button('Focus entry screen','brick-entry','','primary','arrow')}<h3 class="mt24">Or start with the structure</h3><p>Add the key views first, then fill their content stacks.</p>${button('Add a view','design-add','view','small','plus')}<p class="small muted mt24">Every block is a versioned component. Implementation details are maintained on its library definition.</p></div>`;
 if(!canHaveBricks(n))return '<h2>Content is planned on screens</h2><p class="muted">Navigation groups and application actions do not contain visual content. Select a view, internal screen, dialog or settings surface.</p>';
 const items=bricksOf(n);return `<div class="section-head"><h2>Content components</h2>${badge(items.length+'/24')}</div><p class="small muted">${esc(n.label)} · Drag the grip to reorder, or use Earlier / Later.</p>${retainedBindingNotice(n)}<div class="brick-inspector-list">${items.map((b,i)=>`<section class="brick-inspector-item" data-group="${BRICK_KINDS[b.kind].group}"><button class="brick-inspector-open" data-action="brick-edit" data-value="${n.id+':'+b.id}"><span>${i+1}</span><strong>${esc(b.title)}</strong></button><p>${esc(b.purpose||BRICK_KINDS[b.kind].label)}</p><div class="row wrap">${button('Earlier','brick-up',n.id+':'+b.id,'ghost small','',i===0?'disabled':'')}${button('Later','brick-down',n.id+':'+b.id,'ghost small','',i===items.length-1?'disabled':'')}${button('Move / copy','brick-transfer',n.id+':'+b.id,'ghost small')}${button('Definition','library-open',b.definition||'','ghost small')}${design().library.find(c=>c.id===b.definition)?.version!==b.version?button('Review upgrade','library-upgrade',n.id+':'+b.id,'small'):''}${button('Remove','brick-delete',n.id+':'+b.id,'ghost small')}</div></section>`).join('')||'<p class="small muted">No content components placed. Choose one from the library to start this screen.</p>'}</div><div class="row wrap mt16">${button('Add component','brick-add',n.id,'primary','plus')}${button('Starter stack','brick-starter',n.id,'small')}</div><details class="brick-inline-palette inspector-section"><summary>Add from component library</summary><p class="small muted">Click to configure, or drag a block onto a screen.</p>${brickPalette(n)}</details><section class="inspector-section"><h3>One shared component library</h3><p class="small muted">Every brick is a versioned component instance. Reuse its definition, or customize only this screen. Existing code bindings are retained.</p>${button('Manage component library','library-manage',n.id,'ghost small','box')}</section>`;
}
function brickField(label,key,value,rows=0,max=800){return `<label class="field" for="brick-${key}">${label}${rows?`<textarea id="brick-${key}" data-field="brick-${key}" rows="${rows}" maxlength="${max}">${esc(value||'')}</textarea>`:`<input id="brick-${key}" data-field="brick-${key}" value="${esc(value||'')}" maxlength="${max}">`}</label>`;}
function brickEditDialog(){
 const f=brickUi.form,n=design().nodes.find(n=>n.id===f?.node);if(!n)return dialogBody('Brick unavailable','Select its screen again.');
 return dialogBody(f.id?'Edit component instance':'Add component',`<div class="brick-editor-intro"><span data-group="${BRICK_KINDS[f.kind].group}">${brickSketch(f.kind)}</span><div><strong>${esc(n.label)}</strong><p>This is a screen instance of a reusable library component.</p></div></div>${f.definition?`<div class="library-instance-note">${icon('box')}<span><strong>${esc(design().library.find(c=>c.id===f.definition)?.name||f.definition)}</strong> · v${esc(f.version)}<small>Changes here affect only this screen. Manage shared defaults in the component library.</small></span></div>${variantSelect(design().library.find(c=>c.id===f.definition),f.variant||'default','brick-variant')}`:''}<div class="grid2"><label class="field" for="brick-kind">Block type<select id="brick-kind" data-field="brick-kind">${Object.entries(BRICK_KINDS).map(([id,s])=>`<option value="${id}" ${f.kind===id?'selected':''}>${s.label}</option>`).join('')}</select></label><label class="field" for="brick-region">Layout region<select id="brick-region" data-field="brick-region">${componentSlots(n).map(s=>`<option ${s===f.region?'selected':''}>${esc(s)}</option>`).join('')}</select></label></div>${brickField('Block name','title',f.title,0,100)}${brickField('User purpose','purpose',f.purpose,2,800)}${brickField('Content / data / behavior notes','content',f.content,4,4000)}${f.component?'<p class="small muted">Preserved implementation link: '+esc(f.component)+'. This is metadata on the same component instance.</p>':''}<p class="error" id="brick-error" role="alert">${esc(brickUi.error)}</p>`,(f.id?button('Duplicate','brick-duplicate',n.id+':'+f.id,'ghost'):'')+button('Cancel','close','','ghost')+button('Save component','brick-save','','primary','check'));
}
function brickPaletteDialog(){const n=design().nodes.find(n=>n.id===brickUi.node);if(!n)return dialogBody('Choose a surface','Select a visual surface first.');return dialogBody('Add content to '+n.label,`<p>Choose a block, describe its purpose, then save. Wireframes are schematic; they do not execute component code.</p><label class="field" for="brick-search">Find a content block<input id="brick-search" type="search" data-field="brick-search" value="${esc(brickUi.query)}" placeholder="Table, form, empty state…"></label><div class="brick-palette-grid" id="brick-palette-results">${brickPalette(n)}</div>`,button('Manage library','library-manage',n.id,'ghost','box')+button('Cancel','close','','ghost'));}
function brickTransferDialog(){const f=brickUi.move,n=design().nodes.find(n=>n.id===f?.target);if(!f)return dialogBody('Transfer unavailable','Select a content brick.');return dialogBody('Move or copy content',`<p>Transfer this content brick between screens. Connections and screen hierarchy stay unchanged.</p><label class="field" for="brick-target">Destination<select id="brick-target" data-field="brick-target">${design().nodes.filter(n=>canHaveBricks(n)&&n.id!==f.source).map(n=>`<option value="${n.id}" ${n.id===f.target?'selected':''}>${esc(n.label)}</option>`).join('')}</select></label><label class="field" for="brick-move-region">Destination region<select id="brick-move-region" data-field="brick-move-region">${n?componentSlots(n).map(s=>`<option ${s===f.region?'selected':''}>${s}</option>`).join(''):''}</select></label><label class="toggle-line"><input type="checkbox" data-field="brick-copy" ${f.copy?'checked':''}> Keep a copy on the original screen</label><p class="small muted">Mapped components reuse the same library definition. Existing source placements are retained; they are not automatically deleted.</p><p class="error" role="alert">${esc(brickUi.error)}</p>`,button('Cancel','close','','ghost')+button('Confirm transfer','brick-transfer-save','','primary', '',n?'':'disabled'));
}
function brickRemoveDialog(){const f=brickUi.move,{n,b}=findBrick((f?.source||'')+':'+(f?.id||''));return dialogBody('Remove content brick?',`<p>Remove <strong>${esc(b?.title||'this block')}</strong> from ${esc(n?.label||'the screen')}?</p><p>Component placements, requirement links and existing source are retained. Undo restores the content and its order.</p><p class="error" role="alert">${esc(brickUi.error)}</p>`,button('Keep brick','close','','ghost')+button('Remove brick','brick-delete-confirm','','danger'));}
function brickMethodDialog(){return dialogBody('Plan the structure and its content',`<p>Adapted from Octopus.do’s Content Brick Method. Each screen is a page-shaped stack of meaningful content blocks.</p><ol class="method-steps"><li><strong>Start with the primary screen, or outline all views.</strong><p>Both paths use the same sitemap. No setup or generation is triggered.</p></li><li><strong>Describe and order the content.</strong><p>Use low-fidelity blocks to name the information, input and feedback the user needs.</p></li><li><strong>Review the whole experience.</strong><p>Zoom out to compare screens. Keep navigation connections distinct from containment.</p></li><li><strong>Reuse component definitions.</strong><p>Bricks are library components with ordered screen instances. A reusable definition does not certify compiled Vue behavior or passing tests.</p></li></ol><p class="small muted">Drag a brick by its grip to reorder it. Earlier/Later and Move/Copy offer non-drag alternatives. Card positions are presentation data; brick order is content meaning.</p>`,button('Close','close','','ghost')+button('Focus primary screen','brick-entry','','primary','arrow'));}
