import { literal, symbol, type Model } from './model.ts';
import { relativeImport, type Add } from './file-code.ts';
export function uiCode(m: Model, add: Add): void {
  const root = m.sourceRoot; const registry: string[] = []; const panels: string[] = [];
  for (const component of m.components) {
    const id = String(component.id);
    add(`${root}/domain/components/${id}.ts`,`export const specification = ${literal(component)};\n`,'managed');
    // Free-form prop/event descriptions remain design data, never TypeScript or HTML input.
    add(`${root}/presentation/components/library/${id}.vue`,`<script setup lang="ts">\nimport { specification } from '../../../domain/components/${id}.ts';\n</script>\n<template>\n  <section class="generated-component" :aria-label="specification.name">\n    <h3>{{ specification.name }}</h3>\n    <p>{{ specification.description }}</p>\n    <p class="generated-hint">Component implementation point</p>\n    <slot />\n  </section>\n</template>\n`);
  }
  for (const screen of m.screens.filter(s => !['group','action'].includes(s.kind))) {
    const imports = screen.components.map((id,i) => `import C${i} from '../library/${id}.vue';`).join('\n');
    add(`${root}/presentation/components/screens/${screen.slug}.vue`,`<script setup lang="ts">\nimport { useScreen } from '../../composables/use-screen.ts';\n${imports}\nconst model = useScreen(${literal(screen.id)});\n</script>\n<template>\n  <section class="generated-screen" :aria-labelledby="model.headingId">\n    <h2 :id="model.headingId">{{ model.screen.label }}</h2>\n    <p>{{ model.screen.goal }}</p>\n${screen.components.map((_,i) => `    <C${i} />`).join('\n')}\n    <section v-for="flow in model.flows" :key="flow.id" :aria-label="flow.label">\n      <button type="button" :disabled="flow.pending || flow.requiresInput" @click="flow.run()">{{ flow.label }}</button>\n      <p v-if="flow.requiresInput">Implement the input mapping before enabling this action.</p>\n      <p v-if="flow.error" role="status">{{ flow.error }}</p>\n    </section>\n    <button v-for="edge in model.edges" :key="edge.id" type="button" @click="model.follow(edge.id)">{{ edge.label }}</button>\n    <p v-if="model.message.value" role="status">{{ model.message.value }}</p>\n  </section>\n</template>\n`);
    registry.push(`import ${symbol(screen.slug)} from '../presentation/components/screens/${screen.slug}.vue';`); panels.push(`${literal(screen.id)}: ${symbol(screen.slug)}`);
  }
  add(`${root}/bootstrap/panels.ts`,registry.join('\n')+`\nimport type { Component } from 'vue';\nexport const panels: Record<string,Component> = {${panels.join(',\n')}};\n`,'managed');
  add(`${root}/presentation/context/project.ts`,`import { inject, type InjectionKey, type Component } from 'vue';\nexport interface Flow { id: string; card: string; label: string; trigger: string; direction: string; requiresInput: boolean; readonly pending: boolean; readonly error: string | null; run(): Promise<unknown> }\nexport interface ProjectContext { panels: Record<string,Component>; flows: Flow[]; initial?: string; isolated: boolean; openModal(id: string): void }\nexport const projectKey: InjectionKey<ProjectContext> = Symbol('generated-project');\nexport function useProject(): ProjectContext { const context = inject(projectKey); if (!context) throw new Error('PROJECT_CONTEXT_MISSING'); return context; }\n`);
  add(`${root}/presentation/composables/use-screen.ts`,`import { onMounted, ref, useId } from 'vue';\nimport { screens, interactions } from '../../domain/screens.ts';\nimport { useProject } from '../context/project.ts';\nimport { useNavigation } from '../stores/navigation.ts';\nexport function useScreen(id: string) {\n  const context = useProject(); const navigation = useNavigation(); const headingId = useId(); const message = ref('');\n  const screen = screens.find(s => s.id === id); if (!screen) throw new Error('SCREEN_MISSING');\n  const edges = interactions.filter(e => e.from === id); const flows = context.flows.filter(f => f.card === id);\n  onMounted(() => { for (const flow of flows) if (flow.trigger === 'on-open' && flow.direction === 'read' && !flow.requiresInput) void flow.run(); });\n  function follow(edge: string) { const result = navigation.follow(edge); if (result.kind === 'modal') context.openModal(result.target); if (result.kind === 'unimplemented') message.value = 'Implement this interaction before enabling business behavior.'; }\n  return {screen,edges,flows,headingId,message,follow};\n}\n`);
  add(`${root}/presentation/composables/use-workbench.ts`,`import { useProject } from '../context/project.ts';\nimport { screens } from '../../domain/screens.ts';\nimport { useNavigation } from '../stores/navigation.ts';\nexport function useWorkbench() { const context = useProject(); const navigation = useNavigation(); if (context.initial) navigation.open(context.initial); return {context,navigation,items:screens.filter(s => s.nav && !['group','action','modal'].includes(s.kind))}; }\n`);
  add(`${root}/presentation/components/Workbench.vue`,`<script setup lang="ts">\nimport { useWorkbench } from '../composables/use-workbench.ts';\nconst model = useWorkbench();\n</script>\n<template>\n  <div class="generated-workbench">\n    <nav v-if="!model.context.isolated" aria-label="Project navigation">\n      <button v-for="item in model.items" :key="item.id" type="button" :aria-current="model.navigation.current === item.id ? 'page' : undefined" @click="model.navigation.open(item.id)">{{ item.label }}</button>\n      <button type="button" :disabled="!model.navigation.history.length" @click="model.navigation.back()">Back</button>\n    </nav>\n    <main><component :is="model.context.panels[model.navigation.current]" /></main>\n  </div>\n</template>\n`);
  const flowImports = m.sources.map(s => `import { define${symbol(s.slug)}Store } from '../presentation/stores/${s.slug}.ts';`).join('\n');
  const flowStores = m.sources.map(s => `  const ${symbol(s.slug)} = define${symbol(s.slug)}Store(sources[${literal(s.slug)}])(pinia);`).join('\n');
  const flows = m.flows.map(f => {
    const source = m.sources.find(s => s.id === f.source)!; const op = source.operations.find(o => o.id === f.operation)!;
    const state = `${symbol(source.slug)}[${literal(op.slug)}]`;
    return `{id:${literal(f.id)},card:${literal(f.card)},label:${literal(f.label)},trigger:${literal(f.trigger)},direction:${literal(f.direction)},requiresInput:${op.input !== null},get pending(){return ${state}.pending;},get error(){return ${state}.error;},run: ${op.input === null ? `() => ${state}.execute(undefined)` : `async () => ({ok:false,code:'input-mapping-required'})`}}`;
  });
  add(`${root}/bootstrap/flows.ts`,`${flowImports}\nimport type { Pinia } from 'pinia';\nimport type { Sources } from '../application/sources.ts';\nimport type { Flow } from '../presentation/context/project.ts';\nexport function bindFlows(sources: Sources, pinia: Pinia): Flow[] {\n${flowStores}\n  return [${flows.join(',\n')}];\n}\n`,'managed');
  const test = `${m.testRoot}/workbench.test.ts`;
  add(test,`// @vitest-environment happy-dom\nimport { it, expect } from 'vitest';\nimport { mount } from '@vue/test-utils';\nimport { createPinia, disposePinia } from 'pinia';\nimport Workbench from ${literal(relativeImport(test,`${root}/presentation/components/Workbench.vue`))};\nimport { panels } from ${literal(relativeImport(test,`${root}/bootstrap/panels.ts`))};\nimport { projectKey } from ${literal(relativeImport(test,`${root}/presentation/context/project.ts`))};\nit('mounts the generated product screens with isolated view state', async () => { const pinia = createPinia(); const wrapper = mount(Workbench,{global:{plugins:[pinia],provide:{[projectKey as symbol]:{panels,flows:[],isolated:false,openModal:()=>{}}}}}); try { expect(wrapper.find('h2').exists()).toBe(true); for (const button of wrapper.findAll('nav button').filter(b => b.text() !== 'Back')) { await button.trigger('click'); expect(wrapper.find('h2').text()).toBe(button.text()); } } finally { wrapper.unmount(); disposePinia(pinia); } });\n`);
}
