import type { CharacterModelRule } from './definitionTypes'

export const CHARACTER_MODEL_RULES: readonly CharacterModelRule[] = [
  {"id": "voxel-human-v2", "category": "human", "silhouette": "human", "packId": "pack-core", "defaultParts": {"head": "head-classic", "body": "body-tailored", "ears": "ears-none", "tail": "tail-none", "arms": "arms-standard", "screen": "screen-none", "base": "base-legs"}},
  {"id": "voxel-operator-v2", "category": "human", "silhouette": "human", "packId": "pack-workshop", "defaultParts": {"head": "head-compact", "body": "body-utility", "ears": "ears-none", "tail": "tail-none", "arms": "arms-compact", "screen": "screen-none", "base": "base-legs"}},
  {"id": "voxel-scholar-v2", "category": "human", "silhouette": "human", "packId": "pack-core", "defaultParts": {"head": "head-wide", "body": "body-scholar", "ears": "ears-none", "tail": "tail-none", "arms": "arms-standard", "screen": "screen-none", "base": "base-legs"}},
  {"id": "voxel-builder-v2", "category": "human", "silhouette": "human", "packId": "pack-workshop", "defaultParts": {"head": "head-classic", "body": "body-utility", "ears": "ears-none", "tail": "tail-none", "arms": "arms-compact", "screen": "screen-none", "base": "base-legs"}},
  {"id": "voxel-dog-v1", "category": "pet", "silhouette": "quadruped", "packId": "pack-companions", "defaultParts": {"head": "head-dog", "body": "body-long", "ears": "ears-floppy", "tail": "tail-curled", "arms": "arms-none", "screen": "screen-none", "base": "base-paws"}},
  {"id": "voxel-cat-v1", "category": "pet", "silhouette": "quadruped", "packId": "pack-companions", "defaultParts": {"head": "head-cat", "body": "body-compact", "ears": "ears-pointed", "tail": "tail-short", "arms": "arms-none", "screen": "screen-none", "base": "base-paws"}},
  {"id": "voxel-rabbit-v1", "category": "pet", "silhouette": "quadruped", "packId": "pack-companions", "defaultParts": {"head": "head-rabbit", "body": "body-compact", "ears": "ears-tall", "tail": "tail-puff", "arms": "arms-none", "screen": "screen-none", "base": "base-paws"}},
  {"id": "voxel-owl-v1", "category": "animal", "silhouette": "bird", "packId": "pack-wild", "defaultParts": {"head": "head-owl", "body": "body-feather", "ears": "ears-owl", "tail": "tail-none", "arms": "arms-wings", "screen": "screen-none", "base": "base-talons"}},
  {"id": "voxel-fox-v1", "category": "animal", "silhouette": "quadruped", "packId": "pack-wild", "defaultParts": {"head": "head-fox", "body": "body-long", "ears": "ears-pointed", "tail": "tail-fox", "arms": "arms-none", "screen": "screen-none", "base": "base-paws"}},
  {"id": "voxel-turtle-v1", "category": "animal", "silhouette": "quadruped", "packId": "pack-wild", "defaultParts": {"head": "head-turtle", "body": "body-shell", "ears": "ears-none", "tail": "tail-short", "arms": "arms-none", "screen": "screen-none", "base": "base-paws"}},
  {"id": "voxel-talking-head-v1", "category": "item", "silhouette": "head", "packId": "pack-mascots", "defaultParts": {"head": "head-floating", "body": "body-floating", "ears": "ears-none", "tail": "tail-none", "arms": "arms-floating", "screen": "screen-none", "base": "base-hover"}},
  {"id": "voxel-terminal-v1", "category": "item", "silhouette": "object", "packId": "pack-mascots", "defaultParts": {"body": "body-terminal", "ears": "ears-none", "tail": "tail-none", "arms": "arms-none", "screen": "screen-terminal", "base": "base-pedestal"}},
  {"id": "voxel-toolbox-v1", "category": "item", "silhouette": "object", "packId": "pack-workshop", "defaultParts": {"body": "body-toolbox", "ears": "ears-none", "tail": "tail-none", "arms": "arms-clamps", "screen": "screen-dotmatrix", "base": "base-feet"}},
  {"id": "voxel-book-v1", "category": "item", "silhouette": "object", "packId": "pack-mascots", "defaultParts": {"body": "body-book", "ears": "ears-none", "tail": "tail-none", "arms": "arms-floating", "screen": "screen-friendly", "base": "base-hover"}},
  {"id": "voxel-cube-v1", "category": "item", "silhouette": "object", "packId": "pack-mascots", "defaultParts": {"body": "body-cube", "ears": "ears-none", "tail": "tail-none", "arms": "arms-none", "screen": "screen-friendly", "base": "base-hover"}},
]
