import type { CharacterPartRule } from './definitionTypes'

export const CHARACTER_PART_RULES: readonly CharacterPartRule[] = [
  {"id": "head-classic", "slot": "head", "silhouettes": ["human"], "categories": ["human"], "packId": "pack-core"},
  {"id": "head-wide", "slot": "head", "silhouettes": ["human"], "categories": ["human"], "packId": "pack-core"},
  {"id": "head-compact", "slot": "head", "silhouettes": ["human"], "categories": ["human"], "packId": "pack-workshop"},
  {"id": "head-dog", "slot": "head", "silhouettes": ["quadruped"], "categories": ["pet", "animal"], "packId": "pack-companions"},
  {"id": "head-cat", "slot": "head", "silhouettes": ["quadruped"], "categories": ["pet", "animal"], "packId": "pack-companions"},
  {"id": "head-rabbit", "slot": "head", "silhouettes": ["quadruped"], "categories": ["pet", "animal"], "packId": "pack-companions"},
  {"id": "head-fox", "slot": "head", "silhouettes": ["quadruped"], "categories": ["animal", "pet"], "packId": "pack-wild"},
  {"id": "head-turtle", "slot": "head", "silhouettes": ["quadruped"], "categories": ["animal"], "packId": "pack-wild"},
  {"id": "head-owl", "slot": "head", "silhouettes": ["bird"], "categories": ["animal"], "packId": "pack-wild"},
  {"id": "head-floating", "slot": "head", "silhouettes": ["head"], "categories": ["item"], "packId": "pack-mascots"},
  {"id": "body-tailored", "slot": "body", "silhouettes": ["human"], "categories": ["human"], "packId": "pack-core"},
  {"id": "body-utility", "slot": "body", "silhouettes": ["human"], "categories": ["human"], "packId": "pack-workshop"},
  {"id": "body-scholar", "slot": "body", "silhouettes": ["human"], "categories": ["human"], "packId": "pack-core"},
  {"id": "body-compact", "slot": "body", "silhouettes": ["quadruped"], "categories": ["pet", "animal"], "packId": "pack-companions"},
  {"id": "body-long", "slot": "body", "silhouettes": ["quadruped"], "categories": ["pet", "animal"], "packId": "pack-companions"},
  {"id": "body-shell", "slot": "body", "silhouettes": ["quadruped"], "categories": ["animal"], "packId": "pack-wild"},
  {"id": "body-feather", "slot": "body", "silhouettes": ["bird"], "categories": ["animal"], "packId": "pack-wild"},
  {"id": "body-floating", "slot": "body", "silhouettes": ["head"], "categories": ["item"], "packId": "pack-mascots"},
  {"id": "body-terminal", "slot": "body", "silhouettes": ["object"], "categories": ["item"], "packId": "pack-mascots"},
  {"id": "body-toolbox", "slot": "body", "silhouettes": ["object"], "categories": ["item"], "packId": "pack-workshop"},
  {"id": "body-book", "slot": "body", "silhouettes": ["object"], "categories": ["item"], "packId": "pack-mascots"},
  {"id": "body-cube", "slot": "body", "silhouettes": ["object"], "categories": ["item"], "packId": "pack-mascots"},
  {"id": "ears-none", "slot": "ears", "silhouettes": ["human", "quadruped", "head", "object"], "categories": ["human", "pet", "animal", "item"], "packId": "pack-core"},
  {"id": "ears-round", "slot": "ears", "silhouettes": ["quadruped", "head"], "categories": ["pet", "animal", "item"], "packId": "pack-companions"},
  {"id": "ears-floppy", "slot": "ears", "silhouettes": ["quadruped"], "categories": ["pet", "animal"], "packId": "pack-companions"},
  {"id": "ears-pointed", "slot": "ears", "silhouettes": ["quadruped", "head"], "categories": ["pet", "animal", "item"], "packId": "pack-companions"},
  {"id": "ears-tall", "slot": "ears", "silhouettes": ["quadruped", "head"], "categories": ["pet", "animal", "item"], "packId": "pack-companions"},
  {"id": "ears-owl", "slot": "ears", "silhouettes": ["bird"], "categories": ["animal"], "packId": "pack-wild"},
  {"id": "tail-none", "slot": "tail", "silhouettes": ["human", "quadruped", "bird", "head", "object"], "categories": ["human", "pet", "animal", "item"], "packId": "pack-core"},
  {"id": "tail-short", "slot": "tail", "silhouettes": ["quadruped"], "categories": ["pet", "animal"], "packId": "pack-companions"},
  {"id": "tail-curled", "slot": "tail", "silhouettes": ["quadruped"], "categories": ["pet", "animal"], "packId": "pack-companions"},
  {"id": "tail-fox", "slot": "tail", "silhouettes": ["quadruped"], "categories": ["pet", "animal"], "packId": "pack-wild"},
  {"id": "tail-puff", "slot": "tail", "silhouettes": ["quadruped"], "categories": ["pet", "animal"], "packId": "pack-companions"},
  {"id": "arms-standard", "slot": "arms", "silhouettes": ["human"], "categories": ["human"], "packId": "pack-core"},
  {"id": "arms-compact", "slot": "arms", "silhouettes": ["human"], "categories": ["human"], "packId": "pack-workshop"},
  {"id": "arms-wings", "slot": "arms", "silhouettes": ["bird"], "categories": ["animal"], "packId": "pack-wild"},
  {"id": "arms-floating", "slot": "arms", "silhouettes": ["head", "object"], "categories": ["item"], "packId": "pack-mascots"},
  {"id": "arms-clamps", "slot": "arms", "silhouettes": ["object"], "categories": ["item"], "packId": "pack-workshop"},
  {"id": "arms-none", "slot": "arms", "silhouettes": ["quadruped", "head", "object"], "categories": ["pet", "animal", "item"], "packId": "pack-core"},
  {"id": "screen-none", "slot": "screen", "silhouettes": ["human", "quadruped", "bird", "head"], "categories": ["human", "pet", "animal", "item"], "packId": "pack-core"},
  {"id": "screen-friendly", "slot": "screen", "silhouettes": ["object", "head"], "categories": ["item"], "packId": "pack-mascots"},
  {"id": "screen-terminal", "slot": "screen", "silhouettes": ["object"], "categories": ["item"], "packId": "pack-mascots"},
  {"id": "screen-dotmatrix", "slot": "screen", "silhouettes": ["object"], "categories": ["item"], "packId": "pack-workshop"},
  {"id": "base-legs", "slot": "base", "silhouettes": ["human"], "categories": ["human"], "packId": "pack-core"},
  {"id": "base-paws", "slot": "base", "silhouettes": ["quadruped"], "categories": ["pet", "animal"], "packId": "pack-companions"},
  {"id": "base-talons", "slot": "base", "silhouettes": ["bird"], "categories": ["animal"], "packId": "pack-wild"},
  {"id": "base-hover", "slot": "base", "silhouettes": ["head", "object"], "categories": ["item"], "packId": "pack-mascots"},
  {"id": "base-pedestal", "slot": "base", "silhouettes": ["object"], "categories": ["item"], "packId": "pack-mascots"},
  {"id": "base-feet", "slot": "base", "silhouettes": ["object"], "categories": ["item"], "packId": "pack-workshop"},
]
