"""Exact-artifact browser checks. Managed Chromium blocks all URL navigation here.
Render the file bytes with set_content. A clearly marked in-memory Storage test
adapter makes persistence/error paths inspectable; this is not file:// acceptance.
"""
import hashlib, json, os, re, time
from pathlib import Path
from playwright.sync_api import sync_playwright, expect
ROOT=Path(__file__).resolve().parents[1]
HTML=(ROOT/'jev-studio.html').read_text()
RESULTS=[]; ERRORS=[]; NETWORK=[]
def check(name, condition=True):
    if not condition: raise AssertionError(name)
    RESULTS.append({'name':name,'status':'passed'})
STORAGE="""() => {const data={}; window.__testStorage=data; Object.defineProperty(window,'localStorage',{configurable:true,value:{getItem:k=>data[k]??null,setItem:(k,v)=>{data[k]=String(v)},removeItem:k=>delete data[k]}})}"""
with sync_playwright() as p:
    browser=p.chromium.launch(executable_path=os.environ.get('CHROMIUM','/usr/bin/chromium'),headless=True,args=['--no-sandbox'])
    context=browser.new_context(viewport={'width':1512,'height':982},accept_downloads=True)
    page=context.new_page();page.set_default_timeout(4000)
    page.on('pageerror',lambda e:ERRORS.append(str(e)))
    page.on('request',lambda req:NETWORK.append(req.url))
    page.evaluate(STORAGE);page.set_content(HTML);page.wait_for_timeout(200)
    check('Boots with precompiled templates under hash-only script CSP',page.get_by_label('Prompt name',exact=True).input_value()=='Route an inbox note')
    check('Three typed question cards',page.locator('.question-card').count()==3)
    page.screenshot(path=str(ROOT/'evidence/desktop-compose.png'),full_page=True)
    page.get_by_label('Prompt name',exact=True).fill('Route my project inbox')
    page.get_by_label('Option 1 description',exact=True).fill('A specific deliverable with a named owner and next step.')
    page.wait_for_timeout(650)
    stored=page.evaluate("JSON.parse(window.__testStorage['jev-studio.library.v1'])")
    check('Edits persist through the repository adapter',stored['prompts'][0]['name']=='Route my project inbox')
    page.get_by_role('button',name='Export JSON',exact=True).click()
    with page.expect_download() as d: page.get_by_role('button',name='Download JSON',exact=True).click()
    exported=json.loads(Path(d.value.path()).read_text())
    (ROOT/'examples/edited-roundtrip.prompt.json').write_text(json.dumps(exported,indent=2)+'\n')
    check('Actual recipe download contains edited criteria',exported['questions'][0]['options'][0]['description'].startswith('A specific deliverable'))
    check('Recipe download omits resolved note bodies','Alex: request two' not in json.dumps(exported))
    page.get_by_label('Question 1 ID',exact=True).fill('')
    expect(page.locator('.editor-scroll .banner.danger')).to_be_visible()
    page.wait_for_timeout(650)
    check('Invalid draft is not persisted',json.loads(page.evaluate("window.__testStorage['jev-studio.library.v1']"))['prompts'][0]['questions'][0]['id']=='destination')
    page.get_by_label('Question 1 ID',exact=True).fill('destination')
    page.get_by_role('button',name='Save version',exact=True).first.click()
    page.get_by_label('Version message').fill('Baseline before refinement')
    page.locator('.modal').get_by_role('button',name='Save version',exact=True).click()
    page.get_by_label('Prompt name',exact=True).fill('Changed draft')
    page.locator('.workspace-tabs').get_by_role('button',name=re.compile('Versions')).click()
    expect(page.get_by_text('Baseline before refinement',exact=True)).to_be_visible()
    page.get_by_role('button',name='Compare',exact=True).click()
    check('Version comparison exposes changed fields',page.locator('.diff-item').count()>0)
    page.get_by_role('button',name='Restore',exact=True).click()
    page.get_by_role('button',name='Checkpoint and restore',exact=True).click()
    check('Restore recovers recipe name',page.get_by_label('Prompt name',exact=True).input_value()=='Route my project inbox')
    check('Restore preserves checkpoint history',page.locator('.revision-card').count()==2)
    page.locator('.workspace-tabs').get_by_role('button',name='Test bench',exact=True).click()
    page.get_by_role('button',name='Replay fixture',exact=True).click()
    check('Clear fixture shows three local suggestions',page.locator('.result-card .badge.success').count()==3)
    check('Fixture is visibly labeled',page.get_by_text('Synthetic fixture',exact=True).count()==1)
    page.screenshot(path=str(ROOT/'evidence/desktop-testbench.png'),full_page=True)
    page.get_by_label('Fixture scenario').select_option('ambiguous')
    page.get_by_role('button',name='Replay fixture',exact=True).click()
    check('Ambiguous fixture routes all answers to review',page.locator('.result-card .badge.caution').count()==3)
    page.get_by_label('Minimum confidence').fill('0.9')
    expect(page.get_by_text('Inputs changed.',exact=True)).to_be_visible()
    check('Policy edit invalidates previous results',page.locator('.result-card').count()==0)
    page.get_by_role('button',name='Replay fixture',exact=True).click()
    page.get_by_role('button',name='Import response',exact=True).click()
    page.get_by_label('Jev response JSON').fill('{"model":"jev-1.13.0","answers":{},"usage":{"input_tokens":1,"output_tokens":0}}')
    page.locator('.modal .consent input').check()
    page.get_by_role('button',name='Validate response',exact=True).click()
    check('Malformed response is rejected visibly',page.locator('.modal [role=alert]').is_visible())
    page.get_by_role('button',name='Close dialog',exact=True).click()
    page.locator('.workspace-tabs').get_by_role('button',name=re.compile('Vault state')).click()
    page.locator('#vault-files').set_input_files([
      {'name':'Selected.md','mimeType':'text/markdown','buffer':b'---\ntype: project\nstatus: active\nsecret: NEVER_EXPORT_THIS_PROPERTY\n---\n# Local evidence\nPRIVATE_BODY_SENTINEL\n<img src=x onerror="window.__owned=true">\n- [ ] Alex: prepare a plan.\n[[Reference]]'},
      {'name':'Reference.md','mimeType':'text/markdown','buffer':b'# Reference\nRead-only background.'},
      {'name':'Private.md','mimeType':'text/markdown','buffer':b'---\nprivate: true\n---\nDO_NOT_IMPORT'},
      {'name':'Blocked.md','mimeType':'text/markdown','buffer':b'---\nai: false\n---\nDO_NOT_IMPORT_EITHER'},
    ])
    expect(page.get_by_role('button',name='Use this snapshot',exact=True)).to_be_visible()
    check('Markdown import review reports exclusions','2 eligible notes' in page.locator('.modal').inner_text())
    page.get_by_role('button',name='Use this snapshot',exact=True).click()
    check('Markdown import replaces only the in-memory vault',page.locator('.note-table-row').count()==2)
    row=page.locator('.note-table-row').filter(has_text='Selected.md')
    row.get_by_role('button',name='Make active',exact=True).click()
    page.wait_for_timeout(100)
    check('Imported HTML remains inert',page.evaluate('window.__owned===undefined'))
    page.get_by_role('button',name='Export JSON',exact=True).click()
    page.locator('input[type=radio][value=request]').check()
    check('Resolved export requires explicit acknowledgement',page.get_by_role('button',name='Download JSON',exact=True).is_disabled())
    page.locator('.export-review .consent input').check()
    with page.expect_download() as d: page.get_by_role('button',name='Download JSON',exact=True).click()
    request=json.loads(Path(d.value.path()).read_text())
    check('Resolved payload downloads documented envelope',set(request)=={'model','state','questions'})
    check('Actual imported note reaches state','PRIVATE_BODY_SENTINEL' in json.dumps(request))
    check('Unlisted frontmatter does not reach state','NEVER_EXPORT_THIS_PROPERTY' not in json.dumps(request))
    check('Vault bodies never enter the persistence adapter','PRIVATE_BODY_SENTINEL' not in page.evaluate("JSON.stringify(window.__testStorage)"))
    page.get_by_role('button',name='Import prompt JSON',exact=True).click()
    page.locator('#prompt-json').set_input_files({'name':'roundtrip.json','mimeType':'application/json','buffer':json.dumps(exported).encode()})
    expect(page.get_by_role('button',name='Import as copies',exact=True)).to_be_enabled()
    check('File-based JSON import keeps its validation preview',page.locator('.import-summary').is_visible())
    page.get_by_role('button',name='Import as copies',exact=True).click()
    check('Round-trip import preserves originals',page.locator('.prompt-item').count()==5)
    check('Round-trip adds independent copy','imported' in page.get_by_label('Prompt name',exact=True).input_value())
    page.get_by_role('button',name='Add question',exact=True).click()
    page.locator('.template-list').get_by_role('button',name=re.compile('Rate an ordered rubric')).click()
    check('Adds an editable Score question',page.locator('.question-card').count()==4)
    page.get_by_role('button',name='Remove question 4',exact=True).click()
    check('Removes question without deleting the recipe',page.locator('.question-card').count()==3)
    page.get_by_text('Recipe settings',exact=False).click()
    page.get_by_role('button',name='Archive prompt',exact=True).click()
    check('Archive is non-destructive',page.locator('.prompt-item').count()==1)
    page.get_by_role('button',name='Restore from archive',exact=True).click()
    check('Archive restore returns to library',page.locator('.prompt-item').count()==5)
    page.get_by_role('button',name='How it works',exact=True).click()
    for _ in range(3): page.get_by_role('button',name='Next step →',exact=True).click()
    page.get_by_role('button',name='Start creating',exact=True).click()
    check('Four-step tutorial can complete and dismiss',page.locator('.modal').count()==0)
    page.get_by_role('button',name='Toggle light and dark theme',exact=True).click()
    check('Theme switches without changing recipe',page.locator('.studio').get_attribute('data-theme')=='light')
    page.locator('.workspace-tabs').get_by_role('button',name='Compose',exact=True).click()
    page.locator('.editor-scroll').evaluate('(el)=>el.scrollTop=0')
    page.screenshot(path=str(ROOT/'evidence/desktop-light.png'),full_page=True)
    page.get_by_role('button',name='Toggle light and dark theme',exact=True).click()
    for width,height in [(1280,800),(820,1180),(390,844)]:
      page.set_viewport_size({'width':width,'height':height})
      for label in ['Compose','Vault state','Test bench','Versions','JSON']:
        page.locator('.workspace-tabs').get_by_role('button',name=re.compile('^'+label)).click()
        check(f'No document overflow at {width}px in {label}',not page.evaluate('document.documentElement.scrollWidth>innerWidth+1'))
      page.locator('.workspace-tabs').get_by_role('button',name='Compose',exact=True).click()
      page.locator('.editor-scroll').evaluate('(el)=>el.scrollTop=0')
      if width==390: page.screenshot(path=str(ROOT/'evidence/mobile-compose.png'),full_page=True)
    page.get_by_role('button',name='Toggle library',exact=True).click()
    expect(page.get_by_role('button',name='New prompt',exact=True)).to_be_visible()
    page.get_by_role('button',name='New prompt',exact=True).click()
    page.get_by_role('button',name=re.compile('Start blank')).click()
    check('New prompt flow works at mobile width',page.get_by_label('Prompt name',exact=True).input_value()=='Untitled decision')
    check('No page errors during interaction suite',len(ERRORS)==0)
    check('No network requests during interaction suite',len(NETWORK)==0)
    result={'artifactSha256':hashlib.sha256((ROOT/'jev-studio.html').read_bytes()).hexdigest(),'browser':browser.version,'renderMode':'exact HTML bytes via set_content; managed browser blocks file and localhost navigation','storageMode':'in-memory Storage test adapter; native browser persistence not qualified','results':RESULTS,'pageErrors':ERRORS,'networkRequests':NETWORK}
    (ROOT/'evidence/browser.json').write_text(json.dumps(result,indent=2)+'\n')
    print(json.dumps({'passed':len(RESULTS),'pageErrors':ERRORS,'networkRequests':NETWORK},indent=2))
    browser.close()
