"""Business-logic UI acceptance against exact HTML bytes and explicit test Storage.
Not native Obsidian, live inference, or file-origin persistence qualification.
"""
import hashlib,json,os,re
from pathlib import Path
from playwright.sync_api import sync_playwright,expect
ROOT=Path(__file__).resolve().parents[1];HTML=(ROOT/'jev-studio.html').read_text()
RESULTS=[];ERRORS=[];NETWORK=[]
def check(name,condition=True):
    if not condition: raise AssertionError(name)
    RESULTS.append({'name':name,'status':'passed'})
STORAGE="""() => {const data={};window.__testStorage=data;Object.defineProperty(window,'localStorage',{configurable:true,value:{getItem:k=>data[k]??null,setItem:(k,v)=>{if(window.__failStorage)throw Error('Injected storage failure');data[k]=String(v)},removeItem:k=>delete data[k]}})}"""
with sync_playwright() as pw:
    browser=pw.chromium.launch(executable_path=os.environ.get('CHROMIUM','/usr/bin/chromium'),args=['--no-sandbox'])
    context=browser.new_context(viewport={'width':1600,'height':1000},accept_downloads=True)
    def fresh():
        p=context.new_page();p.set_default_timeout(5000);p.on('pageerror',lambda e:ERRORS.append(str(e)));p.on('request',lambda r:NETWORK.append(r.url));p.evaluate(STORAGE);p.set_content(HTML);p.wait_for_timeout(150);return p
    def enter(p):p.get_by_label('Open business logic',exact=True).click()
    def tab(p,name):p.locator('.logic-tabs').get_by_role('button',name=re.compile('^'+re.escape(name))).click()
    def select(p,name):p.locator('.logic-library-item').filter(has_text=name).click()
    def stored(p):return p.evaluate("JSON.parse(window.__testStorage['jev-studio.library.v1'])")
    def save_wait(p):p.wait_for_timeout(800)
    def download(p,name):
        with p.expect_download() as d:p.get_by_role('button',name=name,exact=True).click()
        return json.loads(Path(d.value.path()).read_text())
    def export(p):
        p.get_by_role('button',name='Export workspace',exact=True).click()
        return download(p,'Download workspace JSON')
    def trace(p):
        p.get_by_role('button',name='Export trace',exact=True).click()
        check('Trace download needs fresh explicit consent',p.get_by_role('button',name='Download simulation trace',exact=True).is_disabled())
        p.locator('.modal .consent input').check();return download(p,'Download simulation trace')
    p=fresh();enter(p)
    check('Opening logic is read-only until an edit or explicit run',p.evaluate("window.__testStorage['jev-studio.library.v1']===undefined"))
    check('Default visual graph contains seven real selectable nodes',p.locator('.logic-node').count()==7)
    check('Default visual graph exposes six connections',p.locator('.logic-edge-hit').count()==6)
    p.get_by_role('button',name='How business logic works',exact=True).click()
    check('Business-logic guide opens',p.locator('.logic-explainer').is_visible())
    p.get_by_label('Dismiss logic guide').click()
    p.get_by_role('button',name='Simulate flow',exact=True).click()
    expect(p.locator('.logic-run-heading .badge')).to_have_text('completed')
    check('Real local simulation executes seven connected steps',p.locator('.logic-trace-row').count()==7)
    check('Business decision is inspectable in the trace','process' in p.locator('.logic-trace-row').nth(4).inner_text())
    result=trace(p);check('Simulation export records synthetic/no-external execution',result['inferencePerformed'] is False and result['externalProcessesExecuted'] is False)
    check('Process output actually feeds the second Jev request',result['run']['trace'][5]['request']['state']['workflow_input']['destination']=='project')
    check('Simulated typed event payloads are exported',len(result['run']['events'])==2)
    p.get_by_label('Flow fixture scenario').select_option('ambiguous')
    check('Changing inputs marks earlier trace stale','Stale' in p.locator('.logic-run-heading').inner_text())
    check('Stale trace export is blocked',p.get_by_role('button',name='Export trace',exact=True).is_disabled())
    p.get_by_role('button',name='Simulate flow',exact=True).click()
    expect(p.locator('.logic-run-heading .badge')).to_have_text('review')
    check('Ambiguous results stop before task process',p.locator('.logic-trace-row').count()==4)
    select(p,'A bounded while-loop');p.get_by_role('button',name='Step',exact=True).click()
    check('Step starts a fresh flow and executes one node',p.locator('.logic-trace-row').count()==1)
    p.get_by_role('button',name='Step',exact=True).click()
    check('Step resumes rather than restarting',p.locator('.logic-trace-row').count()==2)
    p.get_by_role('button',name='Cancel run',exact=True).click()
    expect(p.locator('.logic-run-heading .badge')).to_have_text('cancelled');check('Cancel clears scheduled work')
    p.get_by_role('button',name='Simulate flow',exact=True).click()
    expect(p.locator('.logic-run-heading .badge')).to_have_text('completed')
    check('While fixture executes body and exits after nine steps',p.locator('.logic-trace-row').count()==9)
    tab(p,'Business rules');select(p,'Repeat while attempts remain')
    p.get_by_label('While iteration limit').fill('2');save_wait(p)
    tab(p,'Flows');p.get_by_role('button',name='Simulate flow',exact=True).click()
    expect(p.locator('.logic-run-heading .badge')).to_have_text('review')
    check('Editable while bound is enforced in execution','loop_limit' in p.locator('.logic-trace-detail').inner_text())
    p.close()

    # Definition CRUD, typed conditions, draft guard, undo and event contracts.
    p=fresh();enter(p);tab(p,'Business rules')
    p.get_by_role('button',name='New rule',exact=True).click();p.get_by_label('Logic item name',exact=True).fill('Approve expensive requests')
    p.get_by_label('Branch 1 condition 1 right value').fill('10');p.get_by_label('Fallback decision type').select_option('end');save_wait(p)
    check('New business rule persists conditions and typed fallback',stored(p)['logic']['rules'][-1]['fallback']['type']=='end')
    p.get_by_role('button',name=re.compile('^Add an Else-if branch')).click()
    p.get_by_label('Branch 2 name').fill('Second condition');save_wait(p)
    check('Else-if branch can be authored',p.locator('.logic-rule-card:not(.fallback)').count()==2)
    p.get_by_label('Move branch 2 up').click();check('Branch priority can be edited',p.get_by_label('Branch 1 name').input_value()=='Second condition')
    p.get_by_label('Branch 1 condition matching').select_option('any');save_wait(p)
    check('OR matching persists',stored(p)['logic']['rules'][-1]['branches'][0]['match']=='any')
    p.get_by_label('Branch 1 condition 1 right value').fill('invalid_json');save_wait(p)
    check('Malformed condition JSON is visibly retained as an unsaved draft','Draft not saved' in p.locator('.logic-workspace').inner_text())
    check('Invalid condition never overwrites last good canonical library',stored(p)['logic']['rules'][-1]['branches'][0]['conditions'][0]['right']['value']!='invalid_json')
    p.get_by_label('Branch 1 condition 1 right value').fill('5');save_wait(p)
    p.get_by_role('button',name='Duplicate rule',exact=True).click()
    check('Duplicate rule creates an independent definition',p.get_by_label('Logic item name').input_value().endswith('· copy'))
    p.get_by_role('button',name='Archive rule',exact=True).click();check('Rule archive is reversible',p.get_by_role('button',name='Restore rule',exact=True).is_visible())
    p.get_by_role('button',name='Restore rule',exact=True).click()
    p.get_by_role('button',name='Delete rule',exact=True).click();p.get_by_role('button',name='Confirm removal',exact=True).click()
    check('Unused rule is removable without deleting original',len(stored(p)['logic']['rules'])==3)
    select(p,'Route only clear project notes');p.get_by_role('button',name='Delete rule',exact=True).click()
    check('Deletion is blocked for a referenced rule',p.locator('.modal').count()==0 and len(stored(p)['logic']['rules'])==3)
    tab(p,'Processes');p.get_by_role('button',name='New process',exact=True).click();p.get_by_label('Logic item name').fill('Increment invoice total')
    p.get_by_label('Process input 1 type').select_option('number');p.get_by_label('Process output 1 type').select_option('number')
    p.get_by_label('Output mapping 1 mode').select_option('add');p.get_by_label('Output mapping 1 increment').fill('3');save_wait(p)
    check('Named process input/output and safe arithmetic mapping persist',stored(p)['logic']['processes'][-1]['mappings'][0]['binding']['amount']==3)
    p.get_by_role('button',name='+ Add output field',exact=True).click()
    check('Adding output creates an editable schema and mapping',p.get_by_label('Process output 2 name').is_visible() and p.get_by_label('Output mapping 2 value').is_visible())
    p.get_by_label('Remove process output 2').click();check('Removing field removes its mapping',p.get_by_label('Output mapping 2 value').count()==0)
    p.get_by_role('button',name='Duplicate process',exact=True).click();p.get_by_role('button',name='Delete process',exact=True).click();p.get_by_role('button',name='Confirm removal',exact=True).click()
    check('Process duplicate/delete preserves the source contract',len(stored(p)['logic']['processes'])==4)
    tab(p,'Events');p.get_by_label('Event publisher').select_option('prompt:inbox-routing')
    p.get_by_role('button',name='+ Add event',exact=True).click();p.get_by_label('Event 1 name').fill('note.classified')
    p.get_by_role('button',name='Save event contracts',exact=True).click()
    check('Prompt declares an emitted typed event in schema v2',stored(p)['prompts'][0]['schemaVersion']==2 and stored(p)['prompts'][0]['events'][0]['name']=='note.classified')
    check('Event catalog includes prompt contracts','note.classified' in p.locator('.event-catalog').inner_text())
    p.get_by_label('Event 1 name').fill('note.changed');p.get_by_role('button',name='Save event contracts',exact=True).click()
    check('Event rename preserves stable identity',len(stored(p)['prompts'][0]['events'])==1)
    p.get_by_label('Event publisher').select_option('process:prepare_context');p.get_by_label('Remove event 1').click()
    check('Referenced events cannot be deleted underneath listeners',p.locator('.logic-event-card').count()==1)
    p.get_by_label('Event publisher').select_option('rule:routing_policy');p.get_by_role('button',name='+ Add event',exact=True).click();p.get_by_label('Event 2 name').fill('rule.review_requested');p.get_by_label('Event 2 trigger').select_option('review');p.get_by_role('button',name='Save event contracts',exact=True).click()
    check('Rules can declare review-specific events',stored(p)['logic']['rules'][0]['events'][-1]['when']=='review')
    p.get_by_label('Event publisher').select_option('flow:inbox_decision');p.get_by_role('button',name='+ Add event',exact=True).click();p.get_by_label('Event 1 name').fill('flow.finished');p.get_by_role('button',name='Save event contracts',exact=True).click()
    check('Flows can declare lifecycle events',stored(p)['logic']['flows'][0]['events'][0]['name']=='flow.finished')
    p.get_by_label('Event publisher').select_option('node:inbox_decision:start');p.get_by_role('button',name='+ Add event',exact=True).click();p.get_by_label('Event 1 name').fill('flow.started');p.get_by_role('button',name='Save event contracts',exact=True).click()
    check('Start/end or other instances have their own event contracts',stored(p)['logic']['flows'][0]['nodes'][0]['events'][0]['name']=='flow.started')
    p.get_by_label('Event publisher').select_option('prompt:inbox-routing');p.get_by_label('Remove event 1').click();p.get_by_role('button',name='Save event contracts',exact=True).click()
    check('Unreferenced event deletion is persisted explicitly',stored(p)['prompts'][0]['events']==[])
    tab(p,'Checkpoints');p.get_by_role('button',name='Save checkpoint',exact=True).click();p.get_by_label('Logic checkpoint name').fill('Before confidence adjustment');p.get_by_role('button',name='Save logic checkpoint',exact=True).click()
    check('Logic checkpoint captures shared definitions and connections',p.locator('.logic-revision-card').count()==1)
    tab(p,'Business rules');p.get_by_label('Logic item name').fill('Changed routing rule');save_wait(p)
    tab(p,'Checkpoints');p.get_by_text('Changes since this checkpoint',exact=True).click();check('Checkpoint diff shows changed definitions',p.locator('.logic-diff').count()>=1)
    p.get_by_role('button',name='Restore checkpoint',exact=True).click();p.get_by_role('button',name='Checkpoint and restore logic',exact=True).click()
    check('Restore preserves the pre-restore state as a second checkpoint',p.locator('.logic-revision-card').count()==2)
    check('Restore recovers former rule definition',stored(p)['logic']['rules'][0]['name']=='Route only clear project notes')
    exported=export(p);check('Complete workspace export contains all four editable definition collections',exported['schemaVersion']==2 and len(exported['logic']['rules'])==3 and len(exported['logic']['processes'])==4)
    p.get_by_role('button',name='Import workspace JSON',exact=True).click();p.locator('#logic-json-file').set_input_files({'name':'workspace.json','mimeType':'application/json','buffer':json.dumps(exported).encode()})
    expect(p.get_by_role('button',name='Import linked copies',exact=True)).to_be_enabled();check('Actual JSON file import provides review before mutation',p.locator('.modal .import-summary').is_visible())
    p.get_by_role('button',name='Import linked copies',exact=True).click()
    check('Linked import preserves existing work and appends independent copies',len(stored(p)['logic']['flows'])==6 and len(stored(p)['prompts'])==8)
    check('Imported references remain executable',p.get_by_role('button',name='Simulate flow',exact=True).is_enabled())
    p.close()

    # Connection editor, pointer/keyboard placement, undo, privacy and resilience.
    p=fresh();enter(p);select(p,'Event-driven intake');p.get_by_role('button',name='Simulate flow',exact=True).click()
    check('Event-connected prompt/rule chain executes',p.locator('.logic-trace-row').count()==7)
    ev=trace(p);check('Event subscriber receives the emitted typed answers',ev['run']['trace'][3]['input']['answers']['destination']['choice']=='project')
    p.get_by_role('button',name=re.compile('^Simulation trace')).click()
    node=p.get_by_label('Select process node Prepare decision context',exact=True);node.click();node.press('ArrowRight');save_wait(p)
    check('Keyboard movement updates model position',stored(p)['logic']['flows'][2]['nodes'][1]['x']==370)
    box=node.bounding_box();p.mouse.move(box['x']+80,box['y']+30);p.mouse.down();p.mouse.move(box['x']+110,box['y']+60,steps=5);p.mouse.up();save_wait(p)
    check('Pointer drag changes authored node geometry',stored(p)['logic']['flows'][2]['nodes'][1]['x']>370)
    p.get_by_label('Remove connection e2').click();check('Disconnected completion is surfaced as a blocking error',p.get_by_role('button',name='Simulate flow',exact=True).is_disabled())
    p.get_by_label('Connection type').select_option('event');p.get_by_label('Source output').select_option('context_ready');p.get_by_label('Connection destination').select_option('classify');p.get_by_role('button',name='Add connection',exact=True).click()
    check('Typed event output can be connected to the next prompt',p.get_by_role('button',name='Simulate flow',exact=True).is_enabled())
    p.get_by_label('Undo logic change').click();check('Connection addition is undoable',p.get_by_role('button',name='Simulate flow',exact=True).is_disabled())
    p.get_by_label('Redo logic change').click();check('Connection addition is redoable',p.get_by_role('button',name='Simulate flow',exact=True).is_enabled())
    p.get_by_label('New node type').select_option('process');p.get_by_role('button',name='Add node',exact=True).click()
    check('Adding a node does not create fake wiring',p.locator('.logic-node').count()==8 and p.get_by_role('button',name='Simulate flow',exact=True).is_disabled())
    p.get_by_role('button',name='Remove node',exact=True).click();p.get_by_role('button',name='Confirm removal',exact=True).click();check('Node deletion retains shared process definition',p.locator('.logic-node').count()==7 and len(stored(p)['logic']['processes'])==3)
    # Import a real small local Markdown snapshot, not an invented host connection.
    p.get_by_role('button',name='Prompt editor',exact=True).click();p.locator('.workspace-tabs').get_by_role('button',name=re.compile('Vault state')).click()
    p.locator('#vault-files').set_input_files({'name':'Local.md','mimeType':'text/markdown','buffer':b'# Evidence\nPRIVATE_LOGIC_BODY\n<img src=x onerror="window.__owned=true">'})
    p.get_by_role('button',name='Use this snapshot',exact=True).click();enter(p);p.get_by_role('button',name='Simulate flow',exact=True).click()
    private_trace=trace(p);check('Actual selected Markdown reaches prepared Jev inputs', 'PRIVATE_LOGIC_BODY' in json.dumps(private_trace))
    private_workspace=export(p);check('Workspace exports omit runtime vault snapshot and trace','PRIVATE_LOGIC_BODY' not in json.dumps(private_workspace))
    check('Autosave never stores runtime bodies','PRIVATE_LOGIC_BODY' not in p.evaluate('JSON.stringify(window.__testStorage)'))
    check('Imported HTML never executes',p.evaluate('window.__owned===undefined'))
    before=stored(p)['logic']['flows'][2]['name'];p.evaluate('window.__failStorage=true');p.get_by_label('Logic item name').fill('Unsaved title');save_wait(p)
    check('Persistence failure is visible without overwriting durable state','Not saved' in p.locator('.logic-heading-actions').inner_text() and stored(p)['logic']['flows'][2]['name']==before)
    p.evaluate('window.__failStorage=false');p.get_by_label('Logic item name').fill('Recovered title');save_wait(p);check('Later explicit edit can recover persistence',stored(p)['logic']['flows'][2]['name']=='Recovered title')
    p.close()

    p=fresh();enter(p)
    for width,height in [(1600,1000),(1280,900),(820,1180),(390,844)]:
        p.set_viewport_size({'width':width,'height':height})
        for section in ['Flows','Business rules','Processes','Events','Checkpoints','JSON']:
            tab(p,section);check(f'No page overflow at {width}px in {section}',not p.evaluate('document.documentElement.scrollWidth>innerWidth+1'))
        tab(p,'Flows');p.get_by_role('button',name='Simulate flow',exact=True).click()
        check(f'Graph retains usable height with trace at {width}px',p.locator('.logic-stage').bounding_box()['height']>=250)
    p.get_by_role('button',name='Toggle library',exact=True).click();p.get_by_role('button',name='New flow',exact=True).click()
    check('Mobile flow creation works',p.locator('.logic-node').count()==2 and p.get_by_label('Logic item name').input_value()=='New decision flow')
    p.get_by_role('button',name='How business logic works',exact=True).click();check('Guide is usable on a narrow screen',p.locator('.logic-explainer').is_visible())
    p.get_by_label('Dismiss logic guide').click();p.get_by_role('button',name='Toggle light and dark theme',exact=True).click()
    check('Logic uses the existing light theme',p.locator('.studio').get_attribute('data-theme')=='light')
    p.get_by_role('button',name='Export workspace',exact=True).click();p.keyboard.press('Escape');check('Escape dismisses export without side effects',p.locator('.modal').count()==0)
    check('No page errors',not ERRORS);check('No network requests',not NETWORK)
    receipt={'artifactSha256':hashlib.sha256((ROOT/'jev-studio.html').read_bytes()).hexdigest(),'browser':browser.version,'renderMode':'exact HTML via Playwright set_content','storageMode':'explicit in-memory Storage adapter; native persistence not qualified','nativeObsidianTested':False,'liveJevTested':False,'results':RESULTS,'pageErrors':ERRORS,'networkRequests':NETWORK}
    (ROOT/'evidence/logic-browser.json').write_text(json.dumps(receipt,indent=2)+'\n')
    print(json.dumps({'passed':len(RESULTS),'pageErrors':ERRORS,'networkRequests':NETWORK},indent=2));browser.close()
