import { json } from '../../emitters/model.ts';

const manifest = Object.freeze({
  id: 'starter-extension',
  name: 'Starter extension',
  version: '1.0.0',
  description: 'Example typed Workbench project plugin. Replace or remove it when adding product-specific extensions.',
});
const config = Object.freeze({ enabled: true, label: 'Starter extension ready' });
const lines = (...items: string[]): string => items.join('\n') + '\n';

/** Shared generated extension contract. Static registration keeps every host deterministic and bundle-safe. */
export function pluginExtensionFiles(): Record<string, string> {
  const api = lines(
    "import type { project } from './project.ts';",
    "export type AppHost = 'obsidian-plugin' | 'webapp' | 'website' | 'terminal-app' | 'preview';",
    "export interface PluginManifest { readonly id: string; readonly name: string; readonly version: string; readonly description?: string }",
    "export interface PluginConfig { readonly enabled?: boolean; readonly [key: string]: unknown }",
    "export interface PluginContext { readonly host: AppHost; readonly project: typeof project; readonly config: PluginConfig; readonly root?: HTMLElement }",
    "export interface PluginObject { readonly manifest: PluginManifest; readonly config: PluginConfig; activate(context: PluginContext): void | (() => void) }",
  );
  const runtime = lines(
    "import { pluginRegistry } from '../../../plugins/registry.ts';",
    "import { project } from './project.ts';",
    "import type { AppHost, PluginObject } from './plugin-api.ts';",
    "const visualHosts: readonly AppHost[] = ['obsidian-plugin', 'webapp', 'website', 'preview'];",
    "function checkPlugin(plugin: PluginObject, ids: Set<string>): void {",
    "  const { manifest, config } = plugin;",
    "  if (!manifest || !/^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/.test(manifest.id)) throw new Error('PLUGIN_MANIFEST_ID_INVALID');",
    "  if (!manifest.name || !/^\\d+\\.\\d+\\.\\d+$/.test(manifest.version)) throw new Error('PLUGIN_MANIFEST_INVALID: ' + manifest.id);",
    "  if (!config || typeof config !== 'object' || Array.isArray(config)) throw new Error('PLUGIN_CONFIG_INVALID: ' + manifest.id);",
    "  if (ids.has(manifest.id)) throw new Error('PLUGIN_DUPLICATE: ' + manifest.id);",
    "  ids.add(manifest.id);",
    "}",
    "export function visualHost(root: HTMLElement): AppHost {",
    "  const host = root.dataset.appHost as AppHost | undefined;",
    "  if (!host || !visualHosts.includes(host)) throw new Error('PLUGIN_HOST_MISSING');",
    "  return host;",
    "}",
    "export function activatePluginSet(plugins: readonly PluginObject[], host: AppHost, root?: HTMLElement): () => void {",
    "  const ids = new Set<string>(), cleanups: (() => void)[] = [];",
    "  try {",
    "    for (const plugin of plugins) {",
    "      checkPlugin(plugin, ids);",
    "      if (plugin.config.enabled === false) continue;",
    "      const cleanup = plugin.activate({ host, root, project, config: plugin.config });",
    "      if (cleanup !== undefined && typeof cleanup !== 'function') throw new Error('PLUGIN_CLEANUP_INVALID: ' + plugin.manifest.id);",
    "      if (cleanup) cleanups.unshift(cleanup);",
    "    }",
    "  } catch (error) {",
    "    for (const cleanup of cleanups) try { cleanup(); } catch { /* preserve the activation error */ }",
    "    throw error;",
    "  }",
    "  let closed = false;",
    "  return () => {",
    "    if (closed) return;",
    "    closed = true;",
    "    let failure: unknown;",
    "    for (const cleanup of cleanups) try { cleanup(); } catch (error) { failure ??= error; }",
    "    if (failure) throw failure;",
    "  };",
    "}",
    "export function activatePlugins(host: AppHost, root?: HTMLElement): () => void {",
    "  return activatePluginSet(pluginRegistry, host, root);",
    "}",
  );
  const registry = lines(
    "import type { PluginObject as AppPluginObject } from '../src/plugin/core/plugin-api.ts';",
    "import { PluginObject as StarterExtension } from './starter-extension/src/index.ts';",
    "export const pluginRegistry: readonly AppPluginObject[] = [StarterExtension];",
  );
  const extension = lines(
    "import manifest from '../manifest.json' with { type: 'json' };",
    "import config from '../config.json' with { type: 'json' };",
    "import type { PluginObject as AppPluginObject } from '../../../src/plugin/core/plugin-api.ts';",
    "export const PluginObject = {",
    "  manifest,",
    "  config,",
    "  activate({ root, config: resolved }) {",
    "    if (!root) return;",
    "    const previous = root.dataset.starterExtension;",
    "    root.dataset.starterExtension = String(resolved.label ?? manifest.name);",
    "    return () => {",
    "      if (previous === undefined) delete root.dataset.starterExtension;",
    "      else root.dataset.starterExtension = previous;",
    "    };",
    "  },",
    "} satisfies AppPluginObject;",
    "export default PluginObject;",
  );
  const test = lines(
    "import assert from 'node:assert/strict';",
    "import { test } from 'node:test';",
    "import manifest from '../manifest.json' with { type: 'json' };",
    "import config from '../config.json' with { type: 'json' };",
    "import { project } from '../../../src/plugin/core/project.ts';",
    "import { activatePluginSet } from '../../../src/plugin/core/plugin-runtime.ts';",
    "import { PluginObject } from '../src/index.ts';",
    "test('PluginObject is backed by plugin manifest/config and cleans up its extension', () => {",
    "  assert.deepEqual(PluginObject.manifest, manifest);",
    "  assert.deepEqual(PluginObject.config, config);",
    "  const root = { dataset: {} } as unknown as HTMLElement;",
    "  const cleanup = PluginObject.activate({ host: 'webapp', root, project, config });",
    "  assert.equal(root.dataset.starterExtension, config.label);",
    "  assert.equal(typeof cleanup, 'function');",
    "  cleanup?.();",
    "  assert.equal(root.dataset.starterExtension, undefined);",
    "});",
    "test('plugin runtime skips disabled plugins and disposes active plugins in reverse order once', () => {",
    "  const events: string[] = [];",
    "  const plugin = (id: string, enabled = true) => ({",
    "    manifest: { id, name: id, version: '1.0.0' }, config: { enabled },",
    "    activate() { events.push('start:' + id); return () => events.push('stop:' + id); },",
    "  });",
    "  const close = activatePluginSet([plugin('first'), plugin('disabled', false), plugin('second')], 'terminal-app');",
    "  assert.deepEqual(events, ['start:first', 'start:second']);",
    "  close(); close();",
    "  assert.deepEqual(events, ['start:first', 'start:second', 'stop:second', 'stop:first']);",
    "});",
    "test('plugin runtime rejects duplicate IDs and rolls back already activated plugins', () => {",
    "  const events: string[] = [];",
    "  const first = { manifest: { id: 'same', name: 'First', version: '1.0.0' }, config: {}, activate() { events.push('start:first'); return () => events.push('stop:first'); } };",
    "  const duplicate = { manifest: { id: 'same', name: 'Duplicate', version: '1.0.0' }, config: {}, activate() { events.push('start:duplicate'); } };",
    "  assert.throws(() => activatePluginSet([first, duplicate], 'terminal-app'), /PLUGIN_DUPLICATE/);",
    "  assert.deepEqual(events, ['start:first', 'stop:first']);",
    "});",
    "test('plugin runtime rolls back prior plugins when a later activation fails', () => {",
    "  const events: string[] = [];",
    "  const first = { manifest: { id: 'first', name: 'First', version: '1.0.0' }, config: {}, activate() { events.push('start:first'); return () => events.push('stop:first'); } };",
    "  const failing = { manifest: { id: 'failing', name: 'Failing', version: '1.0.0' }, config: {}, activate() { events.push('start:failing'); throw new Error('activation failed'); } };",
    "  assert.throws(() => activatePluginSet([first, failing], 'webapp'), /activation failed/);",
    "  assert.deepEqual(events, ['start:first', 'start:failing', 'stop:first']);",
    "});",
  );
  const readme = lines(
    "# Project plugins",
    "",
    "Extensions live entirely under `plugins/<plugin-name>/`:",
    "",
    "```text",
    "plugins/example/",
    "  manifest.json",
    "  config.json",
    "  src/index.ts        # exports PluginObject",
    "  tests/*.test.ts",
    "```",
    "",
    "Every plugin is TypeScript and exports a named `PluginObject` implementing `src/plugin/core/plugin-api.ts`. The manifest supplies stable identity/version metadata; `config.json` contains project-owned configuration, including optional `enabled: false`.",
    "",
    "Add the plugin's `PluginObject` to `plugins/registry.ts` to activate it. Registration is explicit and statically bundled so Obsidian, web apps, websites and terminal applications use the same deterministic extension set without runtime filesystem discovery.",
    "",
    "`activate(context)` receives the current host, shared project data, the plugin's config and an optional browser/Obsidian root element. Return a cleanup function for every listener, DOM change or resource you own. Plugin code is trusted application code, not a sandbox.",
    "",
    "Keep plugin-specific source and tests inside its directory; do not reach into another plugin's internals. Tests under `plugins/*/tests/` run as part of the generated project's normal `npm test` command.",
    "",
    "The generated `starter-extension` is an executable example. Replace or remove it when establishing the product's real plugin set; if removed, delete its registry import/entry as well.",
  );
  return {
    'src/plugin/core/plugin-api.ts': api,
    'src/plugin/core/plugin-runtime.ts': runtime,
    'plugins/registry.ts': registry,
    'plugins/starter-extension/manifest.json': json(manifest),
    'plugins/starter-extension/config.json': json(config),
    'plugins/starter-extension/src/index.ts': extension,
    'plugins/starter-extension/tests/plugin.test.ts': test,
    'plugins/README.md': readme,
  };
}
