import { makerSymbol as symbol, title } from '../../bin/adapters/makers/arguments.ts';

function pluginLocal(name) {
  const base = symbol(name);
  return base.charAt(0).toUpperCase() + base.slice(1) + 'Plugin';
}
function importBindings(ts, imports) {
  return imports.flatMap(node => {
    const bindings = node.importClause?.namedBindings;
    if (!bindings || !ts.isNamedImports(bindings)) return [];
    const from = ts.isStringLiteral(node.moduleSpecifier) ? node.moduleSpecifier.text : '';
    return bindings.elements.map(item => ({ local: item.name.text, imported: item.propertyName?.text ?? item.name.text, from }));
  });
}
function frozenArray(ts, init) {
  const call = ts.isCallExpression(init) && ts.isPropertyAccessExpression(init.expression) ? init : undefined;
  const target = call?.expression;
  const freezes = target && ts.isIdentifier(target.expression) && target.expression.text === 'Object' && target.name.text === 'freeze';
  return freezes && call.arguments.length === 1 && ts.isArrayLiteralExpression(call.arguments[0]) ? call.arguments[0] : undefined;
}
function registryArray(ts, parsed) {
  let array;
  const declarations = parsed.statements.filter(ts.isVariableStatement).flatMap(statement => statement.declarationList.declarations);
  for (const declaration of declarations) {
    if (!ts.isIdentifier(declaration.name) || declaration.name.text !== 'pluginRegistry' || !declaration.initializer) continue;
    const init = declaration.initializer;
    array = frozenArray(ts, init) ?? (ts.isArrayLiteralExpression(init) ? init : array);
  }
  if (!array || array.elements.some(item => !ts.isIdentifier(item))) throw new Error('PLUGIN_REGISTRY_UNSUPPORTED_SHAPE');
  return array;
}
/** True when the exact generated import and registration already exist; any partial ownership conflicts. */
function alreadyRegistered({ matching, localImports, array, local, from, name }) {
  const registered = array.elements.some(item => item.text === local);
  if (!matching.length && !registered) {
    if (localImports.some(item => item.local === local)) throw new Error('PLUGIN_REGISTRY_CONFLICT:' + local);
    return false;
  }
  const imported = matching.length === 1 && localImports.some(item => item.from === from && item.imported === 'PluginObject' && item.local === local);
  if (imported && registered) return true;
  throw new Error('PLUGIN_REGISTRY_CONFLICT:' + name);
}
async function extendRegistry(source, name) {
  const ts = await import('typescript');
  const parsed = ts.createSourceFile('plugins/registry.ts', source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS);
  if (parsed.parseDiagnostics.length) throw new Error('PLUGIN_REGISTRY_PARSE_ERROR');
  const local = pluginLocal(name), from = './' + name + '/src/index.ts';
  const imports = parsed.statements.filter(ts.isImportDeclaration);
  const matching = imports.filter(node => ts.isStringLiteral(node.moduleSpecifier) && node.moduleSpecifier.text === from);
  const array = registryArray(ts, parsed);
  if (alreadyRegistered({ matching, localImports: importBindings(ts, imports), array, local, from, name })) return source;
  const insertion = array.elements.length ? (array.elements.hasTrailingComma ? ' ' : ', ') + local : local;
  const updated = source.slice(0, array.end - 1) + insertion + source.slice(array.end - 1);
  const lastImport = imports.at(-1);
  if (!lastImport) throw new Error('PLUGIN_REGISTRY_IMPORTS_MISSING');
  return updated.slice(0, lastImport.end) + "\nimport { PluginObject as " + local + " } from '" + from + "';" + updated.slice(lastImport.end);
}

export async function pluginRecipe(context, name) {
  for (const path of ['plugins/api.ts', 'plugins/runtime.ts', 'plugins/registry.ts']) {
    try { await context.read(path); }
    catch (error) {
      if (error?.code === 'ENOENT') throw new Error('PLUGIN_SDK_REQUIRED: make plugin runs only from a Workbench source checkout with plugins/api.ts, plugins/runtime.ts and plugins/registry.ts.');
      throw error;
    }
  }
  const display = title(name);
  const eventLocal = symbol(name) + 'Ready';
  const cliId = name + '-info';
  const actionId = name + '-event';
  const folder = 'plugins/' + name;
  await context.add(folder + '/manifest.json', JSON.stringify({
    id: name, name: display + ' Workbench plugin', version: '1.0.0',
    description: 'Workbench extension generated by make plugin; disabled until reviewed.',
  }, null, 2) + '\n');
  await context.add(folder + '/config.json', JSON.stringify({ enabled: false, message: display + ' ready' }, null, 2) + '\n');
  await context.add(folder + '/src/index.ts', `import manifest from '../manifest.json' with { type: 'json' };
import config from '../config.json' with { type: 'json' };
import { definePluginEvent, type WorkbenchPluginObject } from '../../api.ts';

export const ${eventLocal} = definePluginEvent('${name}.ready',
  (value): value is { source: 'cli' | 'tui' } => Boolean(value && typeof value === 'object'
    && ((value as { source?: unknown }).source === 'cli' || (value as { source?: unknown }).source === 'tui')));

export const PluginObject = {
  manifest,
  config,
  events: [${eventLocal}],
  cli: [{
    id: '${cliId}',
    summary: 'Dispatch the ${display} example event.',
    execute(_request, { eventBus }) {
      eventBus.dispatch(${eventLocal}, { source: 'cli' });
      return { plugin: manifest.id, status: 'ready' };
    },
  }],
  tui: [{
    id: '${actionId}',
    label: '${display}: dispatch example event',
    run({ eventBus, ui }) {
      eventBus.dispatch(${eventLocal}, { source: 'tui' });
      ui.write(String(config.message) + '\\n');
    },
  }],
  activate({ eventBus, progress }) {
    return eventBus.on(${eventLocal}, payload => progress?.('[' + manifest.id + '] ' + payload.source + '\\n'));
  },
} satisfies WorkbenchPluginObject;

export default PluginObject;
`);
  await context.add(folder + '/tests/plugin.test.ts', `import assert from 'node:assert/strict';
import { test } from 'node:test';
import { Readable } from 'node:stream';
import { createPluginRuntime } from '../../runtime.ts';
import { PluginObject, ${eventLocal} } from '../src/index.ts';

const enabled = { ...PluginObject, config: { ...PluginObject.config, enabled: true } };

void test('${name} plugin exposes event, CLI and TUI contributions through one runtime', async () => {
  const received: string[] = [];
  const runtime = await createPluginRuntime({
    root: process.cwd(), frameworkRoot: process.cwd(), input: Readable.from([]), registry: [enabled],
  });
  const off = runtime.eventBus.on(${eventLocal}, payload => received.push(payload.source));
  const command = runtime.cliCommands.find(item => item.id === '${cliId}');
  assert.ok(command);
  assert.deepEqual(await command.execute({ action: '', flags: {} }, runtime.commandContext),
    { plugin: '${name}', status: 'ready' });
  const writes: string[] = [];
  const action = runtime.tuiActions.find(item => item.id === '${actionId}');
  assert.ok(action);
  await action.run({
    ...runtime.commandContext, project: 'design/project.json',
    ui: { ask: async () => '', write: text => writes.push(text) },
    workspace: {} as never,
  });
  assert.deepEqual(received, ['cli', 'tui']);
  assert.ok(writes.length === 1);
  off(); runtime.dispose();
});
`);
  await context.add(folder + '/README.md', `# ${display} Workbench plugin

Generated by \`npm run make -- plugin ${name}\`.

The plugin is disabled in \`config.json\` until its source and capabilities are reviewed. Its starter code demonstrates one typed event, one top-level CLI contribution, one Studio/TUI action, shared event-bus access and deterministic activation cleanup.

Add framework adapters or starter definitions through \`PluginObject.frameworks\` and \`PluginObject.starters\`. Keep all plugin source and tests under this folder.

After editing, run:

\`\`\`sh
npm run check:plugins
npm run test:plugins
npm run typecheck:maker
\`\`\`
`);
  await context.edit('plugins/registry.ts', source => extendRegistry(source, name));
}
