import { localName, locales, registerFactory, generatedTest } from './primitives.mjs';
import { registerEntity } from './entities-recipe.mjs';

/** A new setting is explicit plugin-data storage, sharing the preference writer. */
export async function settingRecipe(context, owner, name) {
  const local = localName(owner, name, 'setting'); const definition = `${local}Feature`;
  const prefix = await locales(context, owner, `${name}-setting`, { title: `Toggle ${name}`, description: 'Boolean feature preference; disabled by default.' });
  await context.add(`src/features/${owner}/${name}.setting-definition.ts`, `import { defineEntity, fields, definePluginDataFeature } from '../api';\n\nexport const ${definition} = definePluginDataFeature({\n  backend: 'plugin-data',\n  entity: defineEntity('${owner}-${name}-setting', 1, { enabled: fields.defaulted(fields.boolean(), false) }),\n});\n`);
  await registerEntity(context, { key: local, local: definition, from: `../features/${owner}/${name}.setting-definition` });
  await context.add(`src/features/${owner}/${name}.setting.ts`, `import { defineCommand } from '../api';\nimport type { PluginDataRepository } from '../../application/plugin-data-repository';\nimport { failure } from '../../domain/outcome';\n\nexport function ${local}(repository: PluginDataRepository<{ enabled?: boolean }, { readonly enabled: boolean }>) {\n  let disposed = false;\n  const command = defineCommand({ id: '${owner}-${name}-setting', titleKey: '${prefix}.title', available: () => !disposed,\n    async execute() {\n      if (disposed) return failure('disposed', 'error.disposed');\n      const current = await repository.list();\n      if (!current.ok) return current;\n      if (disposed) return failure('disposed', 'error.disposed');\n      if (current.value.length > 1) return failure('conflict', 'error.conflict');\n      const saved = current.value[0];\n      return saved ? repository.update(saved, { enabled: !saved.values.enabled }) : repository.create({ enabled: true });\n    },\n  });\n  return { commands: [command] as const, dispose() { disposed = true; } };\n}\n`);
  await registerFactory(context, owner, name, 'setting', `services => ${local}(services.repositories.${local})`);
  await generatedTest(context, owner, name, 'setting', `import { expect, it } from 'vitest';\nimport { PluginDataRepository } from '../../../src/application/plugin-data-repository';\nimport { ${definition} } from '../../../src/features/${owner}/${name}.setting-definition';\nimport { ${local} } from '../../../src/features/${owner}/${name}.setting';\nimport { authoringFixture } from '../authoring-fixture';\n\nit('validates defaults, persists only explicit changes, and preserves shared preferences', async () => {\n  const f = await authoringFixture(); let next = 0;\n  const repository = new PluginDataRepository(${definition}.entity, f.data, f.services.events, () => 'setting-' + ++next, () => '2026-09-23', f.services.diagnostics);\n  const extension = ${local}(repository); const command = extension.commands[0];\n  try {\n    expect(${definition}.entity.parse({})).toEqual({ ok: true, value: { enabled: false } });\n    expect(${definition}.entity.decode({ enabled: 'true' }).ok).toBe(false);\n    expect(command.available?.()).toBe(true); expect(f.saved).toHaveLength(0);\n    await command.execute(); await f.services.preferences.update({ notifySuccess: false });\n    const first = await repository.list(); if (!first.ok) throw new Error('list failed');\n    expect(first.value[0]?.values.enabled).toBe(true);\n    await command.execute(); const second = await repository.list();\n    if (!second.ok) throw new Error('list failed'); expect(second.value[0]?.values.enabled).toBe(false);\n    expect(f.services.preferences.current.notifySuccess).toBe(false);\n    extension.dispose(); expect(command.available?.()).toBe(false);\n    const count = f.saved.length; await command.execute(); expect(f.saved).toHaveLength(count);\n  } finally { extension.dispose(); repository.dispose(); f.dispose(); }\n});\n`);
}
