/** Tooling-only metadata. The production graph imports events.ts, never this module. */
import type { EventDefinition } from '../application/event-definition';
import * as core from '../application/event-definitions/core';
import * as host from '../application/event-definitions/host';
export interface EventCatalogEntry {
  readonly definition: EventDefinition;
  readonly owner: string;
  readonly meaning: string;
  readonly version: number;
  readonly publisher: string;
  readonly subscribers: readonly string[];
  readonly origin: 'application' | 'obsidian' | 'harness';
  readonly sensitivity: 'none' | 'identifiers' | 'vault-paths';
  readonly delivery: string;
}
export const coreEventCatalog: readonly EventCatalogEntry[] = [
  {
    definition: core.pluginDataCreated,
    owner: 'plugin-data',
    meaning: 'Committed plugin-data.created fact',
    version: 1,
    publisher: 'PluginDataRepository',
    subscribers: ['view projections'],
    origin: 'application',
    sensitivity: 'identifiers',
    delivery: 'Synchronous start; snapshot; no replay; owned subscriptions.',
  },
  {
    definition: core.pluginDataUpdated,
    owner: 'plugin-data',
    meaning: 'Committed plugin-data.updated fact',
    version: 1,
    publisher: 'PluginDataRepository',
    subscribers: ['view projections'],
    origin: 'application',
    sensitivity: 'identifiers',
    delivery: 'Synchronous start; snapshot; no replay; owned subscriptions.',
  },
  {
    definition: core.pluginDataDeleted,
    owner: 'plugin-data',
    meaning: 'Committed plugin-data.deleted fact',
    version: 1,
    publisher: 'PluginDataRepository',
    subscribers: ['view projections'],
    origin: 'application',
    sensitivity: 'identifiers',
    delivery: 'Synchronous start; snapshot; no replay; owned subscriptions.',
  },
  {
    definition: core.documentCreated,
    owner: 'documents',
    meaning: 'Committed documents.created fact',
    version: 1,
    publisher: 'DocumentCreationService / NoteRepository',
    subscribers: ['view projections'],
    origin: 'application',
    sensitivity: 'vault-paths',
    delivery: 'Synchronous start; snapshot; no replay; owned subscriptions.',
  },
  {
    definition: core.documentUpdated,
    owner: 'documents',
    meaning: 'Committed documents.updated fact',
    version: 1,
    publisher: 'DocumentCreationService / NoteRepository',
    subscribers: ['view projections'],
    origin: 'application',
    sensitivity: 'vault-paths',
    delivery: 'Synchronous start; snapshot; no replay; owned subscriptions.',
  },
  {
    definition: core.documentDeleted,
    owner: 'documents',
    meaning: 'Committed documents.deleted fact',
    version: 1,
    publisher: 'DocumentCreationService / NoteRepository',
    subscribers: ['view projections'],
    origin: 'application',
    sensitivity: 'vault-paths',
    delivery: 'Synchronous start; snapshot; no replay; owned subscriptions.',
  },
  {
    definition: core.preferencesChanged,
    owner: 'preferences',
    meaning: 'Committed preferences.changed fact',
    version: 1,
    publisher: 'PreferenceService',
    subscribers: ['view projections'],
    origin: 'application',
    sensitivity: 'none',
    delivery: 'Synchronous start; snapshot; no replay; owned subscriptions.',
  },
  {
    definition: host.activeFileChanged,
    owner: 'host-bridge',
    meaning: 'Normalized host notification for host.active-file-changed',
    version: 1,
    publisher: 'ObsidianEventBridge',
    subscribers: ['view projections'],
    origin: 'obsidian',
    sensitivity: 'none',
    delivery: 'Synchronous start; snapshot; no replay; owned subscriptions.',
  },
  {
    definition: host.entryCreated,
    owner: 'host-bridge',
    meaning: 'Normalized host notification for host.vault.entry-created',
    version: 1,
    publisher: 'ObsidianEventBridge',
    subscribers: ['view projections'],
    origin: 'obsidian',
    sensitivity: 'vault-paths',
    delivery: 'Synchronous start; snapshot; no replay; owned subscriptions.',
  },
  {
    definition: host.entryModified,
    owner: 'host-bridge',
    meaning: 'Normalized host notification for host.vault.entry-modified',
    version: 1,
    publisher: 'ObsidianEventBridge',
    subscribers: ['view projections'],
    origin: 'obsidian',
    sensitivity: 'vault-paths',
    delivery: 'Synchronous start; snapshot; no replay; owned subscriptions.',
  },
  {
    definition: host.entryRenamed,
    owner: 'host-bridge',
    meaning: 'Normalized host notification for host.vault.entry-renamed',
    version: 1,
    publisher: 'ObsidianEventBridge',
    subscribers: ['view projections'],
    origin: 'obsidian',
    sensitivity: 'vault-paths',
    delivery: 'Synchronous start; snapshot; no replay; owned subscriptions.',
  },
  {
    definition: host.entryDeleted,
    owner: 'host-bridge',
    meaning: 'Normalized host notification for host.vault.entry-deleted',
    version: 1,
    publisher: 'ObsidianEventBridge',
    subscribers: ['view projections'],
    origin: 'obsidian',
    sensitivity: 'vault-paths',
    delivery: 'Synchronous start; snapshot; no replay; owned subscriptions.',
  },
  {
    definition: host.fileOpened,
    owner: 'host-bridge',
    meaning: 'Normalized host notification for host.workspace.file-opened',
    version: 1,
    publisher: 'ObsidianEventBridge',
    subscribers: ['view projections'],
    origin: 'obsidian',
    sensitivity: 'vault-paths',
    delivery: 'Synchronous start; snapshot; no replay; owned subscriptions.',
  },
  {
    definition: host.activeViewChanged,
    owner: 'host-bridge',
    meaning: 'Normalized host notification for host.workspace.active-view-changed',
    version: 1,
    publisher: 'ObsidianEventBridge',
    subscribers: ['view projections'],
    origin: 'obsidian',
    sensitivity: 'none',
    delivery: 'Synchronous start; snapshot; no replay; owned subscriptions.',
  },
  {
    definition: host.layoutChanged,
    owner: 'host-bridge',
    meaning: 'Normalized host notification for host.workspace.layout-changed',
    version: 1,
    publisher: 'ObsidianEventBridge',
    subscribers: ['view projections'],
    origin: 'obsidian',
    sensitivity: 'none',
    delivery: 'Synchronous start; snapshot; no replay; owned subscriptions.',
  },
  {
    definition: host.metadataChanged,
    owner: 'host-bridge',
    meaning: 'Normalized host notification for host.metadata.changed',
    version: 1,
    publisher: 'ObsidianEventBridge',
    subscribers: ['view projections'],
    origin: 'obsidian',
    sensitivity: 'vault-paths',
    delivery: 'Synchronous start; snapshot; no replay; owned subscriptions.',
  },
];
